package factories

import (
	"github.com/TrashPony/veliri-lib/game_objects/book"
)

const sizeBook = 250

var booksTypes = map[int]book.Book{
	1: {
		ID:      1,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 23,
	},
	2: {
		ID:      2,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 25,
	},
	3: {
		ID:      3,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 26,
	},
	4: {
		ID:      4,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 27,
	},
	5: {
		ID:      5,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 28,
	},
	6: {
		ID:      6,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 29,
	},
	7: {
		ID:      7,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 30,
	},
	8: {
		ID:      8,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 31,
	},
	9: {
		ID:      9,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 32,
	},
	10: {
		ID:      10,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 33,
	},
	11: {
		ID:      11,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 34,
	},
	12: {
		ID:      12,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 35,
	},
	13: {
		ID:      13,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 36,
	},
	14: {
		ID:      14,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 37,
	},
	15: {
		ID:      15,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 38,
	},
	16: {
		ID:      16,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 39,
	},
	17: {
		ID:      17,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 40,
	},
	18: {
		ID:      18,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 41,
	},
	19: {
		ID:      19,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 42,
	},
	20: {
		ID:      20,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 43,
	},
	21: {
		ID:      21,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 44,
	},
	22: {
		ID:      22,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 45,
	},
	23: {
		ID:      23,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 46,
	},
	24: {
		ID:      24,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 47,
	},
	25: {
		ID:      25,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 48,
	},
	26: {
		ID:      26,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 49,
	},
	27: {
		ID:      27,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 50,
	},
	28: {
		ID:      28,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 51,
	},
	29: {
		ID:      29,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 52,
	},
	30: {
		ID:      30,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 53,
	},
	32: {
		ID:      32,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 55,
	},
	33: {
		ID:      33,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 56,
	},
	34: {
		ID:      34,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 57,
	},
	35: {
		ID:      35,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 58,
	},
	36: {
		ID:      36,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 59,
	},
	37: {
		ID:      37,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 60,
	},
	38: {
		ID:      38,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 61,
	},
	39: {
		ID:      39,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 62,
	},
	40: {
		ID:      40,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 63,
	},
	41: {
		ID:      41,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 64,
	},
	42: {
		ID:      42,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 65,
	},
	52: {
		ID:      52,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 75,
	},
	53: {
		ID:      53,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 76,
	},
	54: {
		ID:      54,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 77,
	},
	55: {
		ID:      55,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 78,
	},
	56: {
		ID:      56,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 79,
	},
	57: {
		ID:      57,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 80,
	},
	58: {
		ID:      58,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 81,
	},
	59: {
		ID:      59,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 82,
	},
	60: {
		ID:      60,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 83,
	},
	61: {
		ID:      61,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 84,
	},
	62: {
		ID:      62,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 85,
	},
	63: {
		ID:      63,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 86,
	},
	64: {
		ID:      64,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 87,
	},
	65: {
		ID:      65,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 88,
	},
	66: {
		ID:      66,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 89,
	},
	67: {
		ID:      67,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 90,
	},
	68: {
		ID:      68,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 91,
	},
	69: {
		ID:      69,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 92,
	},
	70: {
		ID:      70,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 93,
	},
	71: {
		ID:      71,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 94,
	},
	72: {
		ID:      72,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 95,
	},
	73: {
		ID:      73,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 96,
	},
	74: {
		ID:      74,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 97,
	},
	75: {
		ID:      75,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 98,
	},
	76: {
		ID:      76,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 99,
	},
	77: {
		ID:      77,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 100,
	},
	78: {
		ID:      78,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 101,
	},
	79: {
		ID:      79,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 102,
	},
	80: {
		ID:      80,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 103,
	},
	81: {
		ID:      81,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 104,
	},
	82: {
		ID:      82,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 105,
	},
	83: {
		ID:      83,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 106,
	},
	84: {
		ID:      84,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 107,
	},
	85: {
		ID:      85,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 108,
	},
	86: {
		ID:      86,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 109,
	},
	87: {
		ID:      87,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 110,
	},
	88: {
		ID:      88,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 111,
	},
	89: {
		ID:      89,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 112,
	},
	90: {
		ID:      90,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 113,
	},
	91: {
		ID:      91,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 114,
	},
	92: {
		ID:      92,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 115,
	},
	93: {
		ID:      93,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 116,
	},
	94: {
		ID:      94,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 117,
	},
	95: {
		ID:      95,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 118,
	},
	96: {
		ID:      96,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 119,
	},
	97: {
		ID:      97,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 120,
	},
	98: {
		ID:      98,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 121,
	},
	99: {
		ID:      99,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 122,
	},
	100: {
		ID:      100,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 123,
	},
	101: {
		ID:      101,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 124,
	},
	102: {
		ID:      102,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 125,
	},
	103: {
		ID:      103,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 126,
	},
	104: {
		ID:      104,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 127,
	},
	105: {
		ID:      105,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 128,
	},
	106: {
		ID:      106,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 129,
	},
	107: {
		ID:      107,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 130,
	},
	108: {
		ID:      108,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 131,
	},
	109: {
		ID:      109,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 132,
	},
	110: {
		ID:      110,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 133,
	},
	111: {
		ID:      111,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 134,
	},
	112: {
		ID:      112,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 135,
	},
	113: {
		ID:      113,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 136,
	},
	114: {
		ID:      114,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 137,
	},
	115: {
		ID:      115,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 138,
	},
	116: {
		ID:      116,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 139,
	},
	117: {
		ID:      117,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 140,
	},
	118: {
		ID:      118,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 141,
	},
	119: {
		ID:      119,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 142,
	},
	120: {
		ID:      120,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 143,
	},
	121: {
		ID:      121,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 144,
	},
	122: {
		ID:      122,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 145,
	},
	123: {
		ID:      123,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 146,
	},
	124: {
		ID:      124,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 147,
	},
	125: {
		ID:      125,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 148,
	},
	126: {
		ID:      126,
		Name:    "default_Explores",
		Size:    sizeBook,
		SkillID: 149,
	},
	127: {
		ID:      127,
		Name:    "default_Replics",
		Size:    sizeBook,
		SkillID: 150,
	},
	128: {
		ID:      128,
		Name:    "default_Reverses",
		Size:    sizeBook,
		SkillID: 151,
	},
	129: {
		ID:      129,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 152,
	},
	130: {
		ID:      130,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 153,
	},
	131: {
		ID:      131,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 154,
	},
	132: {
		ID:      132,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 155,
	},
	133: {
		ID:      133,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 156,
	},
	134: {
		ID:      134,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 157,
	},
	135: {
		ID:      135,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 158,
	},
	136: {
		ID:      136,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 159,
	},
	137: {
		ID:      137,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 160,
	},
	138: {
		ID:      138,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 161,
	},
	139: {
		ID:      139,
		Name:    "default",
		Size:    sizeBook,
		SkillID: 162,
	},
}

func GetBook(id int) *book.Book {
	newBook := booksTypes[id]
	return &newBook
}

func GetAllBook() map[int]book.Book {
	return booksTypes
}
