package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var AmmoDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"piu-piu":                       {Name: "B-a medium-caliber projectile", Description: "<p> A standardized type of medium-caliber projectiles for kinetic and ballistic weapons that provide significant damage, but, as a rule, are not always distinguished by accuracy and high rate of fire. </p>"},
		"piu-piu_2":                     {Name: "B-a small-caliber projectile", Description: "<p> A standardized type of small-bore projectiles for kinetic and ballistic weapons that do not provide high damage, but, as a rule, contribute to high accuracy and rate of fire. </p>"},
		"piu-piu_3":                     {Name: "Бронебойный мелкокалиберный снаряд", Description: "<p></p>"},
		"piu-piu_4":                     {Name: "Разрывной мелкокалиберный снаряд", Description: "<p></p>"},
		"piu-piu_5":                     {Name: "Бронебойный среднекалиберной снаряд", Description: "<p></p>"},
		"piu-piu_6":                     {Name: "Кумулятивный среднекалиберной снаряд", Description: "<p></p>"},
		"medium_lens":                   {Name: "Medium focusing cartridge", Description: "<p> Standardized cartridge for charging medium and large laser beam impact equipment. </p>"},
		"aim_medium_missile_bullet":     {Name: "Cicada - Homing Medium Missile", Description: "<p> Cicada - development of a line of unguided missiles of the Sistema family with the aim of creating homing shells. Provides average damage to any captured targets. </p>"},
		"aim_big_missile_bullet":        {Name: "Vindicator - Homing Large Rocket", Description: "<p> The Vindicator is a continuation of ideas started in Cicada and the Sistema unguided rockets family. This homing missile, which can only be used in large rocket firing systems, is a real terror to the enemies it captures. </p>"},
		"ballistics_artillery_bullet":   {Name: "B-a large-caliber projectile", Description: "<p> A standardized type of large-caliber projectiles for kinetic and ballistic weapons that guarantee devastating damage, but cannot be used with rapid-fire or extremely accurate weapons. </p>"},
		"ballistics_artillery_bullet_3": {Name: "Бронебойный крупнокалиберный снаряд", Description: "<p></p>"},
		"ballistics_artillery_bullet_4": {Name: "Кумулятивный крупнокалиберный снаряд", Description: "<p></p>"},
		"medium_missile_bullet":         {Name: "System.A-2 - Medium missile", Description: "<p> Massive and military-standardized missile of medium destructive power. Cannot be used in high-dimensional missile system weapons. </p>"},
		"big_missile_bullet":            {Name: "System.O-5 - Large rocket", Description: "<p> Massive and military-standardized missile of great destructive power. Cannot be used in missile weapons with an average overall weight or less. </p>"},
		"small_lens":                    {Name: "Small focusing cartridge", Description: "<p> Standardized cartridge for charging small and medium-sized laser beam impact tools. </p>"},
		"small_lens_beam":               {Name: "Малый лучевой картридж", Description: "<p></p>"},
		"small_missile_bullet":          {Name: "Малая ракета", Description: "<p></p>"},
		"big_lens_1":                    {Name: "big_lens_1", Description: "<p></p>"},
		"medium_lens_beam":              {Name: "medium_lens_beam", Description: "<p></p>"},
	},
	_const.RU: {
		"piu-piu":                       {Name: "Б-а среднекалиберной снаряд", Description: "<p>Стандартизированный тип среднекалиберных снарядов для кинетических и баллистических орудий, обеспечивающих ощутимый урон, но, как правило, не всегда отличающихся кучностью и высокой скорострельностью.</p>"},
		"ballistics_artillery_bullet":   {Name: "Б-а крупнокалиберный снаряд", Description: "<p>Стандартизированный тип крупнокалиберных снарядов для кинетических и баллистических орудий, гарантирующих сокрушительный урон, но невозможных к применению в скорострельных или крайне точных орудиях.</p>"},
		"ballistics_artillery_bullet_3": {Name: "Бронебойный крупнокалиберный снаряд", Description: "<p>Разновидность боеприпаса, предназначенного для противодействия тяжёлой бронетехнике. Характеризуется высокой скоростью полёта и достаточной точностью на дальних дистанциях. Впрочем, всячески неспособна обеспечивать урон по площади.</p>"},
		"ballistics_artillery_bullet_4": {Name: "Панцирные заряды", Description: "<p>Боеприпасы чьё назначение - поражение тяжело бронированных целей. Заряды обладают поразительной точностью и внушительным уроном, но будут абсолютно бесполезны в бою на дальних дистанциях или, при попытке поразить сразу несколько целей.</p>"},
		"medium_missile_bullet":         {Name: "Система.А-2 - Средняя ракета", Description: "<p>Массовая и стандартизированная под военные нужды ракета средней поражающей силы. Невозможна к использования в орудиях ракетной системы высоко-габаритного образца.</p>"},
		"big_missile_bullet":            {Name: "Система.О-5 - Большая ракета", Description: "<p>Массовая и стандартизированная под военные нужды ракета большой поражающей силы. Невозможна к использования в ракетных орудиях средней габаритной массы или меньше.</p>"},
		"small_lens":                    {Name: "Малый фокусирующий картридж", Description: "<p>Стандартизированный картридж для зарядки в малые и средние орудия лазерно-лучевого воздействия.</p>"},
		"medium_lens":                   {Name: "Средний фокусирующий картридж", Description: "<p>Стандартизированный картридж для зарядки в средние и крупные орудия лазерно-лучевого воздействия.</p>"},
		"piu-piu_2":                     {Name: "Б-а мелкокалиберный снаряд", Description: "<p>Стандартизированный тип мелкокалиберных снарядов для кинетических и баллистических орудий, не обеспечивающих высокий урон, но, как правило, способствующие высокой кучности и скорострельности.</p>"},
		"piu-piu_3":                     {Name: "ББ-м “Игла”", Description: "<p>Мелкокалиберный бронебойный снаряд повышенной точности, специально спроектированный для использования в малых орудиях по типу: пушек/пулемётов.</p>"},
		"piu-piu_4":                     {Name: "Деформирующие пули", Description: "<p>Мелкокалиберный снаряд осколочно-фугасного действия, специально спроектированный для использования в малых орудиях по типу: пушек/пулемётов. </p>"},
		"piu-piu_5":                     {Name: "ББ-с “Прорыв”", Description: "<p>Бронебойный снаряд средних размеров, предназначается для поражения усреднённо бронированных целей и зачастую встречается как боезаряд к крупным орудиям.</p>"},
		"piu-piu_6":                     {Name: "Капсульные боеприпасы", Description: "<p>Тип снарядов, обладающих высокой пробивной силой и эффективных против любых целей, принося в жертву малую дальность полёта и шанс высокого отклонения после выстрела.</p>"},
		"aim_medium_missile_bullet":     {Name: "Цикада - Самонаводящиеся средняя ракета", Description: "<p>Цикада – развитие линейки неуправляемых ракет семейства «Система» с целью создания самонаводящихся на цель снарядов. Обеспечивает усреднённый урон по любым захваченным целям.</p>"},
		"aim_big_missile_bullet":        {Name: "Воздаятель - Самонаводящиеся большая ракета", Description: "<p>Воздаятель – продолжение идей, начатых в «Цикада» и линейке семейства неуправляемых ракет «Система». Эта самонаводящаяся ракета, что может быть использована только в крупногабаритных ракетных огневых системах, истинный ужас для врагов, что были ею захвачены.</p>"},
		"small_lens_beam":               {Name: "Лучевой картридж", Description: "<p>Проводник энергии для лучевого оружия, наносящий многослойные ожоги по вражескую броню. Как правило встраивается в малогабаритные и легкодоступные лучевые пушки.</p>"},
		"small_missile_bullet":          {Name: "Малая ракета", Description: "<p>Оружие реактивного типа, способное за кратчайшие сроки достигнуть далеко удалённых целей и нанести тем урон.</p>"},
		"big_lens_1":                    {Name: "Лучевой Блок", Description: "<p>Накопитель источника энергии для лучевого оружия, наносящий крупные повреждения за счёт широко направленного потока излучения. Данные боеприпасы, встречаются сугубо у объёмных и технически сложных орудий.</p>"},
		"medium_lens_beam":              {Name: "Фокусирующий картридж", Description: "<p>Проводник энергии для лучевого оружия, наносящий глубокие точечные прорези во вражеской броне. Подобные картриджи в основном являются неотъемлемыми источниками питания для орудий среднего тоннажа.</p>"},
	},
	_const.ZhCN: {
		"piu-piu":                       {Name: "中口径弹药", Description: "<p>标准化的中口径弹药，适用于动能和弹道武器，提供显著的伤害，但通常不以高精度和高射速著称。</p>"},
		"piu-piu_2":                     {Name: "小口径弹药", Description: "<p>标准化的小口径弹药，适用于动能和弹道武器，伤害较低，但通常具有高精度和高射速。</p>"},
		"piu-piu_3":                     {Name: "小口径穿甲弹", Description: "<p></p>"},
		"piu-piu_4":                     {Name: "小口径爆破弹", Description: "<p></p>"},
		"piu-piu_5":                     {Name: "中口径穿甲弹", Description: "<p></p>"},
		"piu-piu_6":                     {Name: "中口径聚能弹", Description: "<p></p>"},
		"medium_lens":                   {Name: "中型聚焦弹药", Description: "<p>标准化的中型和大型激光束冲击设备的弹药。</p>"},
		"aim_medium_missile_bullet":     {Name: "蝉 - 中型制导导弹", Description: "<p>蝉 - 系统家族非制导导弹的改进型，旨在创建制导弹药。对任何捕获的目标提供中等伤害。</p>"},
		"aim_big_missile_bullet":        {Name: "复仇者 - 大型制导火箭", Description: "<p>复仇者是蝉和系统家族非制导火箭的延续。这种制导导弹只能用于大型火箭发射系统，是捕获目标的真正恐怖。</p>"},
		"ballistics_artillery_bullet":   {Name: "大口径弹药", Description: "<p>标准化的大口径弹药，适用于动能和弹道武器，保证毁灭性伤害，但不能用于速射或极高精度的武器。</p>"},
		"ballistics_artillery_bullet_3": {Name: "大口径穿甲弹", Description: "<p></p>"},
		"ballistics_artillery_bullet_4": {Name: "大口径聚能弹", Description: "<p></p>"},
		"medium_missile_bullet":         {Name: "系统.A-2 - 中型导弹", Description: "<p>大规模和军事标准化的中等破坏力导弹。不能用于高维导弹系统武器。</p>"},
		"big_missile_bullet":            {Name: "系统.O-5 - 大型火箭", Description: "<p>大规模和军事标准化的高破坏力导弹。不能用于中等或更小的导弹武器。</p>"},
		"small_lens":                    {Name: "小型聚焦弹药", Description: "<p>标准化的小型和中型激光束冲击工具的弹药。</p>"},
		"small_lens_beam":               {Name: "小型光束弹药", Description: "<p></p>"},
		"small_missile_bullet":          {Name: "小型导弹", Description: "<p></p>"},
		"big_lens_1":                    {Name: "大型聚焦弹药", Description: "<p></p>"},
		"medium_lens_beam":              {Name: "中型光束弹药", Description: "<p></p>"},
	},
}
