package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var BaseDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"mining_installation_3": {ID: 22, Name: "Raitsin", Description: ""},
		"processing_plant_3":    {ID: 24, Name: "processing_plant_3", Description: ""},
		"base_17":               {ID: 32, Name: "Fattom", Description: ""},
		"base_Reverses":         {ID: -3, Name: "base_Reverses", Description: ""},
		"base_3":                {ID: 3, Name: "Proustav", Description: ""},
		"mining_installation_2": {ID: 13, Name: "Kia Lun", Description: ""},
		"mining_installation_4": {ID: 20, Name: "PlA-008", Description: ""},
		"Генератор “Гифебрации”": {ID: 25, Name: "Generator \"Hyfebration\"", Description: ""},
		"base_Replicas":      {ID: -1, Name: "base_Replicas", Description: ""},
		"base_9":             {ID: 9, Name: "Harves", Description: ""},
		"base_10":            {ID: 10, Name: "Esla", Description: ""},
		"base_11":            {ID: 11, Name: "Newt", Description: ""},
		"processing_plant_2": {ID: 15, Name: "Zunklet", Description: ""},
		"processing_plant_1": {ID: 17, Name: "Obkura", Description: ""},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Tracking station \"Veliri\"", Description: ""},
		"base_Explores":         {ID: -2, Name: "base_Explores", Description: ""},
		"base_6":                {ID: 6, Name: "Galileo", Description: ""},
		"prefabricated_plant_1": {ID: 16, Name: "GDC", Description: ""},
		"base_12":               {ID: 27, Name: "Armonica", Description: ""},
		"base_14":               {ID: 29, Name: "Shakpui", Description: ""},
		"base_20":               {ID: 35, Name: "Pasteur", Description: ""},
		"base_8":                {ID: 8, Name: "Copernicus", Description: ""},
		"Орудие “Гончкинс”":     {ID: 18, Name: "Gun \"Honchkins\"", Description: ""},
		"base_30":               {ID: 26, Name: "HB-dn", Description: ""},
		"processing_plant_4":    {ID: 45, Name: "Jardaro"},
		"base_1":                {ID: 1, Name: "Vernor", Description: ""},
		"base_4":                {ID: 4, Name: "Madu", Description: ""},
		"base_5":                {ID: 5, Name: "Icillin", Description: ""},
		"prefabricated_plant_3": {ID: 23, Name: "Arual", Description: ""},
		"base_13":               {ID: 28, Name: "Vespa", Description: ""},
		"base_15":               {ID: 30, Name: "Sagwood", Description: ""},
		"base_19":               {ID: 34, Name: "Varva", Description: ""},
		"prefabricated_plant_2": {ID: 19, Name: "Mervoor", Description: ""},
		"base_16":               {ID: 31, Name: "Ayvery", Description: ""},
		"base_18":               {ID: 33, Name: "Curie", Description: ""},
		"mining_installation_5": {ID: 46, Name: "mining_installation_5"},
		"prefabricated_plant_4": {ID: 47, Name: "prefabricated_plant_4"},
		"processing_plant_5":    {ID: 48, Name: "processing_plant_5"},
		"prefabricated_plant_5": {ID: 49, Name: "prefabricated_plant_5"},
		"mining_installation_6": {ID: 50, Name: "mining_installation_6"},
		"prefabricated_plant_6": {ID: 51, Name: "prefabricated_plant_6"},
		"processing_plant_6":    {ID: 52, Name: "processing_plant_6"},
		"mining_installation_7": {ID: 53, Name: "mining_installation_7"},
	},
	_const.RU: {
		"base_Reverses":         {ID: -3, Name: "base_Reverses"},
		"base_Explores":         {ID: -2, Name: "base_Explores"},
		"base_Replicas":         {ID: -1, Name: "base_Replicas"},
		"base_1":                {ID: 1, Name: "Вернор"},
		"base_3":                {ID: 3, Name: "Прустав"},
		"base_4":                {ID: 4, Name: "Маду"},
		"base_5":                {ID: 5, Name: "Ициллин"},
		"base_6":                {ID: 6, Name: "Галилей"},
		"base_8":                {ID: 8, Name: "Коперник"},
		"base_9":                {ID: 9, Name: "Харвс"},
		"base_10":               {ID: 10, Name: "Эсла"},
		"base_11":               {ID: 11, Name: "Ньют"},
		"mining_installation_2": {ID: 13, Name: "Киа-Лун"},
		"processing_plant_2":    {ID: 15, Name: "Цунклет"},
		"prefabricated_plant_1": {ID: 16, Name: "GDC"},
		"processing_plant_1":    {ID: 17, Name: "Обкура"},
		"Орудие “Гончкинс”":     {ID: 18, Name: "Орудие “Гончкинс”"},
		"prefabricated_plant_2": {ID: 19, Name: "Мервур"},
		"mining_installation_4": {ID: 20, Name: "PlA-008"},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Станция отслеживания “Велири”"},
		"mining_installation_3":  {ID: 22, Name: "Райцин"},
		"prefabricated_plant_3":  {ID: 23, Name: "Аруал"},
		"processing_plant_3":     {ID: 24, Name: "processing_plant_3"},
		"Генератор “Гифебрации”": {ID: 25, Name: "Генератор “Гифебрации”"},
		"base_30":               {ID: 26, Name: "HB-dn"},
		"base_12":               {ID: 27, Name: "Армоника"},
		"base_13":               {ID: 28, Name: "Веспа"},
		"base_14":               {ID: 29, Name: "Шакпуи"},
		"base_15":               {ID: 30, Name: "Сагвуд"},
		"base_16":               {ID: 31, Name: "Ейвери"},
		"base_17":               {ID: 32, Name: "Фаттом"},
		"base_18":               {ID: 33, Name: "Кюри"},
		"base_19":               {ID: 34, Name: "Варва"},
		"base_20":               {ID: 35, Name: "Пастер"},
		"processing_plant_4":    {ID: 45, Name: "Жардаро"},
		"mining_installation_5": {ID: 46, Name: "mining_installation_5"},
		"prefabricated_plant_4": {ID: 47, Name: "prefabricated_plant_4"},
		"processing_plant_5":    {ID: 48, Name: "processing_plant_5"},
		"prefabricated_plant_5": {ID: 49, Name: "prefabricated_plant_5"},
		"mining_installation_6": {ID: 50, Name: "mining_installation_6"},
		"prefabricated_plant_6": {ID: 51, Name: "prefabricated_plant_6"},
		"processing_plant_6":    {ID: 52, Name: "processing_plant_6"},
		"mining_installation_7": {ID: 53, Name: "mining_installation_7"},
	},
}
