package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var BaseDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"mining_installation_3": {ID: 22, Name: "Raitsin", Description: ""},
		"processing_plant_3":    {ID: 24, Name: "Vultaris", Description: ""},
		"base_17":               {ID: 32, Name: "Fattom", Description: ""},
		"base_Reverses":         {ID: -3, Name: "base_Reverses", Description: ""},
		"base_3":                {ID: 3, Name: "Proustav", Description: ""},
		"mining_installation_2": {ID: 13, Name: "Kia Lun", Description: ""},
		"mining_installation_4": {ID: 20, Name: "PlA-008", Description: ""},
		"Генератор “Гифебрации”": {ID: 25, Name: "Generator \"Hyfebration\"", Description: ""},
		"base_Replicas":      {ID: -1, Name: "base_Replicas", Description: ""},
		"base_9":             {ID: 9, Name: "Harves", Description: ""},
		"base_10":            {ID: 10, Name: "Esla", Description: ""},
		"base_11":            {ID: 11, Name: "Newt", Description: ""},
		"processing_plant_2": {ID: 15, Name: "Zunklet", Description: ""},
		"processing_plant_1": {ID: 17, Name: "Obkura", Description: ""},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Tracking station \"Veliri\"", Description: ""},
		"base_Explores":                  {ID: -2, Name: "base_Explores", Description: ""},
		"base_6":                         {ID: 6, Name: "Galileo", Description: ""},
		"prefabricated_plant_1":          {ID: 16, Name: "GDC", Description: ""},
		"base_12":                        {ID: 27, Name: "Armonica", Description: ""},
		"base_14":                        {ID: 29, Name: "Shakpui", Description: ""},
		"base_20":                        {ID: 35, Name: "Pasteur", Description: ""},
		"base_8":                         {ID: 8, Name: "Copernicus", Description: ""},
		"Орудие “Гончкинс”":              {ID: 18, Name: "Gun \"Honchkins\"", Description: ""},
		"base_30":                        {ID: 26, Name: "HB-dn", Description: ""},
		"processing_plant_4":             {ID: 45, Name: "Jardaro"},
		"base_1":                         {ID: 1, Name: "Vernor", Description: ""},
		"base_4":                         {ID: 4, Name: "Madu", Description: ""},
		"base_5":                         {ID: 5, Name: "Icillin", Description: ""},
		"prefabricated_plant_3":          {ID: 23, Name: "Arual", Description: ""},
		"base_13":                        {ID: 28, Name: "Vespa", Description: ""},
		"base_15":                        {ID: 30, Name: "Sagwood", Description: ""},
		"base_19":                        {ID: 34, Name: "Varva", Description: ""},
		"prefabricated_plant_2":          {ID: 19, Name: "Mervoor", Description: ""},
		"base_16":                        {ID: 31, Name: "Ayvery", Description: ""},
		"base_18":                        {ID: 33, Name: "Curie", Description: ""},
		"mining_installation_5":          {ID: 46, Name: "Quartz"},
		"prefabricated_plant_4":          {ID: 47, Name: "Module"},
		"processing_plant_5":             {ID: 48, Name: "Forge"},
		"prefabricated_plant_5":          {ID: 49, Name: "Assembler"},
		"mining_installation_6":          {ID: 50, Name: "Onyx"},
		"prefabricated_plant_6":          {ID: 51, Name: "Konstruct"},
		"processing_plant_6":             {ID: 52, Name: "Splav"},
		"mining_installation_7":          {ID: 53, Name: "Granit"},
		"Replic_4":                       {ID: 96, Name: "Tyrant"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Refine"},
		"Replic_5":                       {ID: 98, Name: "Goliath"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Magma"},
		"Replic_6":                       {ID: 100, Name: "Avalanche"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Fabrika"},
		"Reverses_4":                     {ID: 102, Name: "Nexus"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Sintez"},
		"Reverses_5":                     {ID: 104, Name: "Xenon"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Ruda-X"},
		"Reverses_6":                     {ID: 106, Name: "Omega"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Block-7"},
		"Explores_4":                     {ID: 102, Name: "Erida"},
		"Explores_processing_plant_4":    {ID: 103, Name: "Metallurg"},
		"Explores_5":                     {ID: 104, Name: "Lyra"},
		"Explores_mining_installation_5": {ID: 105, Name: "Shahta"},
		"Explores_6":                     {ID: 106, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 107, Name: "Inzhener"},
	},
	_const.RU: {
		"base_Reverses":         {ID: -3, Name: "base_Reverses"},
		"base_Explores":         {ID: -2, Name: "base_Explores"},
		"base_Replicas":         {ID: -1, Name: "base_Replicas"},
		"base_1":                {ID: 1, Name: "Вернор"},
		"base_3":                {ID: 3, Name: "Прустав"},
		"base_4":                {ID: 4, Name: "Маду"},
		"base_5":                {ID: 5, Name: "Ициллин"},
		"base_6":                {ID: 6, Name: "Галилей"},
		"base_8":                {ID: 8, Name: "Коперник"},
		"base_9":                {ID: 9, Name: "Харвс"},
		"base_10":               {ID: 10, Name: "Эсла"},
		"base_11":               {ID: 11, Name: "Ньют"},
		"mining_installation_2": {ID: 13, Name: "Киа-Лун"},
		"processing_plant_2":    {ID: 15, Name: "Цунклет"},
		"prefabricated_plant_1": {ID: 16, Name: "GDC"},
		"processing_plant_1":    {ID: 17, Name: "Обкура"},
		"Орудие “Гончкинс”":     {ID: 18, Name: "Орудие “Гончкинс”"},
		"prefabricated_plant_2": {ID: 19, Name: "Мервур"},
		"mining_installation_4": {ID: 20, Name: "PlA-008"},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Станция отслеживания “Велири”"},
		"mining_installation_3":  {ID: 22, Name: "Райцин"},
		"prefabricated_plant_3":  {ID: 23, Name: "Аруал"},
		"processing_plant_3":     {ID: 24, Name: "Вултарис"},
		"Генератор “Гифебрации”": {ID: 25, Name: "Генератор “Гифебрации”"},
		"base_30":                        {ID: 26, Name: "HB-dn"},
		"base_12":                        {ID: 27, Name: "Армоника"},
		"base_13":                        {ID: 28, Name: "Веспа"},
		"base_14":                        {ID: 29, Name: "Шакпуи"},
		"base_15":                        {ID: 30, Name: "Сагвуд"},
		"base_16":                        {ID: 31, Name: "Ейвери"},
		"base_17":                        {ID: 32, Name: "Фаттом"},
		"base_18":                        {ID: 33, Name: "Кюри"},
		"base_19":                        {ID: 34, Name: "Варва"},
		"base_20":                        {ID: 35, Name: "Пастер"},
		"processing_plant_4":             {ID: 45, Name: "Жардаро"},
		"mining_installation_5":          {ID: 46, Name: "Кварц"},
		"prefabricated_plant_4":          {ID: 47, Name: "Модуль"},
		"processing_plant_5":             {ID: 48, Name: "Форж"},
		"prefabricated_plant_5":          {ID: 49, Name: "Ассемблер"},
		"mining_installation_6":          {ID: 50, Name: "Оникс-12"},
		"prefabricated_plant_6":          {ID: 51, Name: "Конструкт"},
		"processing_plant_6":             {ID: 52, Name: "Сплав"},
		"mining_installation_7":          {ID: 53, Name: "Гранит"},
		"Replic_4":                       {ID: 96, Name: "Тирант"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Рефайн"},
		"Replic_5":                       {ID: 98, Name: "Голиаф"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Магма"},
		"Replic_6":                       {ID: 100, Name: "Аваланч"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Фабрика"},
		"Reverses_4":                     {ID: 102, Name: "Нексус"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Синтез"},
		"Reverses_5":                     {ID: 104, Name: "Ксенон"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Руда-Х"},
		"Reverses_6":                     {ID: 106, Name: "Омега"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Блок-7"},
		"Explores_4":                     {ID: 102, Name: "Эрида"},
		"Explores_processing_plant_4":    {ID: 103, Name: "Металлург"},
		"Explores_5":                     {ID: 104, Name: "Лира"},
		"Explores_mining_installation_5": {ID: 105, Name: "Шахта"},
		"Explores_6":                     {ID: 106, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 107, Name: "Инженер"},
	},
	_const.ZhCN: {
		"mining_installation_3": {ID: 22, Name: "Raitsin", Description: ""},
		"processing_plant_3":    {ID: 24, Name: "Vultaris", Description: ""},
		"base_17":               {ID: 32, Name: "Fattom", Description: ""},
		"base_Reverses":         {ID: -3, Name: "base_Reverses", Description: ""},
		"base_3":                {ID: 3, Name: "Proustav", Description: ""},
		"mining_installation_2": {ID: 13, Name: "Kia Lun", Description: ""},
		"mining_installation_4": {ID: 20, Name: "PlA-008", Description: ""},
		"Генератор “Гифебрации”": {ID: 25, Name: "Generator \"Hyfebration\"", Description: ""},
		"base_Replicas":      {ID: -1, Name: "base_Replicas", Description: ""},
		"base_9":             {ID: 9, Name: "Harves", Description: ""},
		"base_10":            {ID: 10, Name: "Esla", Description: ""},
		"base_11":            {ID: 11, Name: "Newt", Description: ""},
		"processing_plant_2": {ID: 15, Name: "Zunklet", Description: ""},
		"processing_plant_1": {ID: 17, Name: "Obkura", Description: ""},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Tracking station \"Veliri\"", Description: ""},
		"base_Explores":                  {ID: -2, Name: "base_Explores", Description: ""},
		"base_6":                         {ID: 6, Name: "Galileo", Description: ""},
		"prefabricated_plant_1":          {ID: 16, Name: "GDC", Description: ""},
		"base_12":                        {ID: 27, Name: "Armonica", Description: ""},
		"base_14":                        {ID: 29, Name: "Shakpui", Description: ""},
		"base_20":                        {ID: 35, Name: "Pasteur", Description: ""},
		"base_8":                         {ID: 8, Name: "Copernicus", Description: ""},
		"Орудие “Гончкинс”":              {ID: 18, Name: "Gun \"Honchkins\"", Description: ""},
		"base_30":                        {ID: 26, Name: "HB-dn", Description: ""},
		"processing_plant_4":             {ID: 45, Name: "Jardaro"},
		"base_1":                         {ID: 1, Name: "Vernor", Description: ""},
		"base_4":                         {ID: 4, Name: "Madu", Description: ""},
		"base_5":                         {ID: 5, Name: "Icillin", Description: ""},
		"prefabricated_plant_3":          {ID: 23, Name: "Arual", Description: ""},
		"base_13":                        {ID: 28, Name: "Vespa", Description: ""},
		"base_15":                        {ID: 30, Name: "Sagwood", Description: ""},
		"base_19":                        {ID: 34, Name: "Varva", Description: ""},
		"prefabricated_plant_2":          {ID: 19, Name: "Mervoor", Description: ""},
		"base_16":                        {ID: 31, Name: "Ayvery", Description: ""},
		"base_18":                        {ID: 33, Name: "Curie", Description: ""},
		"mining_installation_5":          {ID: 46, Name: "Quartz"},
		"prefabricated_plant_4":          {ID: 47, Name: "Module"},
		"processing_plant_5":             {ID: 48, Name: "Forge"},
		"prefabricated_plant_5":          {ID: 49, Name: "Assembler"},
		"mining_installation_6":          {ID: 50, Name: "Onyx"},
		"prefabricated_plant_6":          {ID: 51, Name: "Konstruct"},
		"processing_plant_6":             {ID: 52, Name: "Splav"},
		"mining_installation_7":          {ID: 53, Name: "Granit"},
		"Replic_4":                       {ID: 96, Name: "Tyrant"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Refine"},
		"Replic_5":                       {ID: 98, Name: "Goliath"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Magma"},
		"Replic_6":                       {ID: 100, Name: "Avalanche"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Fabrika"},
		"Reverses_4":                     {ID: 102, Name: "Nexus"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Sintez"},
		"Reverses_5":                     {ID: 104, Name: "Xenon"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Ruda-X"},
		"Reverses_6":                     {ID: 106, Name: "Omega"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Block-7"},
		"Explores_4":                     {ID: 102, Name: "Erida"},
		"Explores_processing_plant_4":    {ID: 103, Name: "Metallurg"},
		"Explores_5":                     {ID: 104, Name: "Lyra"},
		"Explores_mining_installation_5": {ID: 105, Name: "Shahta"},
		"Explores_6":                     {ID: 106, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 107, Name: "Inzhener"},
	},
}
