package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var BaseDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"mining_installation_3": {ID: 22, Name: "Raitsin", Description: ""},
		"processing_plant_3":    {ID: 24, Name: "Vultaris", Description: ""},
		"base_17":               {ID: 32, Name: "Fattom", Description: ""},
		"base_Reverses":         {ID: -3, Name: "base_Reverses", Description: ""},
		"base_3":                {ID: 3, Name: "Proustav", Description: ""},
		"mining_installation_2": {ID: 13, Name: "Kia Lun", Description: ""},
		"mining_installation_4": {ID: 20, Name: "PlA-008", Description: ""},
		"Генератор “Гифебрации”": {ID: 25, Name: "Generator \"Hyfebration\"", Description: ""},
		"base_Replicas":      {ID: -1, Name: "base_Replicas", Description: ""},
		"base_9":             {ID: 9, Name: "Harves", Description: ""},
		"base_10":            {ID: 10, Name: "Esla", Description: ""},
		"base_11":            {ID: 11, Name: "Newt", Description: ""},
		"processing_plant_2": {ID: 15, Name: "Zunklet", Description: ""},
		"processing_plant_1": {ID: 17, Name: "Obkura", Description: ""},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Tracking station \"Veliri\"", Description: ""},
		"base_Explores":                  {ID: -2, Name: "base_Explores", Description: ""},
		"base_6":                         {ID: 6, Name: "Galileo", Description: ""},
		"prefabricated_plant_1":          {ID: 16, Name: "GDC", Description: ""},
		"base_12":                        {ID: 27, Name: "Armonica", Description: ""},
		"base_14":                        {ID: 29, Name: "Shakpui", Description: ""},
		"base_20":                        {ID: 35, Name: "Pasteur", Description: ""},
		"base_8":                         {ID: 8, Name: "Copernicus", Description: ""},
		"Орудие “Гончкинс”":              {ID: 18, Name: "Gun \"Honchkins\"", Description: ""},
		"base_30":                        {ID: 26, Name: "HB-dn", Description: ""},
		"processing_plant_4":             {ID: 45, Name: "Jardaro"},
		"base_1":                         {ID: 1, Name: "Vernor", Description: ""},
		"base_4":                         {ID: 4, Name: "Madu", Description: ""},
		"base_5":                         {ID: 5, Name: "Icillin", Description: ""},
		"prefabricated_plant_3":          {ID: 23, Name: "Arual", Description: ""},
		"base_13":                        {ID: 28, Name: "Vespa", Description: ""},
		"base_15":                        {ID: 30, Name: "Sagwood", Description: ""},
		"base_19":                        {ID: 34, Name: "Varva", Description: ""},
		"prefabricated_plant_2":          {ID: 19, Name: "Mervoor", Description: ""},
		"base_16":                        {ID: 31, Name: "Ayvery", Description: ""},
		"base_18":                        {ID: 33, Name: "Curie", Description: ""},
		"mining_installation_5":          {ID: 46, Name: "Quartz"},
		"prefabricated_plant_4":          {ID: 47, Name: "Module"},
		"processing_plant_5":             {ID: 48, Name: "Forge"},
		"prefabricated_plant_5":          {ID: 49, Name: "Assembler"},
		"mining_installation_6":          {ID: 50, Name: "Onyx"},
		"prefabricated_plant_6":          {ID: 51, Name: "Konstruct"},
		"processing_plant_6":             {ID: 52, Name: "Splav"},
		"mining_installation_7":          {ID: 53, Name: "Granit"},
		"Replic_4":                       {ID: 96, Name: "Tyrant"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Refine"},
		"Replic_5":                       {ID: 98, Name: "Goliath"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Magma"},
		"Replic_6":                       {ID: 100, Name: "Avalanche"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Fabrika"},
		"Reverses_4":                     {ID: 102, Name: "Nexus"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Sintez"},
		"Reverses_5":                     {ID: 104, Name: "Xenon"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Ruda-X"},
		"Reverses_6":                     {ID: 106, Name: "Omega"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Block-7"},
		"Explores_4":                     {ID: 108, Name: "Erida"},
		"Explores_processing_plant_4":    {ID: 109, Name: "Metallurg"},
		"Explores_5":                     {ID: 110, Name: "Lyra"},
		"Explores_mining_installation_5": {ID: 111, Name: "Shahta"},
		"Explores_6":                     {ID: 112, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 113, Name: "Inzhener"},
		"Rustbucket_1":                   {ID: 117, Name: "Junkhole"},
		"Rustbucket_2":                   {ID: 118, Name: "GlitchGate"},
		"Rustbucket_3":                   {ID: 119, Name: "DevNull"},
		// базы войны (type war): war_<ид точки захвата>, ID - ид базы в game.base
		"war_31": {ID: 154, Name: "Outpost Frontier"},
		"war_32": {ID: 153, Name: "Outpost Bastion"},
		"war_33": {ID: 155, Name: "Outpost Shield"},
		"war_34": {ID: 162, Name: "Outpost Blade"},
		"war_35": {ID: 164, Name: "Outpost Granite"},
		"war_36": {ID: 163, Name: "Outpost Dawn"},
		"war_37": {ID: 157, Name: "Outpost Storm"},
		"war_38": {ID: 158, Name: "Outpost Citadel"},
		"war_39": {ID: 156, Name: "Outpost Barrier"},
		"war_40": {ID: 160, Name: "Outpost Cliff"},
		"war_41": {ID: 161, Name: "Outpost Flint"},
		"war_42": {ID: 159, Name: "Outpost Harpoon"},
		"war_43": {ID: 152, Name: "Outpost Beacon"},
		"war_44": {ID: 150, Name: "Outpost Sentinel"},
		"war_45": {ID: 151, Name: "Outpost Ram"},
		"war_46": {ID: 147, Name: "Outpost Bulwark"},
		"war_47": {ID: 149, Name: "Outpost Falcon"},
		"war_48": {ID: 148, Name: "Outpost Cordon"},
		"war_49": {ID: 145, Name: "Outpost Flame"},
		"war_50": {ID: 144, Name: "Outpost Thunder"},
		"war_51": {ID: 146, Name: "Outpost Hawk"},
		"war_52": {ID: 143, Name: "Outpost Wave"},
		"war_53": {ID: 142, Name: "Outpost Cascade"},
		"war_54": {ID: 141, Name: "Outpost Obelisk"},
		"war_55": {ID: 165, Name: "Outpost Summit"},
		"war_56": {ID: 166, Name: "Outpost Bolt"},
		"war_57": {ID: 167, Name: "Outpost Sunrise"},
	},
	_const.RU: {
		"base_Reverses":         {ID: -3, Name: "base_Reverses"},
		"base_Explores":         {ID: -2, Name: "base_Explores"},
		"base_Replicas":         {ID: -1, Name: "base_Replicas"},
		"base_1":                {ID: 1, Name: "Вернор"},
		"base_3":                {ID: 3, Name: "Прустав"},
		"base_4":                {ID: 4, Name: "Маду"},
		"base_5":                {ID: 5, Name: "Ициллин"},
		"base_6":                {ID: 6, Name: "Галилей"},
		"base_8":                {ID: 8, Name: "Коперник"},
		"base_9":                {ID: 9, Name: "Харвс"},
		"base_10":               {ID: 10, Name: "Эсла"},
		"base_11":               {ID: 11, Name: "Ньют"},
		"mining_installation_2": {ID: 13, Name: "Киа-Лун"},
		"processing_plant_2":    {ID: 15, Name: "Цунклет"},
		"prefabricated_plant_1": {ID: 16, Name: "GDC"},
		"processing_plant_1":    {ID: 17, Name: "Обкура"},
		"Орудие “Гончкинс”":     {ID: 18, Name: "Орудие “Гончкинс”"},
		"prefabricated_plant_2": {ID: 19, Name: "Мервур"},
		"mining_installation_4": {ID: 20, Name: "PlA-008"},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Станция отслеживания “Велири”"},
		"mining_installation_3":  {ID: 22, Name: "Райцин"},
		"prefabricated_plant_3":  {ID: 23, Name: "Аруал"},
		"processing_plant_3":     {ID: 24, Name: "Вултарис"},
		"Генератор “Гифебрации”": {ID: 25, Name: "Генератор “Гифебрации”"},
		"base_30":                        {ID: 26, Name: "HB-dn"},
		"base_12":                        {ID: 27, Name: "Армоника"},
		"base_13":                        {ID: 28, Name: "Веспа"},
		"base_14":                        {ID: 29, Name: "Шакпуи"},
		"base_15":                        {ID: 30, Name: "Сагвуд"},
		"base_16":                        {ID: 31, Name: "Ейвери"},
		"base_17":                        {ID: 32, Name: "Фаттом"},
		"base_18":                        {ID: 33, Name: "Кюри"},
		"base_19":                        {ID: 34, Name: "Варва"},
		"base_20":                        {ID: 35, Name: "Пастер"},
		"processing_plant_4":             {ID: 45, Name: "Жардаро"},
		"mining_installation_5":          {ID: 46, Name: "Кварц"},
		"prefabricated_plant_4":          {ID: 47, Name: "Модуль"},
		"processing_plant_5":             {ID: 48, Name: "Форж"},
		"prefabricated_plant_5":          {ID: 49, Name: "Ассемблер"},
		"mining_installation_6":          {ID: 50, Name: "Оникс-12"},
		"prefabricated_plant_6":          {ID: 51, Name: "Конструкт"},
		"processing_plant_6":             {ID: 52, Name: "Сплав"},
		"mining_installation_7":          {ID: 53, Name: "Гранит"},
		"Replic_4":                       {ID: 96, Name: "Тирант"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Рефайн"},
		"Replic_5":                       {ID: 98, Name: "Голиаф"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Магма"},
		"Replic_6":                       {ID: 100, Name: "Аваланч"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Фабрика"},
		"Reverses_4":                     {ID: 102, Name: "Нексус"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Синтез"},
		"Reverses_5":                     {ID: 104, Name: "Ксенон"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Руда-Х"},
		"Reverses_6":                     {ID: 106, Name: "Омега"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Блок-7"},
		"Explores_4":                     {ID: 108, Name: "Эрида"},
		"Explores_processing_plant_4":    {ID: 109, Name: "Металлург"},
		"Explores_5":                     {ID: 110, Name: "Лира"},
		"Explores_mining_installation_5": {ID: 111, Name: "Шахта"},
		"Explores_6":                     {ID: 112, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 113, Name: "Инженер"},
		"Rustbucket_1":                   {ID: 117, Name: "Junkhole"},
		"Rustbucket_2":                   {ID: 118, Name: "GlitchGate"},
		"Rustbucket_3":                   {ID: 119, Name: "DevNull"},
		// базы войны (type war): war_<ид точки захвата>, ID - ид базы в game.base
		"war_31": {ID: 154, Name: "Аванпост «Рубеж»"},
		"war_32": {ID: 153, Name: "Аванпост «Бастион»"},
		"war_33": {ID: 155, Name: "Аванпост «Щит»"},
		"war_34": {ID: 162, Name: "Аванпост «Клинок»"},
		"war_35": {ID: 164, Name: "Аванпост «Гранит»"},
		"war_36": {ID: 163, Name: "Аванпост «Заря»"},
		"war_37": {ID: 157, Name: "Аванпост «Шторм»"},
		"war_38": {ID: 158, Name: "Аванпост «Цитадель»"},
		"war_39": {ID: 156, Name: "Аванпост «Барьер»"},
		"war_40": {ID: 160, Name: "Аванпост «Утёс»"},
		"war_41": {ID: 161, Name: "Аванпост «Кремень»"},
		"war_42": {ID: 159, Name: "Аванпост «Гарпун»"},
		"war_43": {ID: 152, Name: "Аванпост «Маяк»"},
		"war_44": {ID: 150, Name: "Аванпост «Страж»"},
		"war_45": {ID: 151, Name: "Аванпост «Таран»"},
		"war_46": {ID: 147, Name: "Аванпост «Оплот»"},
		"war_47": {ID: 149, Name: "Аванпост «Сокол»"},
		"war_48": {ID: 148, Name: "Аванпост «Кордон»"},
		"war_49": {ID: 145, Name: "Аванпост «Пламя»"},
		"war_50": {ID: 144, Name: "Аванпост «Гроза»"},
		"war_51": {ID: 146, Name: "Аванпост «Ястреб»"},
		"war_52": {ID: 143, Name: "Аванпост «Волна»"},
		"war_53": {ID: 142, Name: "Аванпост «Каскад»"},
		"war_54": {ID: 141, Name: "Аванпост «Обелиск»"},
		"war_55": {ID: 165, Name: "Аванпост «Вершина»"},
		"war_56": {ID: 166, Name: "Аванпост «Затвор»"},
		"war_57": {ID: 167, Name: "Аванпост «Рассвет»"},
	},
	_const.ZhCN: {
		"mining_installation_3": {ID: 22, Name: "Raitsin", Description: ""},
		"processing_plant_3":    {ID: 24, Name: "Vultaris", Description: ""},
		"base_17":               {ID: 32, Name: "Fattom", Description: ""},
		"base_Reverses":         {ID: -3, Name: "base_Reverses", Description: ""},
		"base_3":                {ID: 3, Name: "Proustav", Description: ""},
		"mining_installation_2": {ID: 13, Name: "Kia Lun", Description: ""},
		"mining_installation_4": {ID: 20, Name: "PlA-008", Description: ""},
		"Генератор “Гифебрации”": {ID: 25, Name: "Generator \"Hyfebration\"", Description: ""},
		"base_Replicas":      {ID: -1, Name: "base_Replicas", Description: ""},
		"base_9":             {ID: 9, Name: "Harves", Description: ""},
		"base_10":            {ID: 10, Name: "Esla", Description: ""},
		"base_11":            {ID: 11, Name: "Newt", Description: ""},
		"processing_plant_2": {ID: 15, Name: "Zunklet", Description: ""},
		"processing_plant_1": {ID: 17, Name: "Obkura", Description: ""},
		"Станция отслеживания “Велири”": {ID: 21, Name: "Tracking station \"Veliri\"", Description: ""},
		"base_Explores":                  {ID: -2, Name: "base_Explores", Description: ""},
		"base_6":                         {ID: 6, Name: "Galileo", Description: ""},
		"prefabricated_plant_1":          {ID: 16, Name: "GDC", Description: ""},
		"base_12":                        {ID: 27, Name: "Armonica", Description: ""},
		"base_14":                        {ID: 29, Name: "Shakpui", Description: ""},
		"base_20":                        {ID: 35, Name: "Pasteur", Description: ""},
		"base_8":                         {ID: 8, Name: "Copernicus", Description: ""},
		"Орудие “Гончкинс”":              {ID: 18, Name: "Gun \"Honchkins\"", Description: ""},
		"base_30":                        {ID: 26, Name: "HB-dn", Description: ""},
		"processing_plant_4":             {ID: 45, Name: "Jardaro"},
		"base_1":                         {ID: 1, Name: "Vernor", Description: ""},
		"base_4":                         {ID: 4, Name: "Madu", Description: ""},
		"base_5":                         {ID: 5, Name: "Icillin", Description: ""},
		"prefabricated_plant_3":          {ID: 23, Name: "Arual", Description: ""},
		"base_13":                        {ID: 28, Name: "Vespa", Description: ""},
		"base_15":                        {ID: 30, Name: "Sagwood", Description: ""},
		"base_19":                        {ID: 34, Name: "Varva", Description: ""},
		"prefabricated_plant_2":          {ID: 19, Name: "Mervoor", Description: ""},
		"base_16":                        {ID: 31, Name: "Ayvery", Description: ""},
		"base_18":                        {ID: 33, Name: "Curie", Description: ""},
		"mining_installation_5":          {ID: 46, Name: "Quartz"},
		"prefabricated_plant_4":          {ID: 47, Name: "Module"},
		"processing_plant_5":             {ID: 48, Name: "Forge"},
		"prefabricated_plant_5":          {ID: 49, Name: "Assembler"},
		"mining_installation_6":          {ID: 50, Name: "Onyx"},
		"prefabricated_plant_6":          {ID: 51, Name: "Konstruct"},
		"processing_plant_6":             {ID: 52, Name: "Splav"},
		"mining_installation_7":          {ID: 53, Name: "Granit"},
		"Replic_4":                       {ID: 96, Name: "Tyrant"},
		"Replic_processing_plant_4":      {ID: 97, Name: "Refine"},
		"Replic_5":                       {ID: 98, Name: "Goliath"},
		"Replic_mining_installation_5":   {ID: 99, Name: "Magma"},
		"Replic_6":                       {ID: 100, Name: "Avalanche"},
		"Replic_prefabricated_plant_6":   {ID: 101, Name: "Fabrika"},
		"Reverses_4":                     {ID: 102, Name: "Nexus"},
		"Reverses_processing_plant_4":    {ID: 103, Name: "Sintez"},
		"Reverses_5":                     {ID: 104, Name: "Xenon"},
		"Reverses_mining_installation_5": {ID: 105, Name: "Ruda-X"},
		"Reverses_6":                     {ID: 106, Name: "Omega"},
		"Reverses_prefabricated_plant_6": {ID: 107, Name: "Block-7"},
		"Explores_4":                     {ID: 108, Name: "Erida"},
		"Explores_processing_plant_4":    {ID: 109, Name: "Metallurg"},
		"Explores_5":                     {ID: 110, Name: "Lyra"},
		"Explores_mining_installation_5": {ID: 111, Name: "Shahta"},
		"Explores_6":                     {ID: 112, Name: "Атлас"},
		"Explores_prefabricated_plant_6": {ID: 113, Name: "Inzhener"},
		"Rustbucket_1":                   {ID: 117, Name: "Junkhole"},
		"Rustbucket_2":                   {ID: 118, Name: "GlitchGate"},
		"Rustbucket_3":                   {ID: 119, Name: "DevNull"},
		// базы войны (type war): war_<ид точки захвата>, ID - ид базы в game.base
		"war_31": {ID: 154, Name: "前哨站「边境」"},
		"war_32": {ID: 153, Name: "前哨站「堡垒」"},
		"war_33": {ID: 155, Name: "前哨站「盾」"},
		"war_34": {ID: 162, Name: "前哨站「利刃」"},
		"war_35": {ID: 164, Name: "前哨站「花岗岩」"},
		"war_36": {ID: 163, Name: "前哨站「黎明」"},
		"war_37": {ID: 157, Name: "前哨站「风暴」"},
		"war_38": {ID: 158, Name: "前哨站「要塞」"},
		"war_39": {ID: 156, Name: "前哨站「屏障」"},
		"war_40": {ID: 160, Name: "前哨站「峭壁」"},
		"war_41": {ID: 161, Name: "前哨站「燧石」"},
		"war_42": {ID: 159, Name: "前哨站「鱼叉」"},
		"war_43": {ID: 152, Name: "前哨站「灯塔」"},
		"war_44": {ID: 150, Name: "前哨站「哨兵」"},
		"war_45": {ID: 151, Name: "前哨站「撞角」"},
		"war_46": {ID: 147, Name: "前哨站「壁垒」"},
		"war_47": {ID: 149, Name: "前哨站「猎鹰」"},
		"war_48": {ID: 148, Name: "前哨站「警戒线」"},
		"war_49": {ID: 145, Name: "前哨站「烈焰」"},
		"war_50": {ID: 144, Name: "前哨站「雷霆」"},
		"war_51": {ID: 146, Name: "前哨站「苍鹰」"},
		"war_52": {ID: 143, Name: "前哨站「浪潮」"},
		"war_53": {ID: 142, Name: "前哨站「瀑布」"},
		"war_54": {ID: 141, Name: "前哨站「方尖碑」"},
		"war_55": {ID: 165, Name: "前哨站「山巅」"},
		"war_56": {ID: 166, Name: "前哨站「枪栓」"},
		"war_57": {ID: 167, Name: "前哨站「旭日」"},
	},
}
