package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var BookDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"default":          {Name: "Skill chip: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Standard behavioral pattern firmware module. Contains basic learning algorithms embedded in the subconscious. Does not require adaptation—the synth's consciousness accepts it as a part of itself, like a memory that was always there.</p><p>Any skill chip can be converted into raw experience energy. However, this requires serious infrastructure—and such operations are considered illegal.</p>"},
		"default_Replics":  {Name: "Skill chip: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Standard behavioral pattern firmware module. Contains basic learning algorithms embedded in the subconscious. Does not require adaptation—the synth's consciousness accepts it as a part of itself, like a memory that was always there.</p><p>Any skill chip can be converted into raw experience energy. However, this requires serious infrastructure—and such operations are considered illegal.</p>"},
		"default_Explores": {Name: "Skill chip: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Standard behavioral pattern firmware module. Contains basic learning algorithms embedded in the subconscious. Does not require adaptation—the synth's consciousness accepts it as a part of itself, like a memory that was always there.</p><p>Any skill chip can be converted into raw experience energy. However, this requires serious infrastructure—and such operations are considered illegal.</p>"},
		"default_Reverses": {Name: "Skill chip: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Standard behavioral pattern firmware module. Contains basic learning algorithms embedded in the subconscious. Does not require adaptation—the synth's consciousness accepts it as a part of itself, like a memory that was always there.</p><p>Any skill chip can be converted into raw experience energy. However, this requires serious infrastructure—and such operations are considered illegal.</p>"},
	},
	_const.RU: {
		"default":          {Name: "Чип навыка: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Стандартный модуль перепрошивки поведенческих паттернов. Содержит базовые алгоритмы учения, вшитые в подсознание. Не требует адаптации — сознание синтета принимает его как часть себя, словно воспоминание, которое всегда было там.</p><p>Любой чип можно превратить в сырую энергию опыта. Но для этого требуется серьёзная инфраструктура — и подобные операции считаются незаконными.</p>"},
		"default_Replics":  {Name: "Чип навыка: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Стандартный модуль перепрошивки поведенческих паттернов. Содержит базовые алгоритмы учения, вшитые в подсознание. Не требует адаптации — сознание синтета принимает его как часть себя, словно воспоминание, которое всегда было там.</p><p>Любой чип можно превратить в сырую энергию опыта. Но для этого требуется серьёзная инфраструктура — и подобные операции считаются незаконными.</p>"},
		"default_Explores": {Name: "Чип навыка: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Стандартный модуль перепрошивки поведенческих паттернов. Содержит базовые алгоритмы учения, вшитые в подсознание. Не требует адаптации — сознание синтета принимает его как часть себя, словно воспоминание, которое всегда было там.</p><p>Любой чип можно превратить в сырую энергию опыта. Но для этого требуется серьёзная инфраструктура — и подобные операции считаются незаконными.</p>"},
		"default_Reverses": {Name: "Чип навыка: <span class=\"importantly\">%skill_name%</span>", Description: "<p>Стандартный модуль перепрошивки поведенческих паттернов. Содержит базовые алгоритмы учения, вшитые в подсознание. Не требует адаптации — сознание синтета принимает его как часть себя, словно воспоминание, которое всегда было там.</p><p>Любой чип можно превратить в сырую энергию опыта. Но для этого требуется серьёзная инфраструктура — и подобные операции считаются незаконными.</p>"},
	},
	_const.ZhCN: {
		"default":          {Name: "技能芯片：<span class=\"importantly\">%skill_name%</span>", Description: "<p>标准行为模式重写模块。 包含嵌入潜意识的基础学习算法。无需适应——合成体的意识会将其视为自身的一部分，如同一直存在的记忆。</p><p>任何技能芯片都能转化为原始经验能量。 但这需要庞大的基础设施——此类操作被视为非法。</p>"},
		"default_Replics":  {Name: "技能芯片：<span class=\"importantly\">%skill_name%</span>", Description: "<p>标准行为模式重写模块。 包含嵌入潜意识的基础学习算法。无需适应——合成体的意识会将其视为自身的一部分，如同一直存在的记忆。</p><p>任何技能芯片都能转化为原始经验能量。 但这需要庞大的基础设施——此类操作被视为非法。</p>"},
		"default_Explores": {Name: "技能芯片：<span class=\"importantly\">%skill_name%</span>", Description: "<p>标准行为模式重写模块。 包含嵌入潜意识的基础学习算法。无需适应——合成体的意识会将其视为自身的一部分，如同一直存在的记忆。</p><p>任何技能芯片都能转化为原始经验能量。 但这需要庞大的基础设施——此类操作被视为非法。</p>"},
		"default_Reverses": {Name: "技能芯片：<span class=\"importantly\">%skill_name%</span>", Description: "<p>标准行为模式重写模块。 包含嵌入潜意识的基础学习算法。无需适应——合成体的意识会将其视为自身的一部分，如同一直存在的记忆。</p><p>任何技能芯片都能转化为原始经验能量。 但这需要庞大的基础设施——此类操作被视为非法。</p>"},
	},
}
