package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var CategoriesDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"weapon":     {Name: "weapon", Description: ""},
		"ammo":       {Name: "ammunition", Description: ""},
		"equip":      {Name: "equipment", Description: ""},
		"body":       {Name: "body", Description: ""},
		"resource":   {Name: "mineral resource", Description: ""},
		"recycle":    {Name: "raw material", Description: ""},
		"detail":     {Name: "detail", Description: ""},
		"boxes":      {Name: "box", Description: ""},
		"trash":      {Name: "miscellaneous", Description: ""},
		"skill":      {Name: "-", Description: ""},
		"structure":  {Name: "structure", Description: ""},
		"blueprints": {Name: "blueprint", Description: ""},
		"sector":     {Name: "sector", Description: ""},
		"product":    {Name: "product", Description: ""},
		"fuel":       {Name: "fuel", Description: ""},
		"mine_drone": {Name: "mine drone", Description: ""},
		"package":    {Name: "package", Description: ""},
		"book":       {Name: "skill chip", Description: ""},
	},
	_const.RU: {
		"weapon":     {Name: "оружие", Description: ""},
		"ammo":       {Name: "боеприпас", Description: ""},
		"equip":      {Name: "снаряжение", Description: ""},
		"body":       {Name: "корпус", Description: ""},
		"resource":   {Name: "полезное ископаемое", Description: ""},
		"recycle":    {Name: "сырье", Description: ""},
		"detail":     {Name: "деталь", Description: ""},
		"boxes":      {Name: "ящик", Description: ""},
		"trash":      {Name: "разное", Description: ""},
		"skill":      {Name: "-", Description: ""},
		"structure":  {Name: "строение", Description: ""},
		"blueprints": {Name: "чертеж", Description: ""},
		"sector":     {Name: "сектор", Description: ""},
		"product":    {Name: "товар", Description: ""},
		"fuel":       {Name: "топливо", Description: ""},
		"mine_drone": {Name: "дрон шахтер", Description: ""},
		"package":    {Name: "упаковка", Description: ""},
		"book":       {Name: "чип навыков", Description: ""},
	},
	_const.ZhCN: {
		"weapon":     {Name: "武器", Description: ""},
		"ammo":       {Name: "弹药", Description: ""},
		"equip":      {Name: "装备", Description: ""},
		"body":       {Name: "机身", Description: ""},
		"resource":   {Name: "矿物", Description: ""},
		"recycle":    {Name: "原材料", Description: ""},
		"detail":     {Name: "零件", Description: ""},
		"boxes":      {Name: "箱子", Description: ""},
		"trash":      {Name: "杂项", Description: ""},
		"skill":      {Name: "-", Description: ""},
		"structure":  {Name: "建筑", Description: ""},
		"blueprints": {Name: "蓝图", Description: ""},
		"sector":     {Name: "区域", Description: ""},
		"product":    {Name: "商品", Description: ""},
		"fuel":       {Name: "燃料", Description: ""},
		"mine_drone": {Name: "采矿无人机", Description: ""},
		"package":    {Name: "包裹", Description: ""},
		"book":       {Name: "技能芯片", Description: ""},
	},
}
