package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var EffectsDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"protect_thermo_5":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">5%</span>"},
		"protect_explosion_5": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">5%"},
		"protect_kinetics_5":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">5%</span>"},

		"protect_thermo_10":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">10%</span>"},
		"protect_explosion_10": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного урона</span> на <span class=\"importantly\">10%</span>"},
		"protect_kinetics_10":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">10%</span>"},

		"protect_thermo_15":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">15%</span>"},
		"protect_explosion_15": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">15%"},
		"protect_kinetics_15":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">15%</span>"},

		"protect_thermo_30":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">30%</span>"},
		"protect_explosion_30": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">30%"},
		"protect_kinetics_30":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">30%</span>"},

		"max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>"},
		"max_reverse_speed_20p":  {Description: ""},
		"max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">20%</span>"},
		"max_reverse_factor_20p": {Description: ""},
		"max_move_speed_15":      {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">15%</span>"},
		"max_reverse_speed_15":   {Description: ""},
		"max_power_factor_15":    {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">15%</span>"},
		"max_reverse_factor_15":  {Description: ""},
		"max_move_speed_10":      {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">10%</span>"},
		"max_reverse_speed_10":   {Description: ""},
		"max_power_factor_10":    {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">10%</span>"},
		"max_reverse_factor_10":  {Description: ""},
		"max_move_speed_5":       {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>"},
		"max_reverse_speed_5":    {Description: ""},
		"max_power_factor_5":     {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">5%</span>"},
		"max_reverse_factor_5":   {Description: ""},

		"reduced_max_move_speed_10":     {Description: "Максимальная <span class=\"importantly\">скорость</span> снижена на <span class=\"importantly\">10%</span>."},
		"reduced_max_reverse_speed_10":  {Description: ""},
		"reduced_max_power_factor_10":   {Description: "<span class=\"importantly\">Скорость разгона</span> снижена на <span class=\"importantly\">10%</span>."},
		"reduced_max_reverse_factor_10": {Description: ""},

		"antigravity_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_5":  {Description: ""},
		"antigravity_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_5": {Description: ""},

		"antigravity_max_move_speed_10p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">10%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_10p":  {Description: ""},
		"antigravity_max_power_factor_10p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">10%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_10p": {Description: ""},

		"antigravity_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_20p":  {Description: ""},
		"antigravity_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_20p": {Description: ""},

		"wheels_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_speed_5":  {Description: ""},
		"wheels_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_factor_5": {Description: ""},

		"wheels_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_speed_20p":  {Description: ""},
		"wheels_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_factor_20p": {Description: ""},

		"caterpillars_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_5":  {Description: ""},
		"caterpillars_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_5": {Description: ""},

		"caterpillars_max_move_speed_15p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_15p":  {Description: ""},
		"caterpillars_max_power_factor_15p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_15p": {Description: ""},

		"caterpillars_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_20p":  {Description: ""},
		"caterpillars_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_20p": {Description: ""},

		"antigravity_turn_speed_5":  {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"wheels_turn_speed_15p":     {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_turn_speed_5":       {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"caterpillars_turn_speed_5": {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},

		"reduced_body_capacity_size_25p": {Description: "Максимальный <span class=\"importantly\">объем трюма</span> уменьшен на <span class=\"importantly\">25%</span>"},
		"body_capacity_size_50p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">50%</span>"},
		"body_capacity_size_40p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">40%</span>"},
		"body_capacity_size_30p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">30%</span>"},
		"body_capacity_size_25":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">25%</span>"},
		"body_capacity_size_20p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">20%</span>"},
		"body_capacity_size_15p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">15%</span>"},
		"body_capacity_size_10":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">10%</span>"},
		"body_capacity_size_5p":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">5%</span>"},

		"body_radar_25p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">25%</span>"},
		"body_radar_20p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">20%</span>"},
		"body_radar_15":          {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">15%</span>"},
		"body_radar_10p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">10%</span>"},
		"body_radar_5":           {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">5%</span>"},
		"reduced_body_radar_20p": {Description: "Уменьшение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">20%</span>"},

		"body_view_25p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">25%</span>"},
		"body_view_20p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">20%</span>"},
		"body_view_15p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">15%</span>"},
		"body_view_10":  {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">10%</span>"},
		"body_view_5":   {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">5%</span>"},

		"ballistic_small_damage_15": {Description: "<span class=\"importantly\">Урон малых баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_damage_5":        {Description: "<span class=\"importantly\">Урон баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_small_rate_20p": {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_small_rate_15p": {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_small_rate_10":  {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_small_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_big_rate_20p": {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_big_rate_15p": {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_big_rate_10":  {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_big_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_medium_rate_20p": {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_medium_rate_15p": {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_medium_rate_10":  {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_medium_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота баллистических орудий</span> увеличена на <span class=\"importantly\">5%</span>"},
		"ballistic_accuracy_25p":         {Description: "<span class=\"importantly\">Точность баллистических орудий</span> увеличена на <span class=\"importantly\">25%</span>"},
		"ballistic_damage_20p":           {Description: "<span class=\"importantly\">Урон баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота баллистических орудий</span> увеличена на <span class=\"importantly\">25%</span>"},

		"laser_small_damage_20p": {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_small_damage_15":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_small_damage_10":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_small_damage_5p":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_medium_damage_20p": {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_medium_damage_15p": {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_medium_damage_10":  {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_medium_damage_5p":  {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_big_damage_20p": {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_big_damage_15p": {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_big_damage_10":  {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_big_damage_5p":  {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота лазерных орудий</span> увеличена на <span class=\"importantly\">5%</span>"},
		"laser_damage_5":             {Description: "<span class=\"importantly\">Урон лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},
		"laser_accuracy_25p":         {Description: "<span class=\"importantly\">Точность лазерных орудий</span> увеличена на <span class=\"importantly\">25%</span>"},
		"laser_damage_20p":           {Description: "<span class=\"importantly\">Урон лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота лазерных орудий</span> увеличена на <span class=\"importantly\">25%</span>"},

		"missile_small_damage_20p": {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_small_damage_15":  {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">15%</span>"},
		"missile_small_damage_10p": {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">10%</span>"},
		"missile_small_damage_5p":  {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_small_rate_15": {Description: "<span class=\"importantly\">Скорострельность малых пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},

		"missile_small_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_small_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_small_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_small_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_medium_damage_20p": {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_medium_damage_15":  {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">15%</span>"},
		"missile_medium_damage_10p": {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">10%</span>"},
		"missile_medium_damage_5p":  {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_damage_5": {Description: "<span class=\"importantly\">Урон пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_medium_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_medium_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_medium_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_medium_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_big_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_big_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_big_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_big_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},
		"missile_accuracy_25p":         {Description: "<span class=\"importantly\">Точность пусковых установок</span> увеличена на <span class=\"importantly\">25%</span>"},
		"missile_damage_20p":           {Description: "<span class=\"importantly\">Урон пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота пусковых установок</span> увеличена на <span class=\"importantly\">25%</span>"},

		"jammer_saving_energy_25": {Description: "Уменьшает потребление энергии <span class=\"importantly\">подавителей связи</span> на <span class=\"importantly\">25%</span>"},

		"body_power_capacity_size_25": {Description: "Максимальный <span class=\"importantly\">объем аккумулятора</span> увеличен на <span class=\"importantly\">25%</span>"},
		"body_power_capacity_size_10": {Description: "Максимальный <span class=\"importantly\">объем аккумулятора</span> увеличен на <span class=\"importantly\">10%</span>"},

		"body_power_charging_25p": {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">25%</span>"},
		"body_power_charging_20p": {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">20%</span>"},
		"body_power_charging_15":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">15%</span>"},
		"body_power_charging_10":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">10%</span>"},
		"body_power_charging_5p":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">5%</span>"},

		"invisibility_saving_energy_25": {Description: "Уменьшает потребление энергии <span class=\"importantly\">модулей невидимости</span> на <span class=\"importantly\">25%</span>"},

		"body_resource_capacity_size_25":  {Description: "На <span class=\"importantly\">25%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_40":  {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для руды"},

		"body_organic_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для органики"},

		"body_oil_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для нефти"},

		"body_dust_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для гранул"},

		"body_max_energy_10":          {Description: "На <span class=\"importantly\">10%</span> увеличивается мощность реактора в корпусе."},
		"body_max_energy_25p":         {Description: "На <span class=\"importantly\">25%</span> увеличивается мощность реактора в корпусе."},
		"reduced_body_max_energy_15p": {Description: "На <span class=\"importantly\">15%</span> уменьшает мощность реактора в корпусе."},

		"body_max_hp_150":         {Description: "На <span class=\"importantly\">150</span> ед. увеличивается кол-во жизней корпуса."},
		"body_max_hp_25p":         {Description: "На <span class=\"importantly\">25%</span> увеличивается кол-во жизней корпуса."},
		"reduced_body_max_hp_25p": {Description: "На <span class=\"importantly\">25%</span> уменьшает кол-во жизней корпуса."},
		//
		"bonus_max_move_speed_15": {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">15%</span>"},
		"bonus_max_move_speed_10": {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">10%</span>"},
		"bonus_max_move_speed_5":  {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">5%</span>"},

		"bonus_protect_20": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">20%</span>"},
		"bonus_protect_15": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">15%</span>"},
		"bonus_protect_10": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">10%</span>"},
		"bonus_protect_5":  {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">5%</span>"},

		"speed_oil_extract_25p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">25%</span>"},
		"speed_oil_extract_50p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">50%</span>"},
		"speed_oil_extract_75p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">75%</span>"},
		"speed_oil_extract_100p": {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">100%</span>"},

		"speed_ore_extract_10p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">10%</span>"},
		"speed_ore_extract_20p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">20%</span>"},
		"speed_ore_extract_30p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">30%</span>"},
		"speed_ore_extract_40p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">40%</span>"},

		"ore_saving_energy_15p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">15%</span>"},
		"ore_saving_energy_30p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">30%</span>"},
		"ore_saving_energy_45p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">45%</span>"},
		"ore_saving_energy_60p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">60%</span>"},

		"dust_saving_energy_15p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">15%</span>"},
		"dust_saving_energy_30p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">30%</span>"},
		"dust_saving_energy_45p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">45%</span>"},
		"dust_saving_energy_60p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">60%</span>"},

		"speed_combine_extract_10p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">10%</span>"},
		"speed_combine_extract_20p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">20%</span>"},
		"speed_combine_extract_30p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">30%</span>"},
		"speed_combine_extract_40p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">40%</span>"},

		"sync_bonus_small_laser_damage":    {Description: "на <span class=\"importantly\">5%</span> повышается урон малых лазерных орудий."},
		"sync_bonus_power_charging":        {Description: "на <span class=\"importantly\">5%</span> ускоряет подзарядку аккумулятора."},
		"sync_bonus_resource_capacity":     {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для руды."},
		"sync_bonus_organic_capacity":      {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для органики."},
		"sync_bonus_oil_capacity":          {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для нефти."},
		"sync_bonus_dust_capacity":         {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для гранул."},
		"sync_bonus_radar":                 {Description: "на <span class=\"importantly\">5%</span> увеличение радиуса радара."},
		"sync_bonus_ballistic_small_rate":  {Description: "на <span class=\"importantly\">5%</span> скорострельность малых баллистических орудий."},
		"sync_bonus_max_move_speed":        {Description: "на <span class=\"importantly\">5%</span> увеличение максимальной скорость и скорости разгона."},
		"sync_bonus_capacity_size":         {Description: "на <span class=\"importantly\">10%</span> увеличение размера трюма."},
		"sync_bonus_ballistic_big_rate":    {Description: "на <span class=\"importantly\">5%</span> скорострельность больших баллистических орудий."},
		"sync_bonus_protect":               {Description: "на <span class=\"importantly\">5%</span> защита от всех типов урона."},
		"sync_bonus_big_laser_damage":      {Description: "на <span class=\"importantly\">5%</span> повышается урон больших лазерных орудий."},
		"sync_bonus_small_missile_damage":  {Description: "на <span class=\"importantly\">5%</span> повышается урон малых пусковых установок."},
		"sync_bonus_small_missile_reload":  {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки малых пусковых установок."},
		"sync_bonus_missile_big_reload":    {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки больших пусковых установок."},
		"sync_bonus_view":                  {Description: "на <span class=\"importantly\">5%</span> увеличение радиуса обзора."},
		"sync_bonus_medium_laser_damage":   {Description: "на <span class=\"importantly\">5%</span> повышается урон средних лазерных орудий."},
		"sync_bonus_ballistic_medium_rate": {Description: "на <span class=\"importantly\">5%</span> скорострельность средних баллистических орудий."},
		"sync_bonus_medium_missile_reload": {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки средних пусковых установок."},
		"sync_bonus_speed_oil_extract":     {Description: "на <span class=\"importantly\">25%</span> увеличена скорость добычи насосов."},
		"sync_bonus_speed_ore_extract":     {Description: "на <span class=\"importantly\">10%</span> увеличена скорость добычи буровых лазеров."},
		"sync_bonus_speed_combine_extract": {Description: "на <span class=\"importantly\">10%</span> увеличена эффективность добычи комбайна."},
		"sync_ore_saving_energy":           {Description: "на <span class=\"importantly\">15%</span> уменьшает потребляемую энергию буровых лазеров."},
		"sync_dust_saving_energy":          {Description: "на <span class=\"importantly\">15%</span> уменьшает потребляемую энергию собирателя пыли."},

		"effect_nuclear_fuel":   {Description: "На <span class=\"importantly\">1%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},
		"effect_synthetic_fuel": {Description: "На <span class=\"importantly\">2%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},
		"effect_jet_fuel":       {Description: "На <span class=\"importantly\">3%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},

		"empty": {Description: ""},
	},
	_const.RU: {
		"protect_thermo_5":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">5%</span>"},
		"protect_explosion_5": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">5%"},
		"protect_kinetics_5":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">5%</span>"},

		"protect_thermo_10":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">10%</span>"},
		"protect_explosion_10": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного урона</span> на <span class=\"importantly\">10%</span>"},
		"protect_kinetics_10":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">10%</span>"},

		"reduced_protect_thermo_10":    {Description: "Уменьшает защиту от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">10%</span>"},
		"reduced_protect_explosion_10": {Description: "Уменьшает защиту от <span class=\"importantly\">взрывного урона</span> на <span class=\"importantly\">10%</span>"},
		"reduced_protect_kinetics_10":  {Description: "Уменьшает защиту от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">10%</span>"},

		"protect_thermo_15":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">15%</span>"},
		"protect_explosion_15": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">15%"},
		"protect_kinetics_15":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">15%</span>"},

		"protect_thermo_20p":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">20%</span>"},
		"protect_explosion_20p": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">20%"},
		"protect_kinetics_20p":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">20%</span>"},

		"protect_thermo_30":    {Description: "Увеличение защиты от <span class=\"importantly\">термического</span> урона на <span class=\"importantly\">30%</span>"},
		"protect_explosion_30": {Description: "Увеличение защиты от <span class=\"importantly\">взрывного</span> урона на <span class=\"importantly\">30%"},
		"protect_kinetics_30":  {Description: "Увеличение защиты от <span class=\"importantly\">кинетического</span> урона на <span class=\"importantly\">30%</span>"},

		"max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>"},
		"max_reverse_speed_20p":  {Description: ""},
		"max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">20%</span>"},
		"max_reverse_factor_20p": {Description: ""},
		"max_move_speed_15":      {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">15%</span>"},
		"max_reverse_speed_15":   {Description: ""},
		"max_power_factor_15":    {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">15%</span>"},
		"max_reverse_factor_15":  {Description: ""},
		"max_move_speed_10":      {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">10%</span>"},
		"max_reverse_speed_10":   {Description: ""},
		"max_power_factor_10":    {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">10%</span>"},
		"max_reverse_factor_10":  {Description: ""},
		"max_move_speed_5":       {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>"},
		"max_reverse_speed_5":    {Description: ""},
		"max_power_factor_5":     {Description: "<span class=\"importantly\">Скорость разгона</span> увеличена на <span class=\"importantly\">5%</span>"},
		"max_reverse_factor_5":   {Description: ""},

		"reduced_max_move_speed_10":     {Description: "Максимальная <span class=\"importantly\">скорость</span> снижена на <span class=\"importantly\">10%</span>."},
		"reduced_max_reverse_speed_10":  {Description: ""},
		"reduced_max_power_factor_10":   {Description: "<span class=\"importantly\">Скорость разгона</span> снижена на <span class=\"importantly\">10%</span>."},
		"reduced_max_reverse_factor_10": {Description: ""},

		"antigravity_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_5":  {Description: ""},
		"antigravity_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_5": {Description: ""},

		"antigravity_max_move_speed_10p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">10%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_10p":  {Description: ""},
		"antigravity_max_power_factor_10p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">10%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_10p": {Description: ""},

		"antigravity_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_speed_20p":  {Description: ""},
		"antigravity_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},
		"antigravity_max_reverse_factor_20p": {Description: ""},

		"wheels_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_speed_5":  {Description: ""},
		"wheels_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_factor_5": {Description: ""},

		"wheels_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_speed_20p":  {Description: ""},
		"wheels_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_max_reverse_factor_20p": {Description: ""},

		"caterpillars_max_move_speed_5":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_5":  {Description: ""},
		"caterpillars_max_power_factor_5":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_5": {Description: ""},

		"caterpillars_max_move_speed_15p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_15p":  {Description: ""},
		"caterpillars_max_power_factor_15p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_15p": {Description: ""},

		"caterpillars_max_move_speed_20p":     {Description: "Максимальная <span class=\"importantly\">скорость</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_speed_20p":  {Description: ""},
		"caterpillars_max_power_factor_20p":   {Description: "<span class=\"importantly\">Скорость разгон</span> увеличена на <span class=\"importantly\">20%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},
		"caterpillars_max_reverse_factor_20p": {Description: ""},

		"antigravity_turn_speed_5": {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">антигравитацией</span>."},

		"wheels_turn_speed_15p":     {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">15%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"wheels_turn_speed_5":       {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">колесами</span>."},
		"caterpillars_turn_speed_5": {Description: "<span class=\"importantly\">Скорость поворота</span> увеличена на <span class=\"importantly\">5%</span>. Действует на корпуса с <span class=\"importantly\">гусеницами</span>."},

		"reduced_body_capacity_size_25p": {Description: "Максимальный <span class=\"importantly\">объем трюма</span> уменьшен на <span class=\"importantly\">25%</span>"},
		"body_capacity_size_50p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">50%</span>"},
		"body_capacity_size_40p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">40%</span>"},
		"body_capacity_size_30p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">30%</span>"},
		"body_capacity_size_25":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">25%</span>"},
		"body_capacity_size_20p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">20%</span>"},
		"body_capacity_size_15p":         {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">15%</span>"},
		"body_capacity_size_10":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">10%</span>"},
		"body_capacity_size_5p":          {Description: "Максимальный <span class=\"importantly\">объем трюма</span> увеличен на <span class=\"importantly\">5%</span>"},

		"body_radar_25p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">25%</span>"},
		"body_radar_20p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">20%</span>"},
		"body_radar_15":          {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">15%</span>"},
		"body_radar_10p":         {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">10%</span>"},
		"body_radar_5":           {Description: "Увеличение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">5%</span>"},
		"reduced_body_radar_20p": {Description: "Уменьшение радиуса <span class=\"importantly\">радара</span> на <span class=\"importantly\">20%</span>"},

		"body_view_25p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">25%</span>"},
		"body_view_20p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">20%</span>"},
		"body_view_15p": {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">15%</span>"},
		"body_view_10":  {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">10%</span>"},
		"body_view_5":   {Description: "Увеличение радиуса <span class=\"importantly\">обзора</span> на <span class=\"importantly\">5%</span>"},

		"body_power_capacity_size_25": {Description: "Максимальный <span class=\"importantly\">объем аккумулятора</span> увеличен на <span class=\"importantly\">25%</span>"},
		"body_power_capacity_size_10": {Description: "Максимальный <span class=\"importantly\">объем аккумулятора</span> увеличен на <span class=\"importantly\">10%</span>"},

		"ballistic_small_damage_15": {Description: "<span class=\"importantly\">Урон малых баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_damage_5":        {Description: "<span class=\"importantly\">Урон баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_small_rate_20p": {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_small_rate_15p": {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_small_rate_10":  {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_small_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность малых баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_medium_rate_20p": {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_medium_rate_15p": {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_medium_rate_10":  {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_medium_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность средних баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_big_rate_20p": {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_big_rate_15p": {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"ballistic_big_rate_10":  {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"ballistic_big_rate_5p":  {Description: "<span class=\"importantly\">Скорострельность больших баллистических орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"ballistic_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота баллистических орудий</span> увеличена на <span class=\"importantly\">5%</span>"},
		"ballistic_accuracy_25p":         {Description: "<span class=\"importantly\">Точность баллистических орудий</span> увеличена на <span class=\"importantly\">25%</span>"},
		"ballistic_damage_20p":           {Description: "<span class=\"importantly\">Урон баллистических орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"ballistic_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота баллистических орудий</span> увеличена на <span class=\"importantly\">25%</span>"},

		"laser_small_damage_20p": {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_small_damage_15":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_small_damage_10":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_small_damage_5p":  {Description: "<span class=\"importantly\">Урон малых лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_medium_damage_20p": {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_medium_damage_15p": {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_medium_damage_10":  {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_medium_damage_5p":  {Description: "<span class=\"importantly\">Урон средних лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_big_damage_20p": {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_big_damage_15p": {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">15%</span>"},
		"laser_big_damage_10":  {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">10%</span>"},
		"laser_big_damage_5p":  {Description: "<span class=\"importantly\">Урон больших лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},

		"laser_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота лазерных орудий</span> увеличена на <span class=\"importantly\">5%</span>"},
		"laser_damage_5":             {Description: "<span class=\"importantly\">Урон лазерных орудий</span> увеличен на <span class=\"importantly\">5%</span>"},
		"laser_accuracy_25p":         {Description: "<span class=\"importantly\">Точность лазерных орудий</span> увеличена на <span class=\"importantly\">25%</span>"},
		"laser_damage_20p":           {Description: "<span class=\"importantly\">Урон лазерных орудий</span> увеличен на <span class=\"importantly\">20%</span>"},
		"laser_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота лазерных орудий</span> увеличена на <span class=\"importantly\">25%</span>"},

		"missile_small_damage_20p": {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_small_damage_15":  {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">15%</span>"},
		"missile_small_damage_10p": {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">10%</span>"},
		"missile_small_damage_5p":  {Description: "<span class=\"importantly\">Урон малых пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_small_rate_15": {Description: "<span class=\"importantly\">Скорострельность малых пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},

		"missile_small_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_small_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_small_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_small_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки малых пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_medium_damage_20p": {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_medium_damage_15":  {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">15%</span>"},
		"missile_medium_damage_10p": {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">10%</span>"},
		"missile_medium_damage_5p":  {Description: "<span class=\"importantly\">Урон средних пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_damage_5": {Description: "<span class=\"importantly\">Урон пусковых установок</span> увеличен на <span class=\"importantly\">5%</span>"},

		"missile_medium_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_medium_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_medium_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_medium_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки средних пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_big_reload_20p": {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">20%</span>"},
		"missile_big_reload_15p": {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">15%</span>"},
		"missile_big_reload_10":  {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">10%</span>"},
		"missile_big_reload_5p":  {Description: "<span class=\"importantly\">Скорость перезарядки больших пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},

		"missile_gun_speed_rotate_5":   {Description: "<span class=\"importantly\">Скорость поворота пусковых установок</span> увеличена на <span class=\"importantly\">5%</span>"},
		"missile_accuracy_25p":         {Description: "<span class=\"importantly\">Точность пусковых установок</span> увеличена на <span class=\"importantly\">25%</span>"},
		"missile_damage_20p":           {Description: "<span class=\"importantly\">Урон пусковых установок</span> увеличен на <span class=\"importantly\">20%</span>"},
		"missile_gun_speed_rotate_25p": {Description: "<span class=\"importantly\">Скорость поворота пусковых установок</span> увеличена на <span class=\"importantly\">25%</span>"},

		"jammer_saving_energy_25": {Description: "Уменьшает потребление энергии <span class=\"importantly\">подавителей связи</span> на <span class=\"importantly\">25%</span>"},

		"body_power_charging_25p": {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">25%</span>"},
		"body_power_charging_20p": {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">20%</span>"},
		"body_power_charging_15":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">15%</span>"},
		"body_power_charging_10":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">10%</span>"},
		"body_power_charging_5p":  {Description: "Ускоряет подзарядку аккумулятора на <span class=\"importantly\">5%</span>"},

		"reduced_body_power_charging_20p": {Description: "Уменьшает скорость подзарядки аккумулятора на <span class=\"importantly\">20%</span>"},

		"invisibility_saving_energy_25":   {Description: "Уменьшает потребление энергии <span class=\"importantly\">модулей невидимости</span> на <span class=\"importantly\">25%</span>"},
		"body_resource_capacity_size_25":  {Description: "На <span class=\"importantly\">25%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_40":  {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для руды"},
		"body_resource_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для руды"},

		"body_organic_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для органики"},
		"body_organic_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для органики"},

		"body_oil_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для нефти"},
		"body_oil_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для нефти"},

		"body_dust_capacity_size_40p": {Description: "На <span class=\"importantly\">40%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_30p": {Description: "На <span class=\"importantly\">30%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_20p": {Description: "На <span class=\"importantly\">20%</span> увеличивается вместимость отсека для гранул"},
		"body_dust_capacity_size_10p": {Description: "На <span class=\"importantly\">10%</span> увеличивается вместимость отсека для гранул"},

		"body_max_energy_10":          {Description: "На <span class=\"importantly\">10%</span> увеличивается мощность реактора в корпусе."},
		"body_max_energy_25p":         {Description: "На <span class=\"importantly\">25%</span> увеличивается мощность реактора в корпусе."},
		"reduced_body_max_energy_15p": {Description: "На <span class=\"importantly\">15%</span> уменьшает мощность реактора в корпусе."},

		"body_max_hp_150":         {Description: "На <span class=\"importantly\">150</span> ед. увеличивается кол-во жизней корпуса."},
		"body_max_hp_25p":         {Description: "На <span class=\"importantly\">25%</span> увеличивается кол-во жизней корпуса."},
		"reduced_body_max_hp_25p": {Description: "На <span class=\"importantly\">25%</span> уменьшает кол-во жизней корпуса."},
		//
		"bonus_max_move_speed_15": {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">15%</span>"},
		"bonus_max_move_speed_10": {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">10%</span>"},
		"bonus_max_move_speed_5":  {Description: "Максимальная <span class=\"importantly\">скорость</span> и <span class=\"importantly\">разгон</span> увеличены на <span class=\"importantly\">5%</span>"},

		"bonus_protect_20": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">20%</span>"},
		"bonus_protect_15": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">15%</span>"},
		"bonus_protect_10": {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">10%</span>"},
		"bonus_protect_5":  {Description: "Увеличение защиты от <span class=\"importantly\">всех типов</span> урона на <span class=\"importantly\">5%</span>"},

		"speed_oil_extract_25p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">25%</span>"},
		"speed_oil_extract_50p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">50%</span>"},
		"speed_oil_extract_75p":  {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">75%</span>"},
		"speed_oil_extract_100p": {Description: "Повышает скорость добычи насосов на <span class=\"importantly\">100%</span>"},

		"speed_ore_extract_10p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">10%</span>"},
		"speed_ore_extract_20p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">20%</span>"},
		"speed_ore_extract_30p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">30%</span>"},
		"speed_ore_extract_40p": {Description: "Повышает скорость добычи буровых лазеров на <span class=\"importantly\">40%</span>"},

		"ore_saving_energy_15p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">15%</span>"},
		"ore_saving_energy_30p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">30%</span>"},
		"ore_saving_energy_45p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">45%</span>"},
		"ore_saving_energy_60p": {Description: "Уменьшает потребляемую энергию буровых лазеров на <span class=\"importantly\">60%</span>"},

		"dust_saving_energy_15p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">15%</span>"},
		"dust_saving_energy_30p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">30%</span>"},
		"dust_saving_energy_45p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">45%</span>"},
		"dust_saving_energy_60p": {Description: "Уменьшает потребляемую энергию собирателя пыли на <span class=\"importantly\">60%</span>"},

		"speed_combine_extract_10p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">10%</span>"},
		"speed_combine_extract_20p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">20%</span>"},
		"speed_combine_extract_30p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">30%</span>"},
		"speed_combine_extract_40p": {Description: "Повышает эффективность добычи комбайна на <span class=\"importantly\">40%</span>"},

		"sync_bonus_small_laser_damage":    {Description: "на <span class=\"importantly\">5%</span> повышается урон малых лазерных орудий."},
		"sync_bonus_power_charging":        {Description: "на <span class=\"importantly\">5%</span> ускоряет подзарядку аккумулятора."},
		"sync_bonus_resource_capacity":     {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для руды."},
		"sync_bonus_organic_capacity":      {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для органики."},
		"sync_bonus_oil_capacity":          {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для нефти."},
		"sync_bonus_dust_capacity":         {Description: "на <span class=\"importantly\">10%</span> увеличивается вместимость отсека для гранул."},
		"sync_bonus_radar":                 {Description: "на <span class=\"importantly\">5%</span> увеличение радиуса радара"},
		"sync_bonus_ballistic_small_rate":  {Description: "на <span class=\"importantly\">5%</span> скорострельность малых баллистических орудий"},
		"sync_bonus_max_move_speed":        {Description: "на <span class=\"importantly\">5%</span> увеличение максимальной скорость и скорости разгона"},
		"sync_bonus_capacity_size":         {Description: "на <span class=\"importantly\">10%</span> увеличение размера трюма."},
		"sync_bonus_ballistic_big_rate":    {Description: "на <span class=\"importantly\">5%</span> скорострельность больших баллистических орудий."},
		"sync_bonus_protect":               {Description: "на <span class=\"importantly\">5%</span> защита от всех типов урона."},
		"sync_bonus_big_laser_damage":      {Description: "на <span class=\"importantly\">5%</span> повышается урон больших лазерных орудий."},
		"sync_bonus_small_missile_damage":  {Description: "на <span class=\"importantly\">5%</span> повышается урон малых пусковых установок."},
		"sync_bonus_small_missile_reload":  {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки малых пусковых установок."},
		"sync_bonus_missile_big_reload":    {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки больших пусковых установок."},
		"sync_bonus_view":                  {Description: "на <span class=\"importantly\">5%</span> увеличение радиуса обзора."},
		"sync_bonus_medium_laser_damage":   {Description: "на <span class=\"importantly\">5%</span> повышается урон средних лазерных орудий."},
		"sync_bonus_ballistic_medium_rate": {Description: "на <span class=\"importantly\">5%</span> скорострельность средних баллистических орудий."},
		"sync_bonus_medium_missile_damage": {Description: "на <span class=\"importantly\">5%</span> повышается урон средних пусковых установок."},
		"sync_bonus_medium_missile_reload": {Description: "на <span class=\"importantly\">5%</span> увеличена скорость перезарядки средних пусковых установок."},
		"sync_bonus_speed_oil_extract":     {Description: "на <span class=\"importantly\">25%</span> увеличена скорость добычи насосов."},
		"sync_bonus_speed_ore_extract":     {Description: "на <span class=\"importantly\">10%</span> увеличена скорость добычи буровых лазеров."},
		"sync_bonus_speed_combine_extract": {Description: "на <span class=\"importantly\">10%</span> увеличена эффективность добычи комбайна."},
		"sync_ore_saving_energy":           {Description: "на <span class=\"importantly\">15%</span> уменьшает потребляемую энергию буровых лазеров."},
		"sync_dust_saving_energy":          {Description: "на <span class=\"importantly\">15%</span> уменьшает потребляемую энергию собирателя пыли."},

		"effect_nuclear_fuel":   {Description: "На <span class=\"importantly\">1%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},
		"effect_synthetic_fuel": {Description: "На <span class=\"importantly\">2%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},
		"effect_jet_fuel":       {Description: "На <span class=\"importantly\">3%</span> увеличивает <span class=\"importantly\">ходовые</span> характеристики транспорта и  <span class=\"importantly\">скорость зарядки аккумулятора</span>."},

		"empty": {Description: ""},
	},
}
