package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var EquipDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"armored":                        {Name: "Reinforced armor plate", Description: "<p> A booster for standard hull armor, increasing the overall percentage of damage resistance. </p>"},
		"digger":                         {Name: "Drone \"Phobos\"", Description: "<p> A remotely controlled drone used for exploration work with planetary anomalies and the ability to attack a variety of targets. </p>"},
		"replic_builder":                 {Name: "Engineering module \"Replic\"", Description: "<p> Standardized device for assembling and disassembling objects, as well as detailed extraction of useful parts from wreckage. </p>"},
		"reverses_miner_extracted":       {Name: "Ore pulsator \"Reverses\"", Description: "<p> The standardized rock mining and extraction device on the planet Veliri-6. The device is adapted to the aggressive properties of the environment and is resistant to radiation. </p>"},
		"gravity_square":                 {Name: "Gravitational disturbance resonator", Description: "<p> A cumulative action device that creates waves of a gravitational nature and pulls into the center of its own gravity every thing, including military projectiles. </p>"},
		"repair_kit":                     {Name: "Self-repair module", Description: "<p> About a million nanobots, armed with microelements of spare parts and, upon activation, begin immediate restoration work on the damaged case and systems. </p>"},
		"replic_miner_extracted":         {Name: "Mining projector \"Replic\"", Description: "<p> The standardized rock mining and extraction device on the planet Veliri-6. The device is adapted to the aggressive properties of the environment and is resistant to radiation. </p>"},
		"explores_builder":               {Name: "Engineering module \"Explores\"", Description: "<p> Standardized device for assembling and disassembling objects, as well as detailed extraction of useful parts from wreckage. </p>"},
		"gravity_gun":                    {Name: "MEP-0 device", Description: "<p> A manipulator of gravitational action, used to attract absolutely any captured objects with a directed beam to the position of the device and, with a powerful impulse, send them in a different direction. </p>"},
		"distance_repair":                {Name: "Remote repair system", Description: "<p> Logical development of the \"self-repair module\" system with the ability to send remote repair nanobots to support the recovery of any allied targets. </p>"},
		"jammer":                         {Name: "EMP communication suppressor", Description: "<p> An advanced electromagnetic warfare device that accumulates a kinetic discharge of energy, which temporarily suppresses all other electrical devices. </p>"},
		"missile_defense":                {Name: "Complex-PRO", Description: "<p> A module that provides a no-fly zone in a small radius for any type of missile-salvo system shells, due to overload and failures of their internal guidance systems. </p>"},
		"repair_passive":                 {Name: "Nanite Recovery", Description: "<p> A passive support module that does not consume energy and in case of damage to the hull or any systems - organizing the start of immediate repair work by sending robots-nanites. </p>"},
		"geo_scanner":                    {Name: "Georadar", Description: "<p> A planetary analysis device that allows you to investigate the surface for the presence of inhomogeneities, voids and manifestations of an anomalous nature. </p>"},
		"distance_generator":             {Name: "Power transmission module", Description: "<p> A module specializing in the narrowly targeted transfer of surplus or reserved portion of energy from its own corps to any target at a short distance. </p>"},
		"explores_miner_extracted":       {Name: "Mining Beam \"Explores\"", Description: "<p> The standardized rock mining and extraction device on the planet Veliri-6. The device is adapted to the aggressive properties of the environment and is resistant to radiation. </p>"},
		"reverses_builder":               {Name: "Engineering module \"Reverses\"", Description: "<p> Standardized device for assembling and disassembling objects, as well as detailed extraction of useful parts from wreckage. </p>"},
		"reverses_combine":               {Name: "Harvester", Description: "<p>Standardized device for assembling organic matter.</p>"},
		"energy_shield":                  {Name: "Force field M-shields", Description: "<p> Power emitters of a small spectrum of energy protection, counteracting any phenomenon that tries to overcome the barrier. Significantly reduce damage, but do not guarantee 100% protection. </p>"},
		"mine_bomb_1":                    {Name: "Мины", Description: "Мина"},
		"mini_turret_1":                  {Name: "Переносная турель 1", Description: "Переносная пулеметная турель"},
		"mini_turret_2":                  {Name: "Переносная турель 2", Description: "Переносная ракетная турель"},
		"smoke_screen_local":             {Name: "Дымовая завеса в корпусе", Description: "Дымовая завеса установленная в корпусе, мешает обзору"},
		"smoke_screen_destination":       {Name: "Дымовая завеса в капсулах", Description: "Выстреливает 3 капсулы с дымовой завесой, что мешает обзору"},
		"drone_scout_1":                  {Name: "Дрон разведчик", Description: "Разведыдывает территорию, управляется дистанционно"},
		"drone_defender_1":               {Name: "Дрон защитник 1", Description: "Пулеметный дрон защитник, следует на транспортом и атакует всех врагов которые рядом"},
		"drone_defender_2":               {Name: "Дрон защитник 2", Description: "Ракетный дрон защитник, следует на транспортом и атакует всех врагов которые рядом"},
		"rope_trap_1":                    {Name: "Капкан", Description: "Приковывает горпуном вражеские транспорты и не дает им уехать дальше размера горпуна"},
		"grenade_1":                      {Name: "Разрывная граната", Description: "Атакует и отбрасывает всех в зоне поражения"},
		"gravity_grenade_1":              {Name: "Гравитационная граната", Description: "На месте разрыва открывает небольшную черную дыру :D"},
		"jump_drive_1":                   {Name: "Прыжковый двигатель", Description: "Создает взрывную волну вокруг корпуса которая не повреждает его а толкает в нужном направление"},
		"invisibility_1":                 {Name: "Невидимость", Description: "Делает корпус невидимым для всех сенсорных систем включая визуальные"},
		"wall_1":                         {Name: "Стена", Description: "Выбрасывает строительный модуль который автоматически возводит небольшую стену, позволяет закрыть узкую область или защититься"},
		"energy_shield_mini_structure_1": {Name: "Дистанционное силовое поле", Description: "Выбрасывает капсулу с ядром щита, щит работает до тех пор пока в нем есть энергия"},
		"pump_extracted":                 {Name: "Насос", Description: "Позволяет добывать жидкие ресурсы, включая нефть."},
		"inventory_scanner_1":            {Name: "Сканер", Description: "<p>Позволяет сканировать трюмы других транспортов.</p> <p>Использование в безопасных секторах - нарушает закон.</p>"},
		"dust_collector":                 {Name: "Сборщик пыли", Description: "<p></p>"},

		// пассивное
		"radar_booster_1":                {Name: "radar_booster_1", Description: ""},
		"view_booster_1":                 {Name: "view_booster_1", Description: ""},
		"improved_inventory_capacity_1":  {Name: "improved_inventory_capacity_1", Description: ""},
		"antigravity_speed_booster_1":    {Name: "antigravity_speed_booster_1", Description: ""},
		"caterpillars_speed_booster_1":   {Name: "caterpillars_speed_booster_1", Description: ""},
		"antigravity_mobility_booster_1": {Name: "antigravity_mobility_booster_1", Description: ""},
		"wheels_mobility_booster_1":      {Name: "wheels_mobility_booster_1", Description: ""},
		"ballistic_rotate_booster_1":     {Name: "ballistic_rotate_booster_1", Description: ""},
		"ballistic_damage_booster_1":     {Name: "ballistic_damage_booster_1", Description: ""},
		"missile_rotate_booster_1":       {Name: "missile_rotate_booster_1", Description: ""},
		"missile_damage_booster_1":       {Name: "missile_damage_booster_1", Description: ""},
		"laser_rotate_booster_1":         {Name: "laser_rotate_booster_1", Description: ""},
		"laser_damage_booster_1":         {Name: "laser_damage_booster_1", Description: ""},
		"energy_capacity_1":              {Name: "energy_capacity_1", Description: ""},
		"energy_charging_speed_1":        {Name: "energy_charging_speed_1", Description: ""},
		"power_booster_1":                {Name: "power_booster_1", Description: ""},
		"body_structure_booster_1":       {Name: "body_structure_booster_1", Description: ""},

		"rig_armored":                       {Name: "Модификатор: броня общая", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_explosion":             {Name: "Модификатор: броня от взрыва", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_kinetics":              {Name: "Модификатор: броня от кинетики", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_thermo":                {Name: "Модификатор: броня от термо", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_body_structure_booster":        {Name: "Модификатор: конструкция", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_caterpillars_speed_booster_1":  {Name: "Модификатор: скорость гусениц", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_antigravity_speed_booster_1":   {Name: "Модификатор: скорость антиграва", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_wheels_speed_booster_1":        {Name: "Модификатор: скорость колес", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_radar_booster_1":               {Name: "Модификатор: радар", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_view_booster_1":                {Name: "Модификатор: линзы", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_energy_capacity_1":             {Name: "Модификатор: емкость аккумулятора", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_energy_charging_speed_1":       {Name: "Модификатор: зарядка аккумулятора", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_improved_inventory_capacity_1": {Name: "Модификатор: объем трюма", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_power_booster_1":               {Name: "Модификатор: реактор", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_missile_damage_booster_1":      {Name: "Модификатор: урон ракет", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_laser_damage_booster_1":        {Name: "Модификатор: урон лазера", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_ballistic_damage_booster_1":    {Name: "Модификатор: урон снарядов", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_ballistic_rotate_booster_1":    {Name: "Модификатор: турель баллистики", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_missile_rotate_booster_1":      {Name: "Модификатор: турель пусковой установки", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_laser_rotate_booster_1":        {Name: "Модификатор: турель лазера", Description: "<p>Модуль уничтожается если его снять!</p>"},
	},
	_const.RU: {
		"repair_kit":                     {Name: "Модуль само-ремонта", Description: "<p>Около миллиона наноботов, вооружённых микроэлементами запчастей и при активации, приступающих к незамедлительным восстановительным работам повреждённого корпуса и систем.</p>"},
		"energy_shield":                  {Name: "М-щиты силового поля", Description: "<p>Силовые излучатели малого спектра энергетической защиты, противодействующих любому явлению, что пытается преодолеть барьер.  Существенно снижают урон, но не гарантируют стопроцентной защиты.</p>"},
		"armored":                        {Name: "Армированная броненакладка", Description: "<p>Усилитель стандартной брони корпуса, повышающий общий процент сопротивляемости к урону.</p>"},
		"digger":                         {Name: "Дрон \"Фобос\"", Description: "<p>Дрон на удалённом управлении, применяемый для работ изыскательного характера с планетарными аномалиями и возможностью атаки самых разных целей.</p>"},
		"geo_scanner":                    {Name: "Георадар", Description: "<p>Устройство планетарного анализа, позволяющее исследовать поверхность на наличие неоднородностей, пустот и проявлений аномального характера.</p>"},
		"jammer":                         {Name: "ЭМИ подавитель связи", Description: "<p>Передовое устройство электромагнитной войны, аккумулирующее кинетический разряд энергии, что на время глушит все прочие электротехнические устройства.</p>"},
		"missile_defense":                {Name: "Комплекс-ПРО", Description: "<p>Модуль, обеспечивающий в малом радиусе бесполётную зону для любых видов снарядов ракетно-залповых систем, за счёт перегрузки и сбоев их внутренних систем наведения.</p>"},
		"repair_passive":                 {Name: "Нанитовое восстановление", Description: "<p>Модуль пассивной поддержки, не расходующий энергии и в случае выявления повреждений корпуса или, каких-либо систем – организующий начало незамедлительных ремонтных работ, за счёт отправки роботов-нанитов.</p>"},
		"distance_repair":                {Name: "Д\\У система ремонта", Description: "<p>Логическое развитие системы «модуля само-ремонта» с возможностью отправки дистанциируемых ремонтных наноботов для оказания поддержки восстановления любых союзных целей.</p>"},
		"distance_generator":             {Name: "Модуль передачи энергии", Description: "<p>Модуль, специализирующийся на узконаправленной передаче излишка или зарезервированной доли энергии из собственного корпуса к любой цели на малой дистанции.</p>"},
		"replic_miner_extracted":         {Name: "Горнопроходческий проектор \"Replic\"", Description: "<p>Стандартизированное устройство по разработке и извлечению горных пород на планете Veliri-6. Устройство адаптировано под агрессивные свойства окружающей среды и устойчиво к радиации.</p>"},
		"replic_builder":                 {Name: "Инженерный модуль \"Replic\"", Description: "<p>Стандартизированное устройство по сборке и разборке объектов, а также детальнейшей добыче полезных частей из обломков.</p>"},
		"explores_miner_extracted":       {Name: "Добывающий луч \"Explores\"", Description: "<p>Стандартизированное устройство по разработке и извлечению горных пород на планете Veliri-6. Устройство адаптировано под агрессивные свойства окружающей среды и устойчиво к радиации.</p>"},
		"explores_builder":               {Name: "Инженерный модуль \"Explores\"", Description: "<p>Стандартизированное устройство по сборке и разборке объектов, а также детальнейшей добыче полезных частей из обломков.</p>"},
		"reverses_miner_extracted":       {Name: "Рудный пульсатор \"Reverses\"", Description: "<p>Стандартизированное устройство по разработке и извлечению горных пород на планете Veliri-6. Устройство адаптировано под агрессивные свойства окружающей среды и устойчиво к радиации.</p>"},
		"reverses_builder":               {Name: "Инженерный модуль \"Reverses\"", Description: "<p>Стандартизированное устройство по сборке и разборке объектов, а также детальнейшей добыче полезных частей из обломков.</p>"},
		"reverses_combine":               {Name: "Комбайн", Description: "<p>Стандартизированное устройство по сборке органики.</p>"},
		"gravity_gun":                    {Name: "Устройство МЭП-0", Description: "<p>Манипулятор гравитационного воздействия, применяемый для притягивания направленным лучом абсолютно любых захваченных объектов к позиции работы устройства и, мощным импульсом – их отправки в иное направление.</p>"},
		"gravity_square":                 {Name: "Резонатор гравитационного возмущения", Description: "<p>Устройство накопительного действия, создающего волны гравитационной природы и затягивающего в центр собственного притяжения всякую вещь, включая боевые снаряды.</p>"},
		"mini_turret_1":                  {Name: "Переносная турель 1", Description: "Переносная пулеметная турель"},
		"mini_turret_2":                  {Name: "Переносная турель 2", Description: "Переносная ракетная турель"},
		"smoke_screen_local":             {Name: "Дымовая завеса в корпусе", Description: "Дымовая завеса установленная в корпусе, мешает обзору"},
		"smoke_screen_destination":       {Name: "Дымовая завеса в капсулах", Description: "Выстреливает 3 капсулы с дымовой завесой, что мешает обзору"},
		"drone_scout_1":                  {Name: "Дрон разведчик", Description: "Разведыдывает территорию, управляется дистанционно"},
		"drone_defender_1":               {Name: "Дрон защитник 1", Description: "Пулеметный дрон защитник, следует на транспортом и атакует всех врагов которые рядом"},
		"drone_defender_2":               {Name: "Дрон защитник 2", Description: "Ракетный дрон защитник, следует на транспортом и атакует всех врагов которые рядом"},
		"rope_trap_1":                    {Name: "Капкан", Description: "Приковывает горпуном вражеские транспорты и не дает им уехать дальше размера горпуна. Эффективно против легкой техники но средняя и тяжелая скорее всего быстро порвут трос."},
		"grenade_1":                      {Name: "Разрывная граната", Description: "Атакует и отбрасывает всех в зоне поражения"},
		"gravity_grenade_1":              {Name: "Гравитационная граната", Description: "На месте разрыва открывает небольшную черную дыру :D"},
		"jump_drive_1":                   {Name: "Прыжковый двигатель", Description: "Создает взрывную волну вокруг корпуса которая не повреждает его а толкает в нужном направление"},
		"invisibility_1":                 {Name: "Невидимость", Description: "Делает корпус невидимым для всех сенсорных систем включая визуальные"},
		"wall_1":                         {Name: "Стена", Description: "Выбрасывает строительный модуль который автоматически возводит небольшую стену, позволяет закрыть узкую область или защититься"},
		"energy_shield_mini_structure_1": {Name: "Дистанционное силовое поле", Description: "Выбрасывает капсулу с ядром щита, щит работает до тех пор пока в нем есть энергия"},
		"pump_extracted":                 {Name: "Насос", Description: "Позволяет добывать жидкие ресурсы, включая нефть."},
		"inventory_scanner_1":            {Name: "Сканер", Description: "Позволяет сканировать трюмы других транспортов."},
		"mine_bomb_1":                    {Name: "Миноукладчик", Description: "<p>Это устройство, которое позволяет транспортному средству устанавливать мину позади себя.</p><p>Мина срабатывает, если вражеский транспорт попадает в зону поражения мины и взрывается, нанося большой урон и отбрасывая цель.</p>"},
		"dust_collector":                 {Name: "Сборщик пыли", Description: "<p></p>"},

		// пассивное
		"radar_booster_1":                {Name: "Репитер сенсоров", Description: "<p>Станция набора усилителей, обеспечивающих увеличенную дальность действия уже установленной радарной системы.</p><p>Радар позволяет обнаруживать и идентифицировать объекты в мире, такие как ресурсы, структуры, транспорты и дроны/ракеты.</p>"},
		"view_booster_1":                 {Name: "Собирающая линза", Description: "<p>Прототип наблюдательного оборудования, обеспечивающее гарантированное увеличение дальности и качества обзора.</p>"},
		"improved_inventory_capacity_1":  {Name: "К.Г.Р.Т", Description: "<p>«Контроллер Грузового Расширителя Трюма» - апгрейд корпуса, чья функция расширить объём трюма за счёт продвинутой модульной системы структуризации.</p>"},
		"antigravity_speed_booster_1":    {Name: "Инжектор", Description: "<p>Ускоритель частиц вакуумной камеры, позволяющий корпусам на антиграве развивать более высокую скорость за счёт переменного электро-поля.</p>"},
		"caterpillars_speed_booster_1":   {Name: "Т-подвеска", Description: "<p>Разработка облегчённой и как следствие более простой в технологиях гусеничной подвески, чьё единственное достоинство – увеличение скорости гусеничного транспорта.</p>"},
		"antigravity_mobility_booster_1": {Name: "Маневровая установка", Description: "<p>Модуль, применимый только к корпусам на антиграве, чья активация формирует образование ионизированной дуги и увеличения манёвренности.</p>"},
		"wheels_mobility_booster_1":      {Name: "Кинематика оси", Description: "<p>Стандартизированное улучшение колёсного транспорта. После установки, повышает характеристики манёвренности/резкости поворота корпуса.</p>"},
		"ballistic_rotate_booster_1":     {Name: "Ротатор: баллистика", Description: "<p>Устройство башенного вращения, позволяющее уменьшить сроки поворота баллистического оружия.</p>"},
		"ballistic_damage_booster_1":     {Name: "Разгонный модуль", Description: "<p>Аппарат замкнутого магнитного поля, при выстреле разгоняющий баллистические виды боеприпасов, чем повышает наносимый ими урон.</p>"},
		"missile_rotate_booster_1":       {Name: "Ротатор: ракеты", Description: "<p>Устройство башенного вращения, позволяющее уменьшить сроки поворота ракетного оружия.</p>"},
		"missile_damage_booster_1":       {Name: "Прожигающий наконечник", Description: "<p>Модуль усиления ракетного вооружения за счёт замены стандартных способов поражения на узконаправленное кумулятивное воздействие, чем повышает наносимый урон.</p>"},
		"laser_rotate_booster_1":         {Name: "Ротатор: лазер", Description: "<p>Устройство башенного вращения, позволяющее уменьшить сроки поворота лазерного оружия.</p>"},
		"laser_damage_booster_1":         {Name: "Термический накопитель", Description: "<p>Испускатель нагревательного элемента, при выстреле выделяющий более концентрированный сгусток тепла, чем повышает урон лазерного вооружения.</p>"},
		"energy_capacity_1":              {Name: "Аккумулятор", Description: "<p>Техническое оборудование энергетической разновидности. Обеспечивает корпус дополнительным объемом энергии, что можно использовать для различных целей.</p>"},
		"energy_charging_speed_1":        {Name: "Вспомогательный реактор", Description: "<p>Позволяет корпусу быстрее и эффективнее заряжать аккумулятор от главного ториевого реактора.</p>"},
		"power_booster_1":                {Name: "Установка преобразователя", Description: "<p>Устройство поддержки энергетической разновидности. Снижает оказываемое на ториевый реактор давление и перераспределяет энергию, чем в целом повышает его эффективность. Позволяет устанавливать на корпус более мощное снаряжение или оружие.</p>"},
		"body_structure_booster_1":       {Name: "Композитные сплавы", Description: "<p>Распылённые сплавы бронепокрытия, предназначенные для усиления корпуса. Обеспечивают большую прочность транспорта.</p>"},

		"rig_armored":                       {Name: "Модификатор: броня общая", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_explosion":             {Name: "Модификатор: броня от взрыва", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_kinetics":              {Name: "Модификатор: броня от кинетики", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_armored_thermo":                {Name: "Модификатор: броня от термо", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_body_structure_booster":        {Name: "Модификатор: конструкция", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_caterpillars_speed_booster_1":  {Name: "Модификатор: скорость гусениц", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_antigravity_speed_booster_1":   {Name: "Модификатор: скорость антиграва", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_wheels_speed_booster_1":        {Name: "Модификатор: скорость колес", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_radar_booster_1":               {Name: "Модификатор: радар", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_view_booster_1":                {Name: "Модификатор: линзы", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_energy_capacity_1":             {Name: "Модификатор: емкость аккумулятора", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_energy_charging_speed_1":       {Name: "Модификатор: зарядка аккумулятора", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_improved_inventory_capacity_1": {Name: "Модификатор: объем трюма", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_power_booster_1":               {Name: "Модификатор: реактор", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_missile_damage_booster_1":      {Name: "Модификатор: урон ракет", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_laser_damage_booster_1":        {Name: "Модификатор: урон лазера", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_ballistic_damage_booster_1":    {Name: "Модификатор: урон снарядов", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_ballistic_rotate_booster_1":    {Name: "Модификатор: турель баллистики", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_missile_rotate_booster_1":      {Name: "Модификатор: турель пусковой установки", Description: "<p>Модуль уничтожается если его снять!</p>"},
		"rig_laser_rotate_booster_1":        {Name: "Модификатор: турель лазера", Description: "<p>Модуль уничтожается если его снять!</p>"},
	},
}
