package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var RankDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"civil":              {Name: "civil", ID: 0},
		"volunteer":          {Name: "volunteer", ID: 1},
		"rookie":             {Name: "rookie", ID: 2},
		"soldier":            {Name: "soldier", ID: 3},
		"legionary":          {Name: "legionary", ID: 4},
		"veteran":            {Name: "veteran", ID: 5},
		"corporal":           {Name: "corporal", ID: 6},
		"sergeant":           {Name: "sergeant", ID: 7},
		"staff_sergeant":     {Name: "staff_sergeant", ID: 8},
		"lieutenant":         {Name: "lieutenant", ID: 9},
		"captain":            {Name: "captain", ID: 10},
		"major":              {Name: "major", ID: 11},
		"centurion":          {Name: "centurion", ID: 12},
		"colonel":            {Name: "colonel", ID: 13},
		"tribune":            {Name: "tribune", ID: 14},
		"brigadier_general":  {Name: "brigadier_general", ID: 15},
		"prefect":            {Name: "prefect", ID: 16},
		"praetorian":         {Name: "praetorian", ID: 17},
		"palatine":           {Name: "palatine", ID: 18},
		"honored_palatine":   {Name: "honored_palatine", ID: 19},
		"legate":             {Name: "legate", ID: 20},
		"general":            {Name: "general", ID: 21},
		"warlord":            {Name: "warlord", ID: 22},
		"supreme_warlord":    {Name: "supreme_warlord", ID: 23},
		"commander":          {Name: "commander", ID: 24},
		"commander_in_chief": {Name: "commander_in_chief", ID: 25},
	},
	_const.RU: {
		"civil":              {Name: "Гражданский", ID: 0},
		"volunteer":          {Name: "Доброволец", ID: 1},
		"rookie":             {Name: "Новобранец", ID: 2},
		"soldier":            {Name: "Рядовой", ID: 3},
		"legionary":          {Name: "Легионер", ID: 4},
		"veteran":            {Name: "Ветеран", ID: 5},
		"corporal":           {Name: "Капрал", ID: 6},
		"sergeant":           {Name: "Сержант", ID: 7},
		"staff_sergeant":     {Name: "Старший сержант", ID: 8},
		"lieutenant":         {Name: "Лейтенант", ID: 9},
		"captain":            {Name: "Капитан", ID: 10},
		"major":              {Name: "Майор", ID: 11},
		"centurion":          {Name: "Центурион", ID: 12},
		"colonel":            {Name: "Полковник", ID: 13},
		"tribune":            {Name: "Трибун", ID: 14},
		"brigadier_general":  {Name: "Бригадный генерал", ID: 15},
		"prefect":            {Name: "Префект", ID: 16},
		"praetorian":         {Name: "Преторианец", ID: 17},
		"palatine":           {Name: "Палатин", ID: 18},
		"honored_palatine":   {Name: "Заслуженный палатин", ID: 19},
		"legate":             {Name: "Легат", ID: 20},
		"general":            {Name: "Генерал", ID: 21},
		"warlord":            {Name: "Военачальник", ID: 22},
		"supreme_warlord":    {Name: "Верховный военачальник", ID: 23},
		"commander":          {Name: "Полководец", ID: 24},
		"commander_in_chief": {Name: "Главнокомандующий", ID: 25},
	},
	_const.ZhCN: {
		"civil":              {Name: "平民", ID: 0},
		"volunteer":          {Name: "志愿者", ID: 1},
		"rookie":             {Name: "新兵", ID: 2},
		"soldier":            {Name: "列兵", ID: 3},
		"legionary":          {Name: "军团士兵", ID: 4},
		"veteran":            {Name: "老兵", ID: 5},
		"corporal":           {Name: "下士", ID: 6},
		"sergeant":           {Name: "中士", ID: 7},
		"staff_sergeant":     {Name: "上士", ID: 8},
		"lieutenant":         {Name: "少尉", ID: 9},
		"captain":            {Name: "上尉", ID: 10},
		"major":              {Name: "少校", ID: 11},
		"centurion":          {Name: "百夫长", ID: 12},
		"colonel":            {Name: "上校", ID: 13},
		"tribune":            {Name: "护民官", ID: 14},
		"brigadier_general":  {Name: "准将", ID: 15},
		"prefect":            {Name: "长官", ID: 16},
		"praetorian":         {Name: "禁卫军", ID: 17},
		"palatine":           {Name: "帕拉丁", ID: 18},
		"honored_palatine":   {Name: "荣誉帕拉丁", ID: 19},
		"legate":             {Name: "军团指挥官", ID: 20},
		"general":            {Name: "将军", ID: 21},
		"warlord":            {Name: "军阀", ID: 22},
		"supreme_warlord":    {Name: "最高军阀", ID: 23},
		"commander":          {Name: "统帅", ID: 24},
		"commander_in_chief": {Name: "总司令", ID: 25},
	},
}
