package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var ResourceDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"copper_ore":   {Name: "Copper ore", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"iron_ore":     {Name: "Iron ore", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"silicon_ore":  {Name: "Silicon ore", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"thorium_ore":  {Name: "Lithium Ore", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"titanium_ore": {Name: "Titanium ore", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"oil":          {Name: "Oil", Description: "<p>Natural mineral formation containing useful components and suitable for further processing and exploitation. It is obtained by means of special equipment, as well as an engineering structure of the corresponding type.</p>"},
		"organic":      {Name: "Organic", Description: "<p>Remains of photo/radio-autotrophic organisms extracted from the compactions of local unfriendly flora and used in certain production chains.</p>"},
		"spices":       {Name: "Pry", Description: "<p>A sandy substance of a special composition that forms in the core of dust vortices and somehow has a precognitive effect on synthetics.</p>"},
		"disputes_1":   {Name: "Mold of Diomikia High", Description: "<p>One of the varieties of the most common spores on the planet. As a rule, it is obtained randomly during mechanical processing of one or another flora. These spores have been found to be used as synthesized fuel splitters.</p>"},
		"disputes_2":   {Name: "Residual Foam of Ascomitea", Description: "<p>One of the varieties of the most common spores on the planet. As a rule, it is obtained randomly during processing of one or another flora. These spores with a bright acid effect have been found to be used as an anti-corrosion coating.</p>"},
		"resin":        {Name: "Pitch Acid", Description: "<p>A viscous reactive extract that remains after collecting a certain plant on the surface of the planet. This reacting substance has been found to be used as a lubricating and abrasive substance.</p>"},
		"flower":       {Name: "Flower of the Core Bush", Description: "<p>Syncretic plant with an explosive chemical composition. During the onset of a threat to its carrier, the flower shoots its own contact needles in all directions. This plant has been used in the production of explosives.</p>"},
	},
	_const.RU: {
		"copper_ore":   {Name: "Медная руда", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа.</p>"},
		"iron_ore":     {Name: "Железная руда", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа. </p>"},
		"silicon_ore":  {Name: "Кремниевая руда", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа. </p>"},
		"thorium_ore":  {Name: "Литиева руда", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа. </p>"},
		"titanium_ore": {Name: "Титановая руда", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа. </p>"},
		"oil":          {Name: "Нефть", Description: "<p>Природное минеральное образование, содержащее в себе полезные компоненты и пригодное для дальнейшей переработки и, эксплуатации. Добывается посредством специального оборудования, а также инженерного сооружения соответствующего типа.</p>"},
		"organic":      {Name: "Органика", Description: "<p>Остатки фото/радо-автотрофных организмов, добываемых из уплотнений местной недружелюбной флоры и, нашедшей своё применение в определённых производственных цепочках.</p>"},
		"spices":       {Name: "Прай", Description: "<p>Песчаная субстанция особого состава, которая формируется в ядре пылевых вихрей и каким-то образом оказывающая на синтетов прекогниционное влияние.</p>"},
		"disputes_1":   {Name: "Плесень Диомикии Высокой", Description: "<p>Одна из разновидностей наиболее распространённых спор на планете. Как правило добывается случайным образом во время механической обработки той или иной флоры. Данным спорам было найдено применение в виде синтезированных расщепителей топлива.</p>"},
		"disputes_2":   {Name: "Остаточная Пена Аскомитеи", Description: "<p>Одна из разновидностей наиболее распространённых спор на планете. Как правило добывается случайным образом во время обработки той или иной флоры. Данным спорам с ярким кислотным эффектом было найдено применение в виде антикоррозионного напыления.</p>"},
		"resin":        {Name: "Смоляная Кислота", Description: "<p>Вязкий реактивный экстракт, что остаётся после сбора определенного растения на поверхности планеты. Данной вступающей в реакцию субстанции было найдено применение в виде смазочного и абразивного вещества.</p>"},
		"flower":       {Name: "Цветок Ядрового Куста", Description: "<p>Синкретическое растение, обладающее взрывоопасным химическим составом. Во время наступления угрозы своему носителю, цветок выстреливает во все стороны собственные контактные игла. Данному растению было найдено применение при производстве взрывчатых веществ.</p>"},
	},
	_const.ZhCN: {
		"copper_ore":   {Name: "铜矿石", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"iron_ore":     {Name: "铁矿石", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"silicon_ore":  {Name: "硅矿石", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"thorium_ore":  {Name: "锂矿石", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"titanium_ore": {Name: "钛矿石", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"oil":          {Name: "石油", Description: "<p>一种天然矿物，含有有用的成分，适合进一步加工和利用。通过特殊设备和相应类型的工程结构进行开采。</p>"},
		"organic":      {Name: "有机物", Description: "<p>从当地不友好的植物中提取的光合/放射自养生物的残留物，已在某些生产链中找到应用。</p>"},
		"spices":       {Name: "香料", Description: "<p>一种特殊成分的沙质物质，形成于尘埃漩涡的核心，并对合成物产生某种预认知影响。</p>"},
		"disputes_1":   {Name: "高迪奥米基亚霉菌", Description: "<p>星球上最常见的孢子之一。通常在机械处理某些植物时偶然获得。这些孢子已被用于合成燃料分解剂。</p>"},
		"disputes_2":   {Name: "残余阿斯科米特泡沫", Description: "<p>星球上最常见的孢子之一。通常在处理某些植物时偶然获得。这些具有强烈酸性效果的孢子已被用作防腐涂层。</p>"},
		"resin":        {Name: "树脂酸", Description: "<p>一种粘稠的反应性提取物，采集星球表面特定植物后剩余。这种反应性物质已被用作润滑剂和磨料。</p>"},
		"flower":       {Name: "核心灌木花", Description: "<p>一种具有爆炸性化学成分的共生植物。在受到威胁时，花朵会向四周发射接触针。该植物已被用于生产爆炸物。</p>"},
	},
}

var RecycleDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"enriched_thorium": {Name: "Stabilized Lithium", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"copper":           {Name: "Copper", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"iron":             {Name: "Iron", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"plastic":          {Name: "Plastic", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"silicon":          {Name: "Silicon", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"titanium":         {Name: "Titanium", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
		"carbon":           {Name: "Carbon", Description: "<p>A product of the mining industry that has gone through the processing stages and is now suitable for further exploitation - the creation of parts and equipment.</p>"},
	},
	_const.RU: {
		"enriched_thorium": {Name: "Стабилизированый литий", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"copper":           {Name: "Медь", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"iron":             {Name: "Железо", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"plastic":          {Name: "Пластик", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"silicon":          {Name: "Кремний", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"titanium":         {Name: "Титан", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
		"carbon":           {Name: "Углерод", Description: "<p>Продукт добывающей промышленности, что прошёл стадии обработки и теперь, пригоден для дальнейшей эксплуатации – создания деталей и снаряжения.</p>"},
	},
	_const.ZhCN: {
		"enriched_thorium": {Name: "稳定锂", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"copper":           {Name: "铜", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"iron":             {Name: "铁", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"plastic":          {Name: "塑料", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"silicon":          {Name: "硅", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"titanium":         {Name: "钛", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
		"carbon":           {Name: "碳", Description: "<p>采矿业的产品，经过加工阶段，现在适合进一步使用——用于制造零件和设备。</p>"},
	},
}

var DetailDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"electronics":    {Name: "Electronics", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"steel":          {Name: "Steel", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"wire":           {Name: "Wire", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"wires":          {Name: "Cable", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"gear":           {Name: "Gear", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"titanium_plate": {Name: "Titanium plate", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"batteries":      {Name: "Batteries", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"armor_items":    {Name: "Armor items", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
		"carbon_plate":   {Name: "Carbon fiber", Description: "<p>An expensive component used especially in the fine production of high-tech equipment or structures of various types and purposes.</p>"},
	},
	_const.RU: {
		"electronics":    {Name: "Электроника", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"steel":          {Name: "Сталь", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"wire":           {Name: "Проволока", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"wires":          {Name: "Кабель", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"gear":           {Name: "Шестерня", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"titanium_plate": {Name: "Титановая пластина", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"batteries":      {Name: "Батареи", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"armor_items":    {Name: "Элементы брони", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
		"carbon_plate":   {Name: "Углеродное волокно", Description: "<p>Дорогостоящий компонент, который применяется сугубо в тонком производстве высокотехнологичного снаряжения или сооружений разного типа и назначения.</p>"},
	},
	_const.ZhCN: {
		"electronics":    {Name: "电子元件", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"steel":          {Name: "钢", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"wire":           {Name: "导线", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"wires":          {Name: "电缆", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"gear":           {Name: "齿轮", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"titanium_plate": {Name: "钛板", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"batteries":      {Name: "电池", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"armor_items":    {Name: "装甲部件", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
		"carbon_plate":   {Name: "碳纤维", Description: "<p>一种昂贵的组件，专门用于精密制造高科技设备或不同类型和用途的设施。</p>"},
	},
}
