package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var SectorDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"disputed_territory_7": {ID: 29, Name: "Poppy", Description: ""},
		"free_land_8":          {ID: 48, Name: "23-SS", Description: ""},
		"free_land_13":         {ID: 53, Name: "Neot", Description: ""},
		"sector_3":             {ID: 4, Name: "Minga", Description: ""},
		"sector_9":             {ID: 10, Name: "Archimedes", Description: ""},
		"Explores_1":           {ID: 38, Name: "Dey-ra", Description: ""},
		"Explores_3":           {ID: 40, Name: "Yuri", Description: ""},
		"disputed_territory_1": {ID: 23, Name: "Moses", Description: ""},
		"free_land_10":         {ID: 50, Name: "6789-0T", Description: ""},
		"free_land_12":         {ID: 52, Name: "P / L.40", Description: ""},
		"free_land_16":         {ID: 56, Name: "91-CORP", Description: ""},
		"sector_1":             {ID: 2, Name: "Zerkot", Description: ""},
		"sector_4":             {ID: 5, Name: "Stones", Description: ""},
		"sector_5":             {ID: 6, Name: "Murama", Description: ""},
		"sector_6":             {ID: 7, Name: "Suogo", Description: ""},
		"free_land_4":          {ID: 44, Name: "NkO", Description: ""},
		"disputed_territory_2": {ID: 24, Name: "Nuod", Description: ""},
		"disputed_territory_5": {ID: 27, Name: "Hanscon", Description: ""},
		"free_land_15":         {ID: 55, Name: "SaS-13", Description: ""},
		"sector_7":             {ID: 8, Name: "Matte", Description: ""},
		"Explores_2":           {ID: 39, Name: "Alva", Description: ""},
		"free_land_1":          {ID: 41, Name: "Z43", Description: ""},
		"free_land_2":          {ID: 42, Name: "FFA-1", Description: ""},
		"free_land_7":          {ID: 47, Name: "G-0", Description: ""},
		"free_land_11":         {ID: 51, Name: "H-`1000", Description: ""},
		"sector_2":             {ID: 3, Name: "Funiel", Description: ""},
		"sector_8":             {ID: 9, Name: "Telro", Description: ""},
		"Reverses_3":           {ID: 37, Name: "Thalet", Description: ""},
		"disputed_territory_9": {ID: 31, Name: "Bokosa", Description: ""},
		"free_land_6":          {ID: 46, Name: "LV-426", Description: ""},
		"Replic_1":             {ID: 32, Name: "Devion", Description: ""},
		"Replic_3":             {ID: 34, Name: "Vision", Description: ""},
		"disputed_territory_8": {ID: 30, Name: "Andelo", Description: ""},
		"free_land_9":          {ID: 49, Name: "MJkk", Description: ""},
		"disputed_territory_3": {ID: 25, Name: "Mather", Description: ""},
		"free_land_5":          {ID: 45, Name: "21 / 14.0", Description: ""},
		"free_land_14":         {ID: 54, Name: "Ron", Description: ""},
		"free_land_17":         {ID: 57, Name: "J1MO", Description: ""},
		"free_land_3":          {ID: 43, Name: "Deu-C / 21", Description: ""},
		"free_land_18":         {ID: 58, Name: "TEY-5", Description: ""},
		"Replic_2":             {ID: 33, Name: "Solushon", Description: ""},
		"Reverses_1":           {ID: 35, Name: "Chard", Description: ""},
		"Reverses_2":           {ID: 36, Name: "Koshiro", Description: ""},
		"disputed_territory_4": {ID: 26, Name: "Finsch", Description: ""},
		"disputed_territory_6": {ID: 28, Name: "George", Description: ""},
		"unknown_1":            {ID: 72, Name: "Unknown", Description: ""},
		"unknown_2":            {ID: 73, Name: "Unknown", Description: ""},
		"unknown_3":            {ID: 74, Name: "Unknown", Description: ""},
		"Replic_4":             {ID: 75, Name: "Terminus", Description: ""},
		"Replic_5":             {ID: 76, Name: "Cyberon", Description: ""},
		"Replic_6":             {ID: 77, Name: "Vargos", Description: ""},
		"Reverses_4":           {ID: 78, Name: "Evolis", Description: ""},
		"Reverses_5":           {ID: 79, Name: "Kybriss", Description: ""},
		"Reverses_6":           {ID: 80, Name: "Genesis", Description: ""},
		"Explores_4":           {ID: 81, Name: "Novara", Description: ""},
		"Explores_5":           {ID: 82, Name: "Orion", Description: ""},
		"Explores_6":           {ID: 83, Name: "Eos", Description: ""},
		"---":                  {ID: 0, Name: "---", Description: ""},
	},
	_const.RU: {
		"sector_1":             {ID: 2, Name: "Зеркот", Description: ""},
		"sector_2":             {ID: 3, Name: "Фуниёл", Description: ""},
		"sector_3":             {ID: 4, Name: "Минга", Description: ""},
		"sector_4":             {ID: 5, Name: "Стоунс", Description: ""},
		"sector_5":             {ID: 6, Name: "Мурама", Description: ""},
		"sector_6":             {ID: 7, Name: "Суого", Description: ""},
		"sector_7":             {ID: 8, Name: "Штейн", Description: ""},
		"sector_8":             {ID: 9, Name: "Тельро", Description: ""},
		"sector_9":             {ID: 10, Name: "Архимед", Description: ""},
		"Replic_1":             {ID: 32, Name: "Девион", Description: ""},
		"Replic_2":             {ID: 33, Name: "Солюшон", Description: ""},
		"Replic_3":             {ID: 34, Name: "Визион", Description: ""},
		"Reverses_1":           {ID: 35, Name: "Чард", Description: ""},
		"Reverses_2":           {ID: 36, Name: "Коширо", Description: ""},
		"Reverses_3":           {ID: 37, Name: "Фалет", Description: ""},
		"Explores_1":           {ID: 38, Name: "Дей-ра", Description: ""},
		"Explores_2":           {ID: 39, Name: "Алва", Description: ""},
		"Explores_3":           {ID: 40, Name: "Юри", Description: ""},
		"disputed_territory_1": {ID: 23, Name: "Мозес", Description: ""},
		"disputed_territory_2": {ID: 24, Name: "Нуод", Description: ""},
		"disputed_territory_3": {ID: 25, Name: "Мезер", Description: ""},
		"disputed_territory_4": {ID: 26, Name: "Финш", Description: ""},
		"disputed_territory_5": {ID: 27, Name: "Ганскон", Description: ""},
		"disputed_territory_6": {ID: 28, Name: "Джордж", Description: ""},
		"disputed_territory_7": {ID: 29, Name: "Мак", Description: ""},
		"disputed_territory_8": {ID: 30, Name: "Андело", Description: ""},
		"disputed_territory_9": {ID: 31, Name: "Бокоса", Description: ""},
		"free_land_1":          {ID: 41, Name: "Z43", Description: ""},
		"free_land_2":          {ID: 42, Name: "FFA-1", Description: ""},
		"free_land_3":          {ID: 43, Name: "Deu-C/21", Description: ""},
		"free_land_4":          {ID: 44, Name: "NkO", Description: ""},
		"free_land_5":          {ID: 45, Name: "21/14.0", Description: ""},
		"free_land_6":          {ID: 46, Name: "LV-426", Description: ""},
		"free_land_7":          {ID: 47, Name: "G-0", Description: ""},
		"free_land_8":          {ID: 48, Name: "23-SS", Description: ""},
		"free_land_9":          {ID: 49, Name: "MJkk", Description: ""},
		"free_land_10":         {ID: 50, Name: "6789-0T", Description: ""},
		"free_land_11":         {ID: 51, Name: "H-`1000", Description: ""},
		"free_land_12":         {ID: 52, Name: "P/L.40", Description: ""},
		"free_land_13":         {ID: 53, Name: "Neot", Description: ""},
		"free_land_14":         {ID: 54, Name: "Ron", Description: ""},
		"free_land_15":         {ID: 55, Name: "SaS-13", Description: ""},
		"free_land_16":         {ID: 56, Name: "91-CORP", Description: ""},
		"free_land_17":         {ID: 57, Name: "J1MO", Description: ""},
		"free_land_18":         {ID: 58, Name: "TEY-5", Description: ""},
		"unknown_1":            {ID: 72, Name: "Неизвестно", Description: ""},
		"unknown_2":            {ID: 73, Name: "Неизвестно", Description: ""},
		"unknown_3":            {ID: 74, Name: "Неизвестно", Description: ""},
		"Replic_4":             {ID: 75, Name: "Терминус", Description: ""},
		"Replic_5":             {ID: 76, Name: "Киберон", Description: ""},
		"Replic_6":             {ID: 77, Name: "Варгос", Description: ""},
		"Reverses_4":           {ID: 78, Name: "Эволис", Description: ""},
		"Reverses_5":           {ID: 79, Name: "Кибрис", Description: ""},
		"Reverses_6":           {ID: 80, Name: "Генезис", Description: ""},
		"Explores_4":           {ID: 81, Name: "Новара", Description: ""},
		"Explores_5":           {ID: 82, Name: "Орион", Description: ""},
		"Explores_6":           {ID: 83, Name: "Эос", Description: ""},
		"---":                  {ID: 0, Name: "---", Description: ""},
	},
	_const.ZhCN: {
		"disputed_territory_7": {ID: 29, Name: "Poppy", Description: ""},
		"free_land_8":          {ID: 48, Name: "23-SS", Description: ""},
		"free_land_13":         {ID: 53, Name: "Neot", Description: ""},
		"sector_3":             {ID: 4, Name: "Minga", Description: ""},
		"sector_9":             {ID: 10, Name: "Archimedes", Description: ""},
		"Explores_1":           {ID: 38, Name: "Dey-ra", Description: ""},
		"Explores_3":           {ID: 40, Name: "Yuri", Description: ""},
		"disputed_territory_1": {ID: 23, Name: "Moses", Description: ""},
		"free_land_10":         {ID: 50, Name: "6789-0T", Description: ""},
		"free_land_12":         {ID: 52, Name: "P / L.40", Description: ""},
		"free_land_16":         {ID: 56, Name: "91-CORP", Description: ""},
		"sector_1":             {ID: 2, Name: "Zerkot", Description: ""},
		"sector_4":             {ID: 5, Name: "Stones", Description: ""},
		"sector_5":             {ID: 6, Name: "Murama", Description: ""},
		"sector_6":             {ID: 7, Name: "Suogo", Description: ""},
		"free_land_4":          {ID: 44, Name: "NkO", Description: ""},
		"disputed_territory_2": {ID: 24, Name: "Nuod", Description: ""},
		"disputed_territory_5": {ID: 27, Name: "Hanscon", Description: ""},
		"free_land_15":         {ID: 55, Name: "SaS-13", Description: ""},
		"sector_7":             {ID: 8, Name: "Matte", Description: ""},
		"Explores_2":           {ID: 39, Name: "Alva", Description: ""},
		"free_land_1":          {ID: 41, Name: "Z43", Description: ""},
		"free_land_2":          {ID: 42, Name: "FFA-1", Description: ""},
		"free_land_7":          {ID: 47, Name: "G-0", Description: ""},
		"free_land_11":         {ID: 51, Name: "H-`1000", Description: ""},
		"sector_2":             {ID: 3, Name: "Funiel", Description: ""},
		"sector_8":             {ID: 9, Name: "Telro", Description: ""},
		"Reverses_3":           {ID: 37, Name: "Thalet", Description: ""},
		"disputed_territory_9": {ID: 31, Name: "Bokosa", Description: ""},
		"free_land_6":          {ID: 46, Name: "LV-426", Description: ""},
		"Replic_1":             {ID: 32, Name: "Devion", Description: ""},
		"Replic_3":             {ID: 34, Name: "Vision", Description: ""},
		"disputed_territory_8": {ID: 30, Name: "Andelo", Description: ""},
		"free_land_9":          {ID: 49, Name: "MJkk", Description: ""},
		"disputed_territory_3": {ID: 25, Name: "Mather", Description: ""},
		"free_land_5":          {ID: 45, Name: "21 / 14.0", Description: ""},
		"free_land_14":         {ID: 54, Name: "Ron", Description: ""},
		"free_land_17":         {ID: 57, Name: "J1MO", Description: ""},
		"free_land_3":          {ID: 43, Name: "Deu-C / 21", Description: ""},
		"free_land_18":         {ID: 58, Name: "TEY-5", Description: ""},
		"Replic_2":             {ID: 33, Name: "Solushon", Description: ""},
		"Reverses_1":           {ID: 35, Name: "Chard", Description: ""},
		"Reverses_2":           {ID: 36, Name: "Koshiro", Description: ""},
		"disputed_territory_4": {ID: 26, Name: "Finsch", Description: ""},
		"disputed_territory_6": {ID: 28, Name: "George", Description: ""},
		"unknown_1":            {ID: 72, Name: "Unknown", Description: ""},
		"unknown_2":            {ID: 73, Name: "Unknown", Description: ""},
		"unknown_3":            {ID: 74, Name: "Unknown", Description: ""},
		"Replic_4":             {ID: 75, Name: "Terminus", Description: ""},
		"Replic_5":             {ID: 76, Name: "Cyberon", Description: ""},
		"Replic_6":             {ID: 77, Name: "Vargos", Description: ""},
		"Reverses_4":           {ID: 78, Name: "Evolis", Description: ""},
		"Reverses_5":           {ID: 79, Name: "Kybriss", Description: ""},
		"Reverses_6":           {ID: 80, Name: "Genesis", Description: ""},
		"Explores_4":           {ID: 81, Name: "Novara", Description: ""},
		"Explores_5":           {ID: 82, Name: "Orion", Description: ""},
		"Explores_6":           {ID: 83, Name: "Eos", Description: ""},
		"---":                  {ID: 0, Name: "---", Description: ""},
	},
}
