package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var SkillDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"processing":              {Name: "Переработка полезных ископаемых", Description: "<p>Уменьшает потери при переработке.</p>"},
		"processing_copper_ore":   {Name: "Переработка меди", Description: "<p>Уменьшает потери при переработке меди.</p>"},
		"processing_iron_ore":     {Name: "Переработка железа", Description: "<p>Уменьшает потери при переработке железа.</p>"},
		"processing_silicon_ore":  {Name: "Переработка кремния", Description: "<p>Уменьшает потери при переработке кремния.</p>"},
		"processing_thorium_ore":  {Name: "Переработка тория", Description: "<p>Уменьшает потери при переработке тория.</p>"},
		"processing_titanium_ore": {Name: "Переработка титана", Description: "<p>Уменьшает потери при переработке титана.</p>"},
		"processing_oil":          {Name: "Переработка нефти", Description: "<p>Уменьшает потери при переработке нефти.</p>"},
		"processing_organic":      {Name: "Переработка органики", Description: "<p>Уменьшает потери при переработке органики.</p>"},

		"production_time":    {Name: "Организация производства", Description: "<p>Уменьшает время необходимое для создания предметов.</p>"},
		"production_economy": {Name: "Экономия материалов", Description: "<p>Уменьшает кол-во материалов необходимых для производства.</p>"},

		"ore_extract":                {Name: "Эксплуатация буровых лазеров", Description: "<p>Повышает объем добычи буровых лазеров.</p>"},
		"speed_ore_extract":          {Name: "Скорость буровых лазеров", Description: "<p>Повышает скорость добычи буровых лазеров.</p>"},
		"speed_oil_extract":          {Name: "Эксплуатация насосной установки", Description: "<p>Повышает скорость добычи насосов.</p>"},
		"speed_combine_extract":      {Name: "Эксплуатация комбайна", Description: "<p>Повышает эффективность добычи комбайна.</p>"},
		"chance_dismantling_extract": {Name: "Эксплуатация инженерного модуля", Description: "<p>Повышает шанс извлечь детали из обломков.</p>"},
		"saving_energy_dust_extract": {Name: "Эксплуатация сборщика пыли", Description: "<p>Уменьшает затраты энергии сборщика пыли.</p>"},

		// боеприпасы
		"small_ballistic_ammo":  {Name: "Малые баллистические боеприпасы", Description: "<p>Увеличивает урон малых баллистических боеприпасов. </p>"},
		"medium_ballistic_ammo": {Name: "Средние баллистические боеприпасы", Description: "<p>Увеличивает урон средних баллистических боеприпасов. </p>"},
		"big_ballistic_ammo":    {Name: "Большие баллистические боеприпасы", Description: "<p>Увеличивает урон больших баллистических боеприпасов. </p>"},
		"small_laser_ammo":      {Name: "Малые лазерные линзы", Description: "<p>Увеличивает урон малых линз.</p>"},
		"medium_laser_ammo":     {Name: "Средние лазерные линзы", Description: "<p>Увеличивает урон средних линз.</p>"},
		"big_laser_ammo":        {Name: "Большие лазерные линзы", Description: "<p>Увеличивает урон больших линз.</p>"},
		"small_rocket_ammo":     {Name: "Малые ракеты", Description: "<p>Увеличивает урон малых ракет.</p>"},
		"medium_rocket_ammo":    {Name: "Средние ракеты", Description: "<p>Увеличивает урон средних ракет.</p>"},
		"big_rocket_ammo":       {Name: "Большие ракеты", Description: "<p>Увеличивает урон больших ракет.</p>"},

		// оружие
		"small_ballistic_weapon":           {Name: "Малые баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых баллистических орудий. </p>"},
		"medium_ballistic_weapon":          {Name: "Средние баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних баллистических орудий. </p>"},
		"big_ballistic_weapon":             {Name: "Большие баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших баллистических орудий. </p>"},
		"small_laser_weapon":               {Name: "Малые лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых лазерных орудий. </p>"},
		"medium_laser_weapon":              {Name: "Средние лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних лазерных орудий. </p>"},
		"big_laser_weapon":                 {Name: "Большие лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших лазерных орудий. </p>"},
		"small_rocket_weapon":              {Name: "Малые пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых пусковых установок.</p>"},
		"medium_rocket_weapon":             {Name: "Средние пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних пусковых установок.</p>"},
		"big_rocket_weapon":                {Name: "Большие пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших пусковых установок.</p>"},
		"rotate_small_ballistic_weapon":    {Name: "Скорость поворота малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых баллистических орудий.</p>"},
		"rotate_medium_ballistic_weapon":   {Name: "Скорость поворота средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних баллистических орудий.</p>"},
		"rotate_big_ballistic_weapon":      {Name: "Скорость поворота больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших баллистических орудий.</p>"},
		"rotate_small_laser_weapon":        {Name: "Скорость поворота малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых лазерных орудий.</p>"},
		"rotate_medium_laser_weapon":       {Name: "Скорость поворота средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних лазерных орудий.</p>"},
		"rotate_big_laser_weapon":          {Name: "Скорость поворота больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших лазерных орудий.</p>"},
		"rotate_small_rocket_weapon":       {Name: "Скорость поворота малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых пусковых установок.</p>"},
		"rotate_medium_rocket_weapon":      {Name: "Скорость поворота средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних пусковых установок.</p>"},
		"rotate_big_rocket_weapon":         {Name: "Скорость поворота больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших пусковых установок.</p>"},
		"accuracy_small_ballistic_weapon":  {Name: "Точность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых баллистических орудий.</p>"},
		"accuracy_medium_ballistic_weapon": {Name: "Точность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних баллистических орудий.</p>"},
		"accuracy_big_ballistic_weapon":    {Name: "Точность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших баллистических орудий.</p>"},
		"accuracy_small_laser_weapon":      {Name: "Точность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых лазерных орудий.</p>"},
		"accuracy_medium_laser_weapon":     {Name: "Точность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних лазерных орудий.</p>"},
		"accuracy_big_laser_weapon":        {Name: "Точность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших лазерных орудий.</p>"},
		"accuracy_small_rocket_weapon":     {Name: "Точность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых пусковых установок.</p>"},
		"accuracy_medium_rocket_weapon":    {Name: "Точность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних пусковых установок.</p>"},
		"accuracy_big_rocket_weapon":       {Name: "Точность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших пусковых установок.</p>"},
		"rate_small_ballistic_weapon":      {Name: "Скорострельность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых баллистических орудий.</p>"},
		"rate_medium_ballistic_weapon":     {Name: "Скорострельность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних баллистических орудий.</p>"},
		"rate_big_ballistic_weapon":        {Name: "Скорострельность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших баллистических орудий.</p>"},
		"rate_small_laser_weapon":          {Name: "Скорострельность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых лазерных орудий.</p>"},
		"rate_medium_laser_weapon":         {Name: "Скорострельность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних лазерных орудий.</p>"},
		"rate_big_laser_weapon":            {Name: "Скорострельность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших лазерных орудий.</p>"},
		"rate_small_rocket_weapon":         {Name: "Скорострельность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых пусковых установок.</p>"},
		"rate_medium_rocket_weapon":        {Name: "Скорострельность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних пусковых установок.</p>"},
		"rate_big_rocket_weapon":           {Name: "Скорострельность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших пусковых установок.</p>"},

		// корпуса
		"move_small_explores_body":      {Name: "Управление легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_replics_body":       {Name: "Управление легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_reverses_body":      {Name: "Управление легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_explores_body":     {Name: "Управление средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_replics_body":      {Name: "Управление средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_reverses_body":     {Name: "Управление средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_explores_body":        {Name: "Управление тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_replics_body":         {Name: "Управление тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_reverses_body":        {Name: "Управление тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"armor_small_explores_body":     {Name: "Системы защиты легких корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_replics_body":      {Name: "Системы защиты легких корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_reverses_body":     {Name: "Системы защиты легких корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_explores_body":    {Name: "Системы защиты средних корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_replics_body":     {Name: "Системы защиты средних корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_reverses_body":    {Name: "Системы защиты средних корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_explores_body":       {Name: "Системы защиты тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_replics_body":        {Name: "Системы защиты тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_reverses_body":       {Name: "Системы защиты тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"view_small_explores_body":      {Name: "Использование оптики легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_explores_body":     {Name: "Использование оптики средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_explores_body":        {Name: "Использование оптики тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_replics_body":       {Name: "Использование оптики легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_replics_body":      {Name: "Использование оптики средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_replics_body":         {Name: "Использование оптики тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_reverses_body":      {Name: "Использование оптики легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_reverses_body":     {Name: "Использование оптики средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_reverses_body":        {Name: "Использование оптики тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"powercap_small_explores_body":  {Name: "Использование аккумулятора легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_explores_body": {Name: "Использование аккумулятора средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_explores_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_replics_body":   {Name: "Использование аккумулятора легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_replics_body":  {Name: "Использование аккумулятора средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_replics_body":     {Name: "Использование аккумулятора тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_reverses_body":  {Name: "Использование аккумулятора легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_reverses_body": {Name: "Использование аккумулятора средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_reverses_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"radar_small_explores_body":     {Name: "Разведка легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_explores_body":    {Name: "Разведка средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_explores_body":       {Name: "Разведка тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_replics_body":      {Name: "Разведка легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_replics_body":     {Name: "Разведка средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_replics_body":        {Name: "Разведка тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_reverses_body":     {Name: "Разведка легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_reverses_body":    {Name: "Разведка средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_reverses_body":       {Name: "Разведка тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"charging_small_explores_body":  {Name: "Энергосеть легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_explores_body": {Name: "Энергосеть средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_explores_body":    {Name: "Энергосеть тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_replics_body":   {Name: "Энергосеть легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_replics_body":  {Name: "Энергосеть средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_replics_body":     {Name: "Энергосеть тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_reverses_body":  {Name: "Энергосеть легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_reverses_body": {Name: "Энергосеть средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_reverses_body":    {Name: "Энергосеть тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"replics_hauler":                {Name: "Грузоперевозки \"Replic\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"explores_hauler":               {Name: "Грузоперевозки \"Explores\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"reverses_hauler":               {Name: "Грузоперевозки \"Reverses\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"speed_small_explores_body":     {Name: "Скорость легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_replics_body":      {Name: "Скорость легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_reverses_body":     {Name: "Скорость легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_explores_body":    {Name: "Скорость средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_replics_body":     {Name: "Скорость средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_reverses_body":    {Name: "Скорость средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_explores_body":       {Name: "Скорость тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_replics_body":        {Name: "Скорость тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_reverses_body":       {Name: "Скорость тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"industrial_transport":          {Name: "Управление промышленных корпусов", Description: "<p>Базовый навык владения промышленными корпусами.</p>"},
		"xeno_transport":                {Name: "Управление Ксенокорпусов", Description: "<p>Базовый навык владения Ксенокорпусами.</p>"},
	},
	_const.RU: {
		"processing":              {Name: "Переработка полезных ископаемых", Description: "<p>Уменьшает потери при переработке.</p>"},
		"processing_copper_ore":   {Name: "Переработка меди", Description: "<p>Уменьшает потери при переработке меди.</p>"},
		"processing_iron_ore":     {Name: "Переработка железа", Description: "<p>Уменьшает потери при переработке железа.</p>"},
		"processing_silicon_ore":  {Name: "Переработка кремния", Description: "<p>Уменьшает потери при переработке кремния.</p>"},
		"processing_thorium_ore":  {Name: "Переработка тория", Description: "<p>Уменьшает потери при переработке тория.</p>"},
		"processing_titanium_ore": {Name: "Переработка титана", Description: "<p>Уменьшает потери при переработке титана.</p>"},
		"processing_oil":          {Name: "Переработка нефти", Description: "<p>Уменьшает потери при переработке нефти.</p>"},
		"processing_organic":      {Name: "Переработка органики", Description: "<p>Уменьшает потери при переработке органики.</p>"},

		"ore_extract":                {Name: "Эксплуатация буровых лазеров", Description: "<p>Повышает объем добычи буровых лазеров.</p>"},
		"speed_ore_extract":          {Name: "Скорость буровых лазеров", Description: "<p>Повышает скорость добычи буровых лазеров.</p>"},
		"speed_oil_extract":          {Name: "Эксплуатация насосной установки", Description: "<p>Повышает скорость добычи насосов.</p>"},
		"speed_combine_extract":      {Name: "Эксплуатация комбайна", Description: "<p>Повышает эффективность добычи комбайна.</p>"},
		"chance_dismantling_extract": {Name: "Эксплуатация инженерного модуля", Description: "<p>Повышает шанс извлечь детали из обломков.</p>"},
		"saving_energy_dust_extract": {Name: "Эксплуатация сборщика пыли", Description: "<p>Уменьшает затраты энергии сборщика пыли.</p>"},

		// боеприпасы
		"small_ballistic_ammo":  {Name: "Малые баллистические боеприпасы", Description: "<p>Увеличивает урон малых баллистических боеприпасов. </p>"},
		"medium_ballistic_ammo": {Name: "Средние баллистические боеприпасы", Description: "<p>Увеличивает урон средних баллистических боеприпасов. </p>"},
		"big_ballistic_ammo":    {Name: "Большие баллистические боеприпасы", Description: "<p>Увеличивает урон больших баллистических боеприпасов. </p>"},
		"small_laser_ammo":      {Name: "Малые лазерные линзы", Description: "<p>Увеличивает урон малых линз.</p>"},
		"medium_laser_ammo":     {Name: "Средние лазерные линзы", Description: "<p>Увеличивает урон средних линз.</p>"},
		"big_laser_ammo":        {Name: "Большие лазерные линзы", Description: "<p>Увеличивает урон больших линз.</p>"},
		"small_rocket_ammo":     {Name: "Малые ракеты", Description: "<p>Увеличивает урон малых ракет.</p>"},
		"medium_rocket_ammo":    {Name: "Средние ракеты", Description: "<p>Увеличивает урон средних ракет.</p>"},
		"big_rocket_ammo":       {Name: "Большие ракеты", Description: "<p>Увеличивает урон больших ракет.</p>"},

		// оружие
		"small_ballistic_weapon":           {Name: "Малые баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых баллистических орудий. </p>"},
		"medium_ballistic_weapon":          {Name: "Средние баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних баллистических орудий. </p>"},
		"big_ballistic_weapon":             {Name: "Большие баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших баллистических орудий. </p>"},
		"small_laser_weapon":               {Name: "Малые лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых лазерных орудий. </p>"},
		"medium_laser_weapon":              {Name: "Средние лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних лазерных орудий. </p>"},
		"big_laser_weapon":                 {Name: "Большие лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших лазерных орудий. </p>"},
		"small_rocket_weapon":              {Name: "Малые пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых пусковых установок.</p>"},
		"medium_rocket_weapon":             {Name: "Средние пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних пусковых установок.</p>"},
		"big_rocket_weapon":                {Name: "Большие пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших пусковых установок.</p>"},
		"rotate_small_ballistic_weapon":    {Name: "Скорость поворота малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых баллистических орудий.</p>"},
		"rotate_medium_ballistic_weapon":   {Name: "Скорость поворота средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних баллистических орудий.</p>"},
		"rotate_big_ballistic_weapon":      {Name: "Скорость поворота больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших баллистических орудий.</p>"},
		"rotate_small_laser_weapon":        {Name: "Скорость поворота малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых лазерных орудий.</p>"},
		"rotate_medium_laser_weapon":       {Name: "Скорость поворота средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних лазерных орудий.</p>"},
		"rotate_big_laser_weapon":          {Name: "Скорость поворота больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших лазерных орудий.</p>"},
		"rotate_small_rocket_weapon":       {Name: "Скорость поворота малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых пусковых установок.</p>"},
		"rotate_medium_rocket_weapon":      {Name: "Скорость поворота средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних пусковых установок.</p>"},
		"rotate_big_rocket_weapon":         {Name: "Скорость поворота больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших пусковых установок.</p>"},
		"accuracy_small_ballistic_weapon":  {Name: "Точность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых баллистических орудий.</p>"},
		"accuracy_medium_ballistic_weapon": {Name: "Точность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних баллистических орудий.</p>"},
		"accuracy_big_ballistic_weapon":    {Name: "Точность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших баллистических орудий.</p>"},
		"accuracy_small_laser_weapon":      {Name: "Точность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых лазерных орудий.</p>"},
		"accuracy_medium_laser_weapon":     {Name: "Точность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних лазерных орудий.</p>"},
		"accuracy_big_laser_weapon":        {Name: "Точность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших лазерных орудий.</p>"},
		"accuracy_small_rocket_weapon":     {Name: "Точность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых пусковых установок.</p>"},
		"accuracy_medium_rocket_weapon":    {Name: "Точность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних пусковых установок.</p>"},
		"accuracy_big_rocket_weapon":       {Name: "Точность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших пусковых установок.</p>"},
		"rate_small_ballistic_weapon":      {Name: "Скорострельность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых баллистических орудий.</p>"},
		"rate_medium_ballistic_weapon":     {Name: "Скорострельность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних баллистических орудий.</p>"},
		"rate_big_ballistic_weapon":        {Name: "Скорострельность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших баллистических орудий.</p>"},
		"rate_small_laser_weapon":          {Name: "Скорострельность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых лазерных орудий.</p>"},
		"rate_medium_laser_weapon":         {Name: "Скорострельность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних лазерных орудий.</p>"},
		"rate_big_laser_weapon":            {Name: "Скорострельность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших лазерных орудий.</p>"},
		"rate_small_rocket_weapon":         {Name: "Скорострельность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых пусковых установок.</p>"},
		"rate_medium_rocket_weapon":        {Name: "Скорострельность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних пусковых установок.</p>"},
		"rate_big_rocket_weapon":           {Name: "Скорострельность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших пусковых установок.</p>"},

		// корпуса
		"move_small_explores_body":      {Name: "Управление легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_replics_body":       {Name: "Управление легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_reverses_body":      {Name: "Управление легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_explores_body":     {Name: "Управление средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_replics_body":      {Name: "Управление средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_reverses_body":     {Name: "Управление средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_explores_body":        {Name: "Управление тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_replics_body":         {Name: "Управление тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_reverses_body":        {Name: "Управление тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"armor_small_explores_body":     {Name: "Системы защиты легких корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_replics_body":      {Name: "Системы защиты легких корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_reverses_body":     {Name: "Системы защиты легких корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_explores_body":    {Name: "Системы защиты средних корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_replics_body":     {Name: "Системы защиты средних корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_reverses_body":    {Name: "Системы защиты средних корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_explores_body":       {Name: "Системы защиты тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_replics_body":        {Name: "Системы защиты тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_reverses_body":       {Name: "Системы защиты тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"view_small_explores_body":      {Name: "Использование оптики легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_explores_body":     {Name: "Использование оптики средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_explores_body":        {Name: "Использование оптики тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_replics_body":       {Name: "Использование оптики легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_replics_body":      {Name: "Использование оптики средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_replics_body":         {Name: "Использование оптики тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_reverses_body":      {Name: "Использование оптики легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_reverses_body":     {Name: "Использование оптики средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_reverses_body":        {Name: "Использование оптики тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"powercap_small_explores_body":  {Name: "Использование аккумулятора легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_explores_body": {Name: "Использование аккумулятора средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_explores_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_replics_body":   {Name: "Использование аккумулятора легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_replics_body":  {Name: "Использование аккумулятора средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_replics_body":     {Name: "Использование аккумулятора тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_reverses_body":  {Name: "Использование аккумулятора легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_reverses_body": {Name: "Использование аккумулятора средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_reverses_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"radar_small_explores_body":     {Name: "Разведка легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_explores_body":    {Name: "Разведка средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_explores_body":       {Name: "Разведка тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_replics_body":      {Name: "Разведка легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_replics_body":     {Name: "Разведка средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_replics_body":        {Name: "Разведка тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_reverses_body":     {Name: "Разведка легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_reverses_body":    {Name: "Разведка средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_reverses_body":       {Name: "Разведка тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"charging_small_explores_body":  {Name: "Энергосеть легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_explores_body": {Name: "Энергосеть средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_explores_body":    {Name: "Энергосеть тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_replics_body":   {Name: "Энергосеть легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_replics_body":  {Name: "Энергосеть средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_replics_body":     {Name: "Энергосеть тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_reverses_body":  {Name: "Энергосеть легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_reverses_body": {Name: "Энергосеть средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_reverses_body":    {Name: "Энергосеть тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"replics_hauler":                {Name: "Грузоперевозки \"Replic\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"explores_hauler":               {Name: "Грузоперевозки \"Explores\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"reverses_hauler":               {Name: "Грузоперевозки \"Reverses\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"speed_small_explores_body":     {Name: "Скорость легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_replics_body":      {Name: "Скорость легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_reverses_body":     {Name: "Скорость легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_explores_body":    {Name: "Скорость средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_replics_body":     {Name: "Скорость средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_reverses_body":    {Name: "Скорость средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_explores_body":       {Name: "Скорость тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_replics_body":        {Name: "Скорость тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_reverses_body":       {Name: "Скорость тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"industrial_transport":          {Name: "Управление промышленных корпусов", Description: "<p>Базовый навык владения промышленными корпусами.</p>"},
		"xeno_transport":                {Name: "Управление Ксенокорпусов", Description: "<p>Базовый навык владения Ксенокорпусами.</p>"},
	},
}
