package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var SkillDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"processing":              {Name: "Processing of minerals", Description: "<p>Reduces losses during processing.</p>"},
		"processing_copper_ore":   {Name: "Copper processing", Description: "<p>Reduces losses when processing copper.</p>"},
		"processing_iron_ore":     {Name: "Iron processing", Description: "<p>Reduces losses when processing iron.</p>"},
		"processing_silicon_ore":  {Name: "Silicon processing", Description: "<p>Reduces losses when processing silicon.</p>"},
		"processing_thorium_ore":  {Name: "Thorium processing", Description: "<p>Reduces losses when processing thorium.</p>"},
		"processing_titanium_ore": {Name: "Titanium processing", Description: "<p>Reduces losses when processing titanium.</p>"},
		"processing_oil":          {Name: "Oil processing", Description: "<p>Reduces losses when processing oil.</p>"},
		"processing_organic":      {Name: "Organic processing", Description: "<p>Reduces losses when processing organic materials.</p>"},

		"production_time":       {Name: "Production organization", Description: "<p>Reduces the time required to create items.</p>"},
		"production_economy":    {Name: "Material savings", Description: "<p>Reduces the amount of materials needed for production.</p>"},
		"ore_extract":           {Name: "Drill laser operation", Description: "<p>Increases the volume of drill laser mining.</p>"},
		"speed_ore_extract":     {Name: "Speed of drilling lasers", Description: "<p>Increases the speed of drill laser extraction.</p>"},
		"speed_oil_extract":     {Name: "Operation of the pumping unit", Description: "<p>Increases the speed of pump extraction.</p>"},
		"speed_combine_extract": {Name: "Combine operation", Description: "<p>Improves combine mining efficiency.</p>"},

		"chance_dismantling_extract": {Name: "Engineering module operation", Description: "<p>Increases the chance of extracting parts from debris.</p>"},
		"saving_energy_dust_extract": {Name: "Dust collector operation", Description: "<p>Reduces energy consumption of the dust collector.</p>"},

		// боеприпасы
		"small_ballistic_ammo":  {Name: "Small ballistic ammunition", Description: "<p>Increases the damage of small ballistic ammunition.</p>"},
		"medium_ballistic_ammo": {Name: "Medium ballistic ammunition", Description: "<p>Increases the damage of medium ballistic ammunition.</p>"},
		"big_ballistic_ammo":    {Name: "Large ballistic ammunition", Description: "<p>Increases the damage of large ballistic ammunition.</p>"},
		"small_laser_ammo":      {Name: "Small laser lenses", Description: "<p>Increases the damage of small lenses.</p>"},
		"medium_laser_ammo":     {Name: "Medium laser lenses", Description: "<p>Increases the damage of medium lenses.</p>"},
		"big_laser_ammo":        {Name: "Big laser lenses", Description: "<p>Increases the damage of big lenses.</p>"},
		"small_rocket_ammo":     {Name: "Small rockets", Description: "<p>Increases the damage of small rockets.</p>"},
		"medium_rocket_ammo":    {Name: "Medium rockets", Description: "<p>Increases the damage of medium rockets.</p>"},
		"big_rocket_ammo":       {Name: "Large rockets", Description: "<p>Increases the damage of large rockets.</p>"},

		// оружие
		"small_ballistic_weapon":           {Name: "Small ballistic weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of small ballistic weapons.</p>"},
		"medium_ballistic_weapon":          {Name: "Medium ballistic weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of medium ballistic weapons.</p>"},
		"big_ballistic_weapon":             {Name: "Large ballistic weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of large ballistic weapons.</p>"},
		"small_laser_weapon":               {Name: "Small laser weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of small laser weapons.</p>"},
		"medium_laser_weapon":              {Name: "Medium laser weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of medium laser weapons.</p>"},
		"big_laser_weapon":                 {Name: "Large laser weapons", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of large laser weapons.</p>"},
		"small_rocket_weapon":              {Name: "Small launchers", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of small launchers.</p>"},
		"medium_rocket_weapon":             {Name: "Medium launchers", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of medium launchers.</p>"},
		"big_rocket_weapon":                {Name: "Large launchers", Description: "<p>Reduces the <span class=\"importantly\">reloading time</span> of large launchers.</p>"},
		"rotate_small_ballistic_weapon":    {Name: "Rotation speed of small ballistic weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of small ballistic weapons.</p>"},
		"rotate_medium_ballistic_weapon":   {Name: "Rotation speed of medium ballistic weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of medium ballistic weapons.</p>"},
		"rotate_big_ballistic_weapon":      {Name: "Rotation speed of big ballistic weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of big ballistic weapons.</p>"},
		"rotate_small_laser_weapon":        {Name: "Rotation speed of small laser weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of small laser weapons.</p>"},
		"rotate_medium_laser_weapon":       {Name: "Rotation speed of medium laser weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of medium laser weapons.</p>"},
		"rotate_big_laser_weapon":          {Name: "Rotation speed of big laser weapons", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of big laser weapons.</p>"},
		"rotate_small_rocket_weapon":       {Name: "Rotation speed of small launchers", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of small launchers.</p>"},
		"rotate_medium_rocket_weapon":      {Name: "Rotation speed of medium launchers", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of medium launchers.</p>"},
		"rotate_big_rocket_weapon":         {Name: "Rotation speed of big launchers", Description: "<p>Increases the <span class=\"importantly\">rotation speed</span> of big launchers.</p>"},
		"accuracy_small_ballistic_weapon":  {Name: "Accuracy of small ballistic weapons", Description: "<p>Improves the <span class=\"importantly\">accuracy</span> of small ballistic weapons.</p>"},
		"accuracy_medium_ballistic_weapon": {Name: "Accuracy of medium ballistic weapons", Description: "<p>Improves the <span class=\"importantly\">accuracy</span> of medium ballistic weapons.</p>"},
		"accuracy_big_ballistic_weapon":    {Name: "Accuracy of large ballistic weapons", Description: "<p>Increases the <span class=\"importantly\">accuracy</span> of large ballistic weapons.</p>"},
		"accuracy_small_laser_weapon":      {Name: "Accuracy of small laser weapons", Description: "<p>Improves the <span class=\"importantly\">accuracy</span> of small laser weapons.</p>"},
		"accuracy_medium_laser_weapon":     {Name: "Accuracy of medium laser weapons", Description: "<p>Improves the <span class=\"importantly\">accuracy</span> of medium laser weapons.</p>"},
		"accuracy_big_laser_weapon":        {Name: "Accuracy of big laser weapons", Description: "<p>Improves the <span class=\"importantly\">accuracy</span> of big laser weapons.</p>"},
		"accuracy_small_rocket_weapon":     {Name: "Accuracy of Small Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">accuracy</span> of small rocket launchers.</p>"},
		"accuracy_medium_rocket_weapon":    {Name: "Accuracy of Medium Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">accuracy</span> of medium rocket launchers.</p>"},
		"accuracy_big_rocket_weapon":       {Name: "Accuracy of Large Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">accuracy</span> of large rocket launchers.</p>"},
		"rate_small_ballistic_weapon":      {Name: "Rate of Fire of Small Ballistic Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of small ballistic weapons.</p>"},
		"rate_medium_ballistic_weapon":     {Name: "Rate of Fire of Medium Ballistic Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of medium ballistic weapons.</p>"},
		"rate_big_ballistic_weapon":        {Name: "Rate of Fire of Large Ballistic Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of large ballistic weapons.</p>"},
		"rate_small_laser_weapon":          {Name: "Rate of Fire of Small Laser Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of small laser weapons.</p>"},
		"rate_medium_laser_weapon":         {Name: "Rate of Fire of Medium Laser Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of medium laser weapons.</p>"},
		"rate_big_laser_weapon":            {Name: "Rate of Fire of Large Laser Weapons", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of large laser weapons.</p>"},
		"rate_small_rocket_weapon":         {Name: "Rate of Fire of Small Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of small rocket launchers.</p>"},
		"rate_medium_rocket_weapon":        {Name: "Rate of Fire of Medium Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of medium rocket launchers.</p>"},
		"rate_big_rocket_weapon":           {Name: "Rate of Fire of Large Rocket Launchers", Description: "<p>Increases the <span class=\"importantly\">rate of fire</span> of large rocket launchers.</p>"},

		// корпуса
		"move_small_explores_body":      {Name: "Control of Light \"Explores\" Bodies", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the body.</p>"},
		"move_small_replics_body":       {Name: "Control of Light \"Replic\" Bodies", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the body.</p>"},
		"move_small_reverses_body":      {Name: "Control of Light \"Reverses\" Bodies", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the body.</p>"},
		"move_medium_explores_body":     {Name: "Control of Medium \"Explores\" Bodies", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the body.</p>"},
		"move_medium_replics_body":      {Name: "Control of medium \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the hull.</p>"},
		"move_medium_reverses_body":     {Name: "Control of medium \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the hull.</p>"},
		"move_big_explores_body":        {Name: "Control of heavy \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the hull.</p>"},
		"move_big_replics_body":         {Name: "Control of heavy \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the hull.</p>"},
		"move_big_reverses_body":        {Name: "Control of heavy \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">turning speed</span> of the hull.</p>"},
		"armor_small_explores_body":     {Name: "Protection systems for light \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_small_replics_body":      {Name: "Protection systems for light \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_small_reverses_body":     {Name: "Protection systems for light \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_medium_explores_body":    {Name: "Protection systems for medium \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_medium_replics_body":     {Name: "Protection systems for medium \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_medium_reverses_body":    {Name: "Protection systems for medium \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_big_explores_body":       {Name: "Protection systems for heavy \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_big_replics_body":        {Name: "Protection systems for heavy \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"armor_big_reverses_body":       {Name: "Protection systems for heavy \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">protection</span> rating of the hull.</p>"},
		"view_small_explores_body":      {Name: "Optics systems for light \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_medium_explores_body":     {Name: "Optics systems for medium \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_big_explores_body":        {Name: "Optics systems for heavy \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_small_replics_body":       {Name: "Optics systems for light \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_medium_replics_body":      {Name: "Optics systems for medium \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_big_replics_body":         {Name: "Optics systems for heavy \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_small_reverses_body":      {Name: "Optics systems for light \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_medium_reverses_body":     {Name: "Optics systems for medium \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"view_big_reverses_body":        {Name: "Optics systems for heavy \"Reverses\" hulls", Description: "<p>Increases the <span class=\"importantly\">range of vision</span> of the hull.</p>"},
		"powercap_small_explores_body":  {Name: "Battery systems for light \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the hull.</p>"},
		"powercap_medium_explores_body": {Name: "Battery systems for medium \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the hull.</p>"},
		"powercap_big_explores_body":    {Name: "Battery systems for heavy \"Explores\" hulls", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the hull.</p>"},
		"powercap_small_replics_body":   {Name: "Battery systems for light \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the hull.</p>"},
		"powercap_medium_replics_body":  {Name: "Battery systems for medium \"Replic\" hulls", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the hull.</p>"},
		"powercap_big_replics_body":     {Name: "Using the battery of heavy \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the case.</p>"},
		"powercap_small_reverses_body":  {Name: "Using the battery of light \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the case.</p>"},
		"powercap_medium_reverses_body": {Name: "Using the battery of medium \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the case.</p>"},
		"powercap_big_reverses_body":    {Name: "Using the battery of heavy \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery capacity</span> of the case.</p>"},
		"radar_small_explores_body":     {Name: "Exploration of light \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_medium_explores_body":    {Name: "Exploration of medium \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_big_explores_body":       {Name: "Exploration of heavy \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_small_replics_body":      {Name: "Exploration of light \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_medium_replics_body":     {Name: "Exploration of medium \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_big_replics_body":        {Name: "Exploration of heavy \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_small_reverses_body":     {Name: "Exploration of light \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_medium_reverses_body":    {Name: "Exploration of medium \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"radar_big_reverses_body":       {Name: "Exploration of heavy \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">radar range</span> of the case.</p>"},
		"charging_small_explores_body":  {Name: "Energy network of light \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_medium_explores_body": {Name: "Energy network of medium \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_big_explores_body":    {Name: "Energy network of heavy \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_small_replics_body":   {Name: "Energy network of light \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_medium_replics_body":  {Name: "Energy network of medium \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_big_replics_body":     {Name: "Energy network of heavy \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_small_reverses_body":  {Name: "Energy network of light \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_medium_reverses_body": {Name: "Energy network of medium \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"charging_big_reverses_body":    {Name: "Energy network of heavy \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">battery charging speed</span> of the case.</p>"},
		"replics_hauler":                {Name: "Cargo transportation \"Replic\"", Description: "<p>Basic skill of hauler driving.</p>"},
		"explores_hauler":               {Name: "Cargo transportation \"Explores\"", Description: "<p>Basic skill of hauler driving.</p>"},
		"reverses_hauler":               {Name: "Cargo transportation \"Reverses\"", Description: "<p>Basic skill of hauler driving.</p>"},
		"speed_small_explores_body":     {Name: "Speed of light \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_small_replics_body":      {Name: "Speed of light \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_small_reverses_body":     {Name: "Speed of light \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_medium_explores_body":    {Name: "Speed of medium \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_medium_replics_body":     {Name: "Speed of medium \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_medium_reverses_body":    {Name: "Speed of medium \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_big_explores_body":       {Name: "Speed of heavy \"Explores\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_big_replics_body":        {Name: "Speed of heavy \"Replic\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"speed_big_reverses_body":       {Name: "Speed of heavy \"Reverses\" cases", Description: "<p>Increases the <span class=\"importantly\">maximum speed</span> and <span class=\"importantly\">acceleration speed</span> of the case.</p>"},
		"industrial_transport":          {Name: "Industrial transport", Description: "<p>Basic skill of industrial hulls driving.</p>"},
		"xeno_transport":                {Name: "Xeno transport", Description: "<p>Basic skill of Xenohulls driving.</p>"},
	},
	_const.RU: {
		"processing":              {Name: "Переработка полезных ископаемых", Description: "<p>Уменьшает потери при переработке.</p>"},
		"processing_copper_ore":   {Name: "Переработка меди", Description: "<p>Уменьшает потери при переработке меди.</p>"},
		"processing_iron_ore":     {Name: "Переработка железа", Description: "<p>Уменьшает потери при переработке железа.</p>"},
		"processing_silicon_ore":  {Name: "Переработка кремния", Description: "<p>Уменьшает потери при переработке кремния.</p>"},
		"processing_thorium_ore":  {Name: "Переработка тория", Description: "<p>Уменьшает потери при переработке тория.</p>"},
		"processing_titanium_ore": {Name: "Переработка титана", Description: "<p>Уменьшает потери при переработке титана.</p>"},
		"processing_oil":          {Name: "Переработка нефти", Description: "<p>Уменьшает потери при переработке нефти.</p>"},
		"processing_organic":      {Name: "Переработка органики", Description: "<p>Уменьшает потери при переработке органики.</p>"},

		"production_time":    {Name: "Организация производства", Description: "<p>Уменьшает время необходимое для создания предметов.</p>"},
		"production_economy": {Name: "Экономия материалов", Description: "<p>Уменьшает кол-во материалов необходимых для производства.</p>"},

		"ore_extract":                {Name: "Эксплуатация буровых лазеров", Description: "<p>Повышает объем добычи буровых лазеров.</p>"},
		"speed_ore_extract":          {Name: "Скорость буровых лазеров", Description: "<p>Повышает скорость добычи буровых лазеров.</p>"},
		"speed_oil_extract":          {Name: "Эксплуатация насосной установки", Description: "<p>Повышает скорость добычи насосов.</p>"},
		"speed_combine_extract":      {Name: "Эксплуатация комбайна", Description: "<p>Повышает эффективность добычи комбайна.</p>"},
		"chance_dismantling_extract": {Name: "Эксплуатация инженерного модуля", Description: "<p>Повышает шанс извлечь детали из обломков.</p>"},
		"saving_energy_dust_extract": {Name: "Эксплуатация сборщика пыли", Description: "<p>Уменьшает затраты энергии сборщика пыли.</p>"},

		// боеприпасы
		"small_ballistic_ammo":  {Name: "Малые баллистические боеприпасы", Description: "<p>Увеличивает урон малых баллистических боеприпасов. </p>"},
		"medium_ballistic_ammo": {Name: "Средние баллистические боеприпасы", Description: "<p>Увеличивает урон средних баллистических боеприпасов. </p>"},
		"big_ballistic_ammo":    {Name: "Большие баллистические боеприпасы", Description: "<p>Увеличивает урон больших баллистических боеприпасов. </p>"},
		"small_laser_ammo":      {Name: "Малые лазерные линзы", Description: "<p>Увеличивает урон малых линз.</p>"},
		"medium_laser_ammo":     {Name: "Средние лазерные линзы", Description: "<p>Увеличивает урон средних линз.</p>"},
		"big_laser_ammo":        {Name: "Большие лазерные линзы", Description: "<p>Увеличивает урон больших линз.</p>"},
		"small_rocket_ammo":     {Name: "Малые ракеты", Description: "<p>Увеличивает урон малых ракет.</p>"},
		"medium_rocket_ammo":    {Name: "Средние ракеты", Description: "<p>Увеличивает урон средних ракет.</p>"},
		"big_rocket_ammo":       {Name: "Большие ракеты", Description: "<p>Увеличивает урон больших ракет.</p>"},

		// оружие
		"small_ballistic_weapon":           {Name: "Малые баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых баллистических орудий. </p>"},
		"medium_ballistic_weapon":          {Name: "Средние баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних баллистических орудий. </p>"},
		"big_ballistic_weapon":             {Name: "Большие баллистические орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших баллистических орудий. </p>"},
		"small_laser_weapon":               {Name: "Малые лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых лазерных орудий. </p>"},
		"medium_laser_weapon":              {Name: "Средние лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних лазерных орудий. </p>"},
		"big_laser_weapon":                 {Name: "Большие лазерные орудия", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших лазерных орудий. </p>"},
		"small_rocket_weapon":              {Name: "Малые пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> малых пусковых установок.</p>"},
		"medium_rocket_weapon":             {Name: "Средние пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> средних пусковых установок.</p>"},
		"big_rocket_weapon":                {Name: "Большие пусковые установки", Description: "<p>Уменьшает <span class=\"importantly\">время перезарядки</span> больших пусковых установок.</p>"},
		"rotate_small_ballistic_weapon":    {Name: "Скорость поворота малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых баллистических орудий.</p>"},
		"rotate_medium_ballistic_weapon":   {Name: "Скорость поворота средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних баллистических орудий.</p>"},
		"rotate_big_ballistic_weapon":      {Name: "Скорость поворота больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших баллистических орудий.</p>"},
		"rotate_small_laser_weapon":        {Name: "Скорость поворота малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых лазерных орудий.</p>"},
		"rotate_medium_laser_weapon":       {Name: "Скорость поворота средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних лазерных орудий.</p>"},
		"rotate_big_laser_weapon":          {Name: "Скорость поворота больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших лазерных орудий.</p>"},
		"rotate_small_rocket_weapon":       {Name: "Скорость поворота малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> малых пусковых установок.</p>"},
		"rotate_medium_rocket_weapon":      {Name: "Скорость поворота средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> средних пусковых установок.</p>"},
		"rotate_big_rocket_weapon":         {Name: "Скорость поворота больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> больших пусковых установок.</p>"},
		"accuracy_small_ballistic_weapon":  {Name: "Точность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых баллистических орудий.</p>"},
		"accuracy_medium_ballistic_weapon": {Name: "Точность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних баллистических орудий.</p>"},
		"accuracy_big_ballistic_weapon":    {Name: "Точность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших баллистических орудий.</p>"},
		"accuracy_small_laser_weapon":      {Name: "Точность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых лазерных орудий.</p>"},
		"accuracy_medium_laser_weapon":     {Name: "Точность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних лазерных орудий.</p>"},
		"accuracy_big_laser_weapon":        {Name: "Точность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших лазерных орудий.</p>"},
		"accuracy_small_rocket_weapon":     {Name: "Точность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> малых пусковых установок.</p>"},
		"accuracy_medium_rocket_weapon":    {Name: "Точность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> средних пусковых установок.</p>"},
		"accuracy_big_rocket_weapon":       {Name: "Точность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">точность</span> больших пусковых установок.</p>"},
		"rate_small_ballistic_weapon":      {Name: "Скорострельность малых баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых баллистических орудий.</p>"},
		"rate_medium_ballistic_weapon":     {Name: "Скорострельность средних баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних баллистических орудий.</p>"},
		"rate_big_ballistic_weapon":        {Name: "Скорострельность больших баллистических орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших баллистических орудий.</p>"},
		"rate_small_laser_weapon":          {Name: "Скорострельность малых лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых лазерных орудий.</p>"},
		"rate_medium_laser_weapon":         {Name: "Скорострельность средних лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних лазерных орудий.</p>"},
		"rate_big_laser_weapon":            {Name: "Скорострельность больших лазерных орудий", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших лазерных орудий.</p>"},
		"rate_small_rocket_weapon":         {Name: "Скорострельность малых пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> малых пусковых установок.</p>"},
		"rate_medium_rocket_weapon":        {Name: "Скорострельность средних пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> средних пусковых установок.</p>"},
		"rate_big_rocket_weapon":           {Name: "Скорострельность больших пусковых установок", Description: "<p>Увеличивает <span class=\"importantly\">скорострельность</span> больших пусковых установок.</p>"},

		// корпуса
		"move_small_explores_body":      {Name: "Управление легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_replics_body":       {Name: "Управление легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_small_reverses_body":      {Name: "Управление легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_explores_body":     {Name: "Управление средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_replics_body":      {Name: "Управление средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_medium_reverses_body":     {Name: "Управление средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_explores_body":        {Name: "Управление тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_replics_body":         {Name: "Управление тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"move_big_reverses_body":        {Name: "Управление тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость поворота</span> корпуса.</p>"},
		"armor_small_explores_body":     {Name: "Системы защиты легких корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_replics_body":      {Name: "Системы защиты легких корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_small_reverses_body":     {Name: "Системы защиты легких корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_explores_body":    {Name: "Системы защиты средних корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_replics_body":     {Name: "Системы защиты средних корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_medium_reverses_body":    {Name: "Системы защиты средних корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_explores_body":       {Name: "Системы защиты тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_replics_body":        {Name: "Системы защиты тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"armor_big_reverses_body":       {Name: "Системы защиты тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает показатель <span class=\"importantly\">защиты</span> корпуса.</p>"},
		"view_small_explores_body":      {Name: "Использование оптики легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_explores_body":     {Name: "Использование оптики средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_explores_body":        {Name: "Использование оптики тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_replics_body":       {Name: "Использование оптики легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_replics_body":      {Name: "Использование оптики средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_replics_body":         {Name: "Использование оптики тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_small_reverses_body":      {Name: "Использование оптики легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_medium_reverses_body":     {Name: "Использование оптики средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"view_big_reverses_body":        {Name: "Использование оптики тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность обзора</span> корпуса.</p>"},
		"powercap_small_explores_body":  {Name: "Использование аккумулятора легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_explores_body": {Name: "Использование аккумулятора средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_explores_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_replics_body":   {Name: "Использование аккумулятора легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_replics_body":  {Name: "Использование аккумулятора средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_replics_body":     {Name: "Использование аккумулятора тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_small_reverses_body":  {Name: "Использование аккумулятора легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_medium_reverses_body": {Name: "Использование аккумулятора средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"powercap_big_reverses_body":    {Name: "Использование аккумулятора тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">объем аккумулятора</span> корпуса.</p>"},
		"radar_small_explores_body":     {Name: "Разведка легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_explores_body":    {Name: "Разведка средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_explores_body":       {Name: "Разведка тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_replics_body":      {Name: "Разведка легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_replics_body":     {Name: "Разведка средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_replics_body":        {Name: "Разведка тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_small_reverses_body":     {Name: "Разведка легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_medium_reverses_body":    {Name: "Разведка средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"radar_big_reverses_body":       {Name: "Разведка тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">дальность радара</span> корпуса.</p>"},
		"charging_small_explores_body":  {Name: "Энергосеть легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_explores_body": {Name: "Энергосеть средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_explores_body":    {Name: "Энергосеть тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_replics_body":   {Name: "Энергосеть легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_replics_body":  {Name: "Энергосеть средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_replics_body":     {Name: "Энергосеть тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_small_reverses_body":  {Name: "Энергосеть легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_medium_reverses_body": {Name: "Энергосеть средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"charging_big_reverses_body":    {Name: "Энергосеть тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">скорость зарядки аккумулятора</span> корпуса.</p>"},
		"replics_hauler":                {Name: "Грузоперевозки \"Replic\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"explores_hauler":               {Name: "Грузоперевозки \"Explores\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"reverses_hauler":               {Name: "Грузоперевозки \"Reverses\"", Description: "<p>Базовый навык владения тягачами.</p>"},
		"speed_small_explores_body":     {Name: "Скорость легких корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_replics_body":      {Name: "Скорость легких корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_small_reverses_body":     {Name: "Скорость легких корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_explores_body":    {Name: "Скорость средних корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_replics_body":     {Name: "Скорость средних корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_medium_reverses_body":    {Name: "Скорость средних корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_explores_body":       {Name: "Скорость тяжелых корпусов \"Explores\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_replics_body":        {Name: "Скорость тяжелых корпусов \"Replic\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"speed_big_reverses_body":       {Name: "Скорость тяжелых корпусов \"Reverses\"", Description: "<p>Увеличивает <span class=\"importantly\">максимальную скорость</span> и <span class=\"importantly\">скорость разгона</span> корпуса.</p>"},
		"industrial_transport":          {Name: "Управление промышленных корпусов", Description: "<p>Базовый навык владения промышленными корпусами.</p>"},
		"xeno_transport":                {Name: "Управление Ксенокорпусов", Description: "<p>Базовый навык владения Ксенокорпусами.</p>"},
	},
}
