package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var StructureDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"missile_defense":      {Name: "Missile defense", Description: "<p> An engineering structure for military purposes, tracks and counteracts the approach of unidentified or recognized as \"enemy\" missile-type projectiles. </p> <p> Like other structures, it functions by supplying energy. </p>"},
		"antenna_z-x":          {Name: "Antenna Z-X: 5", Description: "<p> A unique and perfectly preserved structure after the local end of the world, which by the appearance of its covering strongly resembles insect honeycombs </p>"},
		"explores_antenna":     {Name: "Antenna \"Veliri\"", Description: "<p> Part of the Veliri Explores tracking station, serves as a super long-range radar. </p>"},
		"explores_observatory": {Name: "Observatory \"Veliri\"", Description: "<p> Part of Veliri Explores Tracking Station, may serve as a watchtower. </p>"},
		"repair_station":       {Name: "Repair station", Description: "<p> An engineering structure used to carry out repair operations within its own radius of action and only allied signatures. </p> <p> Like other structures, it functions by supplying energy. </p>"},
		"laser_turret":         {Name: "Large laser turret", Description: "<p> A stationary automated defensive position that fires at enemy targets by emitting a high-energy beam. </p>"},
		"shield_generator":     {Name: "Force field generator", Description: "<p> An engineering structure for military purposes, serves as a defensive measure during military or civil conflicts. \"Force Field Generator\" - emits low-phase flows of energy, which forms a protective dome in a certain radius, which reduces any damage received during its work. </p> <p> Like other structures, it functions by supplying energy. </p>"},
		"jammer_generator":     {Name: "Jammer", Description: "<p> An engineering structure for military purposes, which, when activated, causes radio interference and interferes with the operation of any tracking electronics. </p>"},
		"extractor":            {Name: "Multipurpose mining rig", Description: "<p> An engineering structure of a civilian type, which is used purely for the extraction of mineral resources in an automated mode. The \"mining rig\" is defenseless and unable to withstand much damage. When filling the internal warehouse and not emptying it, it stops working. </p> <p> Like other structures, it functions by supplying energy. </p>"},
		"replic_gauss_gun":     {Name: "Gun \"Honchkins\"", Description: "<p> Ultra-Long Range Electromagnetic Artillery </p>"},
		"tank_turret":          {Name: "Large ballistic turret", Description: "<p> A stationary-automated defensive position firing large ballistic projectiles at enemy targets. </p>"},
		"artillery_turret":     {Name: "Artillery turret", Description: "<p> A stationary automated defensive position that tracks and attacks enemy targets with devastating artillery shells. </p>"},
		"energy_generator":     {Name: "Power generator", Description: "<p> An engineering structure of a fuel-exchange nature - powering buildings and devices around it within a certain radius of action. </p> <p> The structure of the structure is fragile, in order to maintain efficiency, constant refueling is required. </p>"},
		"radar":                {Name: "Radar", Description: "<p> An engineering structure, which dramatically increases the detection area of ​​any signatures and is able to warn in advance about the approach of unfriendly targets. </p> <p> Like other structures, it functions by supplying energy. </p>"},
		"storage":              {Name: "Warehouse", Description: "<p> An engineering structure serving with one single purpose - the storage of the cargo of its owner. The complex opening mechanism and dense walls make the \"warehouse\" an inaccessible target for pirates. </p> <p> Meanwhile, like other objects, the \"warehouse\" is vulnerable to the effect of \"destruction\". </p>"},
		"beacon":               {Name: "Faction beacon", Description: "<p> An engineering structure for military purposes, which is located on neutral, or enemy territory, which contributes to the beginning of its expansion. As a rule, in the course of conflicts, the \"lighthouse\" is the primary target of the attack, because it is the \"lighthouse\" that is the very first outpost where the attacking forces pull their reinforcements. </p>"},

		"corporation_base_1":          {Name: "Base", Description: "<p>The core of any large-scale structure in the wasteland. Prepared slipways, power drives and territory cleared for extraction of primary materials, which will later take on the appearance of a full-fledged and multifunctional base.</p><p>Like other similar structures of synthetics, it provides minimal support in the form of repair, refueling and storage.</p>"},
		"corporation_processing_1":    {Name: "Recycler", Description: "<p>An auxiliary resource processing structure — a base module responsible for analyzing items and crushing rocks mined by the player/bot to obtain raw materials.</p>"},
		"corporation_office_1":        {Name: "Office", Description: "<p>Auxiliary administrative structure — a base module responsible for management services. In particular, the 'Office' allows you to regulate the provision of warehouse work and transfer of synthetics to the base.</p>"},
		"corporation_prefabricated_1": {Name: "Factory", Description: "<p>An auxiliary production structure — a base module responsible for the manufacture of various other section modules, as well as parts/items often ordered for individual needs of the player.</p>"},
		"corporation_market_1":        {Name: "Market", Description: "<p><p>Auxiliary economic structure — a base module that is a large-scale trading platform where players make transactions for buying/selling all kinds of things.</p></p>"},
	},
	_const.RU: {
		"laser_turret":         {Name: "Большая лазерная турель", Description: "<p>Стационарно-автоматизированная оборонительная позиция, ведущая огонь по целям вражеского характера посредством испускания высокоэнергетического луча.</p>"},
		"tank_turret":          {Name: "Большая балистическая турель", Description: "<p>Стационарно-автоматизированная оборонительная позиция, ведущая огонь по целям вражеского характера крупными баллистическими снарядами.</p>"},
		"artillery_turret":     {Name: "Артиллерийская турель", Description: "<p>Стационарно-автоматизированная оборонительная позиция, отслеживающая и атакующая цели вражеского характера посредством разрушительных артиллерийских снарядов.</p>"},
		"shield_generator":     {Name: "Генератор силового поля", Description: "<p>Инженерное сооружение военного назначения, служит оборонительной мерой в ходе военных или гражданских конфликтов. «Генератор Силового Поля» - испускает малофазовые потоки энергии, чем образует в определённом радиусе защитный купол, чем снижает любой получаемый урон в ходе своей работы. </p>"},
		"energy_generator":     {Name: "Генератор энергии", Description: "<p>Инженерное сооружение топливо-обменного характера - запитывающее постройки и устройства вокруг себя в определённом радиусе действия. </p><p> Структура сооружения хрупка, ради поддержания работоспособности требуется постоянная дозаправка. </p>"},
		"jammer_generator":     {Name: "Генератор помех", Description: "<p>Инженерное сооружение военного назначения, при активации ставящее радиопомехи и мешающее работе любой электроники отслеживающего характера.  </p>"},
		"missile_defense":      {Name: "ПРО", Description: "<p>Инженерное сооружение военного назначения, отслеживает и противодействует подлёту неопознанных или распознанных как «вражеских» снарядов ракетного типа. </p><p> Как и прочие сооружения, функционирует за счёт запитывания энергией.</p>"},
		"radar":                {Name: "Радар", Description: "<p>Инженерное сооружение, что разительно увеличивает область обнаружения любых сигнатур и способно заранее предупредить о приближении недружелюбных целей. </p><p> Как и прочие сооружения, функционирует за счёт запитывания энергией.</p>"},
		"storage":              {Name: "Склад", Description: "<p>Инженерное сооружение, служащее с одной единственной целью – хранением груза его владельца. Сложный механизм открытия и плотные стенки, делают «склад» труднодоступной целью для пиратов. </p><p> Между тем, как и прочие объекты «склад» уязвим к эффекту «разрушения».</p>"},
		"beacon":               {Name: "Фракционный маяк", Description: "<p>Инженерное сооружение военного назначения, что размещается на нейтральной, или вражеской территории, чем способствует началу её экспансии.  Как правило, в ходе конфликтов «маяк» - первоочередная цель атаки, ведь именно «маяк» является тем самым первым форпостом, куда атакующие силы стягивают свои подкрепления.</p>"},
		"extractor":            {Name: "Универсально добывающая установка", Description: "<p>Инженерное сооружение гражданского образца, что используется сугубо при добыче ископаемых ресурсов в автоматизированном режиме. «Добывающая установка» - беззащитна и не способна выдержать большого урона. При заполнении внутреннего склада и его не опустошении, прекращает свою работу. </p>"},
		"repair_station":       {Name: "Ремонтная станция", Description: "<p>Инженерное сооружение, используемое для проведения ремонтных операций в радиусе собственного действия и только союзных сигнатур. </p><p> Как и прочие сооружения, функционирует за счёт запитывания энергией.</p>"},
		"replic_gauss_gun":     {Name: "Орудие \"Гончкинс\"", Description: "<p>Сверхдальняя электромагнитная артиллерия</p>"},
		"antenna_z-x":          {Name: "Антенна Z-X:5", Description: "<p>Уникальное и прекрасно сохранившееся после наступления местного конца света конструкция, что внешним видом своего покрытия, сильно напоминает соты насекомых</p>"},
		"explores_antenna":     {Name: "Антенна \"Велири\"", Description: "<p>Часть станции отслеживания Explores \"Велири\", служит как сверх дальний радар.</p>"},
		"explores_observatory": {Name: "Обсерватория \"Велири\"", Description: "<p>Часть станции отслеживания Explores \"Велири\", может служить как дозорная башня.</p>"},

		"corporation_base_1":          {Name: "База", Description: "<p>Ядро любого масштабного сооружения в пустошах. Заготовленные стапели, энергоприводы и расчищенная под добычу первичных материалов территория, что в дальнейшем примет облик полноценный и многофункциональной базы.</p><p>Как и прочие подобные сооружения синтетов, обеспечивает минимальную поддержку в виде: ремонта, дозаправки и хранилища.</p>\n"},
		"corporation_processing_1":    {Name: "Переработчик", Description: "<p>Вспомогательное сооружения переработки ресурсов – модуль базы, отвечающий за разбор предметов и измельчение добытых игроком/ботом горных пород ради поучения сырья.</p>"},
		"corporation_office_1":        {Name: "Офис", Description: "<p>Вспомогательное сооружения административного толка – модуль базы, отвечающий за управленческие услуги. В частности, «Офис» позволяет регулировать предоставление работы склада и переноса синтетов на базу.</p>"},
		"corporation_prefabricated_1": {Name: "Завод", Description: "<p>Вспомогательное сооружение производственного толка – модуль базы, отвечающий за изготовление различных иных секций-модулей, а также деталей/предметов, нередко заказываемых под индивидуальные нужды игрока.</p>"},
		"corporation_market_1":        {Name: "Рынок", Description: "<p><p>Вспомогательное сооружение экономического толка – модуль базы, представляющий из себя масштабную торговую площадку, где игроки совершают сделки по купле/продаже всевозможных вещей.</p></p>"},
	},
	_const.ZhCN: {
		"laser_turret":         {Name: "大型激光炮塔", Description: "<p>一种固定自动防御装置，通过发射高能光束攻击敌方目标。</p>"},
		"tank_turret":          {Name: "大型弹道炮塔", Description: "<p>一种固定自动防御装置，通过发射大型弹道炮弹攻击敌方目标。</p>"},
		"artillery_turret":     {Name: "火炮炮塔", Description: "<p>一种固定自动防御装置，通过发射破坏性炮弹追踪并攻击敌方目标。</p>"},
		"shield_generator":     {Name: "护盾发生器", Description: "<p>一种军用工程设施，用于在军事或民事冲突中作为防御措施。“护盾发生器”通过发射低相位能量流，在特定半径内形成保护罩，减少其工作期间受到的任何伤害。</p>"},
		"energy_generator":     {Name: "能量发生器", Description: "<p>一种燃料交换型工程设施，为周围一定半径内的建筑和设备提供能量。</p><p>该设施结构脆弱，需要持续补充燃料以维持运行。</p>"},
		"jammer_generator":     {Name: "干扰发生器", Description: "<p>一种军用工程设施，激活后会产生无线电干扰，妨碍任何追踪类电子设备的运作。</p>"},
		"missile_defense":      {Name: "导弹防御系统", Description: "<p>一种军用工程设施，追踪并拦截未识别或被标记为“敌方”的导弹类弹药。</p><p>与其他设施一样，需要能量供应才能运作。</p>"},
		"radar":                {Name: "雷达", Description: "<p>一种工程设施，显著增加探测范围，能够提前预警敌对目标的接近。</p><p>与其他设施一样，需要能量供应才能运作。</p>"},
		"storage":              {Name: "仓库", Description: "<p>一种工程设施，唯一目的是存储所有者的货物。复杂的开启机制和坚固的墙壁使“仓库”成为海盗难以攻破的目标。</p><p>然而，与其他设施一样，“仓库”也容易受到“破坏”效果的影响。</p>"},
		"beacon":               {Name: "阵营信标", Description: "<p>一种军用工程设施，部署在中立或敌方领土上，促进对该区域的扩张。通常，在冲突中，“信标”是首要攻击目标，因为它是攻击部队集结增援的第一个前哨站。</p>"},
		"extractor":            {Name: "通用采矿装置", Description: "<p>一种民用工程设施，专门用于自动化开采矿物资源。“采矿装置”毫无防御能力，无法承受大量伤害。当内部存储满载且未清空时，将停止工作。</p>"},
		"repair_station":       {Name: "维修站", Description: "<p>一种工程设施，用于在自身作用范围内对友方单位进行维修操作。</p><p>与其他设施一样，需要能量供应才能运作。</p>"},
		"replic_gauss_gun":     {Name: "“贡奇金斯”炮", Description: "<p>超远程电磁炮</p>"},
		"antenna_z-x":          {Name: "Z-X:5天线", Description: "<p>一种独特且保存完好的结构，外观类似于昆虫的蜂窝。</p>"},
		"explores_antenna":     {Name: "“维利里”天线", Description: "<p>Explores“维利里”追踪站的一部分，用作超远程雷达。</p>"},
		"explores_observatory": {Name: "“维利里”天文台", Description: "<p>Explores“维利里”追踪站的一部分，可用作瞭望塔。</p>"},

		"corporation_base_1":          {Name: "基地", Description: "<p>任何大规模设施的核心。准备好的支架、能源驱动器和清理出的初级材料开采区域，未来将发展成一个功能齐全的多功能基地。</p><p>与其他合成设施一样，提供维修、补给和存储等基本支持。</p>"},
		"corporation_processing_1":    {Name: "加工厂", Description: "<p>辅助资源加工设施——基地模块，负责分解物品和粉碎玩家/机器人开采的矿石以获取原材料。</p>"},
		"corporation_office_1":        {Name: "办公室", Description: "<p>辅助行政管理设施——基地模块，负责管理服务。特别是，“办公室”允许调节仓库工作和将合成单位传送到基地。</p>"},
		"corporation_prefabricated_1": {Name: "工厂", Description: "<p>辅助生产设施——基地模块，负责制造各种其他模块部分，以及根据玩家个人需求定制的零件/物品。</p>"},
		"corporation_market_1":        {Name: "市场", Description: "<p>辅助经济设施——基地模块，作为一个大规模的交易平台，玩家可以在此买卖各种物品。</p>"},
	},
}
