package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var TrashDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"terraforming_equipment":        {Name: "Terraforming equipment", Description: "<p> Terraforming equipment - advanced technologies, both mobile and stationary, which are capable of changing climatic conditions of a very different spectrum for the sake of manipulating climatic conditions. </p>"},
		"strange_box":                   {Name: "Strange box", Description: "<p> A strange box of unknown origin, constantly emits a strong signal. </p>"},
		"block_il":                      {Name: "IL block", Description: "<p> Block \"IL\" -size loading blocks of an artificial personality, which \"Synthetes\" use to store, transfer and set their own consciousness in one form or another. </p>"},
		"contribution":                  {Name: "Contribution", Description: "<p> Contribution - packaged and labeled money transferred by one side during the loss of a military conflict to the other. </p>"},
		"deactivated_reactor":           {Name: "Deactivated reactor", Description: "<p> A deactivated reactor is a sample of a reactor standardized in the \"Sintet\" environment, capable of generating enough energy to power entire bases with it. </p>"},
		"ammunition_Gonchkins":          {Name: "Ammunition \"Gonchkins\"", Description: "<p> Gonchkins ammunition is a type of projectile designed specifically for the Honchkins ballistic weapon. In the affected area, it has incredible destructive power. </p>"},
		"security_bots":                 {Name: "Security bots", Description: "<p> Security bots are bots of a purely military type that are used in patrolling the area, conducting military and peacekeeping operations. Due to the simplicity of the design idea, their AI is often prone to deviant behavior. </p>"},
		"political_message":             {Name: "Political message", Description: "<p> Political message - demands, claims, needs and ultimatums. Typically, these are the temporary data holders. </p>"},
		"data_block":                    {Name: "Data block", Description: "<p> Data block - ordinary \"civilian\" storage devices that are used to store and transmit data in various directions. The manufacturer does not ensure the security of information. </p>"},
		"scientific_materials":          {Name: "Scientific materials", Description: "<p> Research papers - documented findings, final reports, and research papers on a variety of topics. </p>"},
		"atmospheric_domes":             {Name: "Atmospheric domes", Description: "<p> Atmospheric domes - systems of stops, walls and glass coverings disassembled and secured for transportation to recreate an artificial atmosphere of the required type in the global area of ​​a particular territory. </p>"},
		"equipment_sold":                {Name: "Equipment sold", Description: "<p> Sold equipment - reinforced, unfolded, described and ready for release and sale of equipment for various purposes. </p>"},
		"datasheet":                     {Name: "Infopackage", Description: "<p> Info packet with various information. </p>"},
		"reliquary":                     {Name: "Reliquary", Description: "<p> The reliquary is a small vacuum cube weighing no more than three kilograms, whose technology allows it to “contain” many objects of physical and informational nature. </p>"},
		"corps_of_the_prisoner_synthet": {Name: "Corps of the prisoner \"Synthet\"", Description: "<p> The body of the captured \"Synthet\" - the body, chassis, guns and a myriad of systems of this disconnected from power sources and assembled \"Synthet\". </p>"},
		"armament":                      {Name: "Armament", Description: "<p> Armament - armored cargo boxes that contain the barrels of gun systems, spare parts, as well as boxes with ammunition. </p>"},
		"blueprints":                    {Name: "Blueprints", Description: "<p> Drawings - a graphic design document containing a detailed image of one or another engineering object. </p>"},
		"card":                          {Name: "Map", Description: "<p> Looks like a key to some kind of lock. </p>"},
		"products":                      {Name: "Goods", Description: "<p> Goods - as a rule, a manufactured product or a mined thing that is packed in a special membrane and is involved in trade. </p>"},
		"scientific_equipment":          {Name: "Scientific equipment", Description: "<p> Scientific equipment - small devices and whole mobile engineering objects of scientific sense. The best purchase for every budding prospector. </p>"},
		"artificially_bred_species":     {Name: "Artificially bred species", Description: "<p> Artificially bred species are selected and reared after careful genetic selection, which are transported in specialized containers with artificial atmosphere support. </p>"},
		"trade_offer":                   {Name: "Trade offer", Description: "<p> Trade offer - a transaction, agreed amounts and specific deliveries between the parties, which are indicated on this data carrier. The information is confidential. </p>"},
		"magnetic_resonator":            {Name: "Magnetic resonator", Description: "<p> Magnetic resonator is a force device by means of propagated magnetic waves, which lead to unpredictable geophysical consequences. </p>"},
		"deactivated_bots":              {Name: "Deactivated bots", Description: "<p> Deactivated bots - bots disconnected from power sources, which are prepared for repair operations, transportation or sale. </p>"},
		"dispatch":                      {Name: "Dispatch", Description: "<p> Dispatch - a diplomatic letter about a request for help, a declaration of war or banal threats, not publicized. </p>"},
		"supplies":                      {Name: "Supplies", Description: "<p> Supplies - a set of narrowly ordered or badly needed goods to maintain the health and vitality of various objects. </p>"},
		"technological_map":             {Name: "Routing", Description: "<p> Technological map is an advanced, convenient and uncomplicated way of storing and transferring large amounts of data. </p>"},
		"scientific_data":               {Name: "Scientific evidence", Description: "<p> Scientific data - archived, classified and infinitely valuable data for those who value the contribution of science to everyday life. </p>"},
		"living_flora_and_fauna":        {Name: "Living flora and fauna", Description: "<p> Living flora and fauna - sealed flasks with an artificial atmosphere, where both dangerous and safe representatives of the living flora and fauna of the planet Veliri-6 are reserved </p>"},
		"subatomic_reactor":             {Name: "Subatomic reactor", Description: "<p> A subatomic reactor is a fragile and incredibly dangerous in its own destruction engineering facility, capable of powering entire bases of \"Synthets\". </p>"},
		"ice_liquor":                    {Name: "Ice-liquor", Description: "<p>A mysterious artifact, fraught with great power. </p>"},
		"weapon_nutrients":              {Name: "Weapon nutrients", Description: "<p>Consumables are used in industrial types of tools</p>"},
		"orbital_drop_beacons":          {Name: "Orbital drop beacons", Description: "<p>Used to signal orbital systems</p>"},

		"egg":                  {Name: "Egg", Description: "<p>An unusual object of oval shape, clearly not created by synthetics. Given the multiple surrounding structures at the site of the find, the ellipsoid clearly has some connection with them.</p>"},
		"blue_fragile_capsule": {Name: "Blue pulse capsule", Description: "<p>A spherical technologically complex device with visually tangible electromagnetic waves of a bluish tint. Considering the size and compactness of the capsule, its possible function may lie in the injection of some unknown capacities. But what exactly for?</p>"},
		"red_fragile_capsule":  {Name: "Red pulse capsule", Description: "<p>A spherical technologically complex device with visible electromagnetic waves of reddish hue. Considering the size and compactness of the capsule, its possible function may be hidden in the build-up of some unknown powers. But what is it for?</p>"},
		"ground_drone_3":       {Name: "Ancient drone", Description: "<p>An extremely primitive self-guided vehicle by the standards of synthetics. Despite its passable driving performance and rather outdated weapons, the drone's protection cannot withstand synthetics' hacking strategies, which allows for full control over it.</p>"},
		"Replic_label":         {Name: "Replic faction label", Description: "<p>Engraved symbolic representation of one of the factions on the planet. In this case, the symbol of Replics is depicted — ardent expansionists and militarists among all other synthetics factions.</p>"},
		"teleport_hack":        {Name: "Teleport hack", Description: "<p>Remote access and authorization override device. Allows you to block access to teleportation gates, and also makes synthetics bases vulnerable to destruction during a factional war.</p>"},
		"siphil_contract":      {Name: "Forged Replic Communicator", Description: "<p>You were recommended as someone who can solve problems. He is one of them.</p><p>Try to resolve the matter quietly and without unnecessary witnesses.</p><p>Any assistants - also eliminate after completion.</p><p><br>I.</p>"},
	},
	_const.RU: {
		"card":                          {Name: "Карта", Description: "<p>Похоже на ключ от какого то замка.</p>"},
		"datasheet":                     {Name: "Инфопакет", Description: "<p>Инфопакет с различной информацией.</p>"},
		"reliquary":                     {Name: "Реликварий", Description: "<p>Реликварий - небольших размеров, весом не больше трёх килограммов вакуумный куб, чья технология позволяет “вмещать” внутрь него множество объектов физической, так и информационной природы.</p>"},
		"block_il":                      {Name: "Блок “ИЛ”", Description: "<p>Блок “ИЛ” -габаритные загрузочные блоки искусственной личности, которые “Синтеты” используют для хранения, переноса и установки собственного сознания в ту или иную форму.</p>"},
		"technological_map":             {Name: "Технологическая карта", Description: "<p>Технологическая карта - передовой, удобный и незамысловатый способ по хранению-передаче больших массивов данных. </p>"},
		"political_message":             {Name: "Политическое послание", Description: "<p>Политическое послание - требования, претензии, нужды и ультиматумы. Как правило, подобное содержится в этих временных держателях данных.</p>"},
		"trade_offer":                   {Name: "Торговое предложение", Description: "<p>Торговое предложение - сделка, оговоренные суммы и конкретные поставки между сторонами, что указаны на данном носителе данных. Информация конфиденциальна. </p>"},
		"data_block":                    {Name: "Блок данных", Description: "<p>Блок данных - обычные накопители “гражданского” образца, что используются для хранения и передачи данных различного направления. Производитель не обеспечивает безопасность информации.</p>"},
		"products":                      {Name: "Товары", Description: "<p>Товары - как правило произведённый продукт или добытая вещь, что упакована в специальную мембрану и участвует в торговом обороте.</p>"},
		"corps_of_the_prisoner_synthet": {Name: "Корпус пленного “Синтета”", Description: "<p>Корпус пленного “Синтета” - корпус, ходовая часть, орудия и несметное множество систем данного отключённого от источников питания и скомпонованного “Синтета”.</p>"},
		"scientific_data":               {Name: "Научные данные", Description: "<p>Научные данные - заархивированные, засекреченные и бесконечно ценные данные для тех, кто ценит вклад науки в повседневную жизнь.</p>"},
		"contribution":                  {Name: "Контрибуция", Description: "<p>Контрибуция - упакованные и помеченные денежные средства, переданные одной стороной в ходе проигрыше военного конфликта, другой.</p>"},
		"magnetic_resonator":            {Name: "Магнитные резонатор", Description: "<p>Магнитные резонатор - устройство силового воздействия посредством распространяемых магнитных волн, что приводят к непредсказуемым геофизическим последствиям.</p>"},
		"equipment_sold":                {Name: "Проданное оборудование", Description: "<p>Проданное оборудование - укреплённое, разложенное, описанное и готовое к отпуску и реализации оборудование самого разного назначения.</p>"},
		"living_flora_and_fauna":        {Name: "Живая флора и фауна", Description: "<p>Живая флора и фауна - герметичные колбы с искусственной атмосферой, где зарезервированы, как опасные, так и безопасные представители живой флоры и фауны планеты Veliri-6</p>"},
		"deactivated_reactor":           {Name: "Деактивированный реактор", Description: "<p>Деактивированный реактор - стандартизированный в среде “Синтетов” образец реактора, способный вырабатывать достаточную энергию, дабы запитывать ею целые базы. </p>"},
		"armament":                      {Name: "Вооружение", Description: "<p>Вооружение - бронированные грузовые ящики, вмещающие в себя стволы орудийных систем, запасные части, а также ящики с амуницией. </p>"},
		"blueprints":                    {Name: "Чертежи", Description: "<p>Чертежи - графический конструкторский документ, содержащий детальное изображение того или иного инженерного объекта. </p>"},
		"deactivated_bots":              {Name: "Деактивированные боты", Description: "<p>Деактивированные боты - отключённые от источников питания боты, которые подготовлены для ремонтных операций, транспортировки или продажи. </p>"},
		"ammunition_Gonchkins":          {Name: "Боеприпасы “Гонкчкинс”", Description: "<p>Боеприпасы “Гонкчкинс” - тип разгонного снаряда, который разработан специально для баллистического оружия “Гончкинс”. В зоне поражения, обладает невероятной разрушительной силой. </p>"},
		"subatomic_reactor":             {Name: "Субатомный реактор", Description: "<p>Субатомный реактор - хрупкий и невероятно опасный при собственном разрушении инженерный объект, способный запитывать целые базы “Синтетов”. </p>"},
		"scientific_materials":          {Name: "Научные материалы", Description: "<p>Научные материалы - задокументированные выводы, финальные отчёты и научные работы на самые разные темы.</p>"},
		"dispatch":                      {Name: "Депеша", Description: "<p>Депеша - дипломатическое письмо о требовании помощи, объявлении войны или банальных угрозах, лишённое огласки. </p>"},
		"scientific_equipment":          {Name: "Научное оборудование", Description: "<p>Научное оборудование - небольшие устройства и целые передвижные инженерные объекты научного толка. Лучшее приобретении для каждого начинающего изыскателя.</p>"},
		"terraforming_equipment":        {Name: "Терраформирующее оборудование", Description: "<p>Терраформирующее оборудование - передовые технологии как мобильного, так и стационарного толка, что способны изменять в угоду манипулирующего климатические условия самого разного спектра.</p>"},
		"artificially_bred_species":     {Name: "Искусственно выведенные виды", Description: "<p>Искусственно выведенные виды - отобранные и выращенные после тщательной генетической селекции виды, что перевозятся в специализированных контейнерах с поддержкой искусственной атмосферы.</p>"},
		"atmospheric_domes":             {Name: "Атмосферные купола", Description: "<p>Атмосферные купола - разобранные и закрепленные для транспортировки системы упоров, стен и стеклянных покрытий по воссозданию искусственной атмосферы нужного типа на глобальной участке той или иной территории.</p>"},
		"supplies":                      {Name: "Припасы", Description: "<p>Припасы - набор узко заказанных или крайне необходимых товаров для поддержания исправности и жизнеспособности различных объектов. </p>"},
		"security_bots":                 {Name: "Охранные боты", Description: "<p>Охранные боты - боты сугубо военного образца, что используются в патрулировании округи, проведении военных и миротворческих операций. Из-за простоты конструкторской идеи, их ИИ нередко склонен к девиантному поведению.</p>"},
		"ice_liquor":                    {Name: "Ice-liquor", Description: "<p>Загадочный артефакт, таящий в себе великую силу.</p>"},
		"weapon_nutrients":              {Name: "Питательные элементы орудий", Description: "<p>Расходные элементы использующиеся в энергетических видах орудий</p>"},
		"orbital_drop_beacons":          {Name: "Маяки орбитального сброса", Description: "<p>Используются для подачи сигнала орбитальным системам</p>"},
		"strange_box":                   {Name: "Странная коробка", Description: "<p>Странный ящик неизвестного происхождение, постоянно излучает сильный сигнал.</p>"},

		"egg":                  {Name: "Яйцо", Description: "<p>Необычный объект овальной формы, однозначно созданный не синтетами. Учитывая множественные окружающие сооружения на месте находки, эллипсоид явно имеет с ними некую связь.</p>"},
		"blue_fragile_capsule": {Name: "Голубая пульс-капсула", Description: "<p>Шарообразное технологически сложное устройство, с визуально осязаемыми электромагнитными волнами голубоватого оттенка. Учитывая размеры и компактность капсулы, её возможная функция может крыться в нагнетании неких неизвестных мощностей. Но, для чего именно?</p>"},
		"red_fragile_capsule":  {Name: "Красная пульс-капсула", Description: "<p>Шарообразное технологически сложное устройство, с визуально осязаемыми электромагнитными волнами красноватого оттенка. Учитывая размеры и компактность капсулы, её возможная функция может крыться в нагнетании неких неизвестных мощностей. Но, для чего именно?</p>"},
		"ground_drone_3":       {Name: "Древний дрон", Description: "<p>Крайне примитивная по технологическим меркам синтетов самоуправляемая техника. Несмотря на сносные ходовые качества и достаточно отсталое вооружение, защита дрона не в силах противостоять стратегиям взлома синтетов, что позволяет получить над ним полный контроль.</p>"},
		"Replic_label":         {Name: "Ярлык фракции \"Replic\"", Description: "<p>Выгравированное символическое отображение одной из фракций на планете. В данном случае, изображён символ Replics - ярых экспансионистов и милитаристов из всех прочих фракций синтетов.</p>"},
		"teleport_hack":        {Name: "Взлом телепорта", Description: "<p>Устройство удалённого доступа и переписи авторизации. Позволяет блокировать доступ к телепортационным вратам, а также делает базы синтетов во время фракционной войны - уязвимыми к уничтожению.</p>"},
		"siphil_contract":      {Name: "Поддельный коммуникатор Replic", Description: "<p>Тебя посоветовали, как умеющего разрешать проблемы. Он - одна из таких.</p><p>Постарайся решить вопрос тихо и без лишних свидетелей.</p><p>Любых помощников - также распыли по окончании.</p><p><br>И.</p>"},
	},
	_const.ZhCN: {
		"card":                          {Name: "卡片", Description: "<p>看起来像是某种锁的钥匙。</p>"},
		"datasheet":                     {Name: "信息包", Description: "<p>包含各种信息的信息包。</p>"},
		"reliquary":                     {Name: "圣物箱", Description: "<p>圣物箱——一种小型、重量不超过三公斤的真空立方体，其技术能够“容纳”许多物理或信息性质的对象。</p>"},
		"block_il":                      {Name: "“IL”模块", Description: "<p>“IL”模块——用于存储、传输和将意识安装到某种形式的人工人格加载模块。</p>"},
		"technological_map":             {Name: "技术图纸", Description: "<p>技术图纸——一种先进、方便且简单的方式，用于存储和传输大量数据。</p>"},
		"political_message":             {Name: "政治信息", Description: "<p>政治信息——通常包含要求、诉求、需求和最后通牒。</p>"},
		"trade_offer":                   {Name: "贸易提议", Description: "<p>贸易提议——双方之间的交易、商定金额和具体交付内容，信息保密。</p>"},
		"data_block":                    {Name: "数据块", Description: "<p>数据块——普通民用数据存储设备，用于存储和传输各种数据。制造商不保证信息安全。</p>"},
		"products":                      {Name: "商品", Description: "<p>商品——通常是生产的产品或开采的物品，包装在特殊膜中并参与贸易流通。</p>"},
		"corps_of_the_prisoner_synthet": {Name: "被俘“合成者”的躯体", Description: "<p>被俘“合成者”的躯体——被切断电源并打包的“合成者”的躯体、行走部分、武器和无数系统。</p>"},
		"scientific_data":               {Name: "科学数据", Description: "<p>科学数据——归档、加密且对重视科学贡献的人来说无比珍贵的数据。</p>"},
		"contribution":                  {Name: "赔款", Description: "<p>赔款——在军事冲突失败后，一方交给另一方的打包并标记的资金。</p>"},
		"magnetic_resonator":            {Name: "磁共振器", Description: "<p>磁共振器——通过传播磁波进行强力影响的设备，可能导致不可预测的地球物理后果。</p>"},
		"equipment_sold":                {Name: "售出设备", Description: "<p>售出设备——加固、分解、描述并准备出售的各种用途设备。</p>"},
		"living_flora_and_fauna":        {Name: "活体动植物", Description: "<p>活体动植物——带有密封人工大气的容器，保存着Veliri-6星球上危险或安全的动植物代表。</p>"},
		"deactivated_reactor":           {Name: "停用反应堆", Description: "<p>停用反应堆——“合成者”标准化的反应堆样本，能够产生足够的能量为整个基地供电。</p>"},
		"armament":                      {Name: "武器装备", Description: "<p>武器装备——装甲货运箱，内含火炮系统、备件和弹药箱。</p>"},
		"blueprints":                    {Name: "蓝图", Description: "<p>蓝图——包含某个工程对象详细图纸的设计文件。</p>"},
		"deactivated_bots":              {Name: "停用机器人", Description: "<p>停用机器人——被切断电源并准备进行维修、运输或出售的机器人。</p>"},
		"ammunition_Gonchkins":          {Name: "“贡奇金斯”弹药", Description: "<p>“贡奇金斯”弹药——专门为“贡奇金斯”弹道武器设计的加速弹药，具有极强的破坏力。</p>"},
		"subatomic_reactor":             {Name: "亚原子反应堆", Description: "<p>亚原子反应堆——脆弱且极具破坏性的工程对象，能够为整个“合成者”基地供电。</p>"},
		"scientific_materials":          {Name: "科学材料", Description: "<p>科学材料——记录的研究结论、最终报告和各种主题的科学论文。</p>"},
		"dispatch":                      {Name: "急件", Description: "<p>急件——要求援助、宣战或简单威胁的外交信件，内容保密。</p>"},
		"scientific_equipment":          {Name: "科学设备", Description: "<p>科学设备——小型设备或移动式工程对象，适合每位初学者的最佳选择。</p>"},
		"terraforming_equipment":        {Name: "地形改造设备", Description: "<p>地形改造设备——能够改变气候条件的先进移动或固定技术。</p>"},
		"artificially_bred_species":     {Name: "人工培育物种", Description: "<p>人工培育物种——经过基因筛选并培育的物种，运输在带有支持人工大气的专用容器中。</p>"},
		"atmospheric_domes":             {Name: "大气穹顶", Description: "<p>大气穹顶——拆解并固定以便运输的系统，用于在特定区域重建所需类型的人工大气。</p>"},
		"supplies":                      {Name: "补给", Description: "<p>补给——用于维持各种设备正常运行的必需品。</p>"},
		"security_bots":                 {Name: "安保机器人", Description: "<p>安保机器人——纯军用机器人，用于巡逻、执行军事和维和任务。由于其简单的设计理念，其人工智能经常容易出现异常行为。</p>"},
		"ice_liquor":                    {Name: "冰酒", Description: "<p>神秘的文物，蕴藏着巨大的力量。</p>"},
		"weapon_nutrients":              {Name: "武器营养元素", Description: "<p>用于能量武器的消耗性元素。</p>"},
		"orbital_drop_beacons":          {Name: "轨道空投信标", Description: "<p>用于向轨道系统发送信号。</p>"},
		"strange_box":                   {Name: "奇怪的盒子", Description: "<p>来源不明的奇怪箱子，持续发出强信号。</p>"},
		"egg":                           {Name: "蛋", Description: "<p>一个不寻常的椭圆形物体，显然不是由合成者制造的。考虑到发现地点周围的多个建筑，这个椭圆体显然与它们有某种联系。</p>"},
		"blue_fragile_capsule":          {Name: "蓝色脉冲胶囊", Description: "<p>一个技术复杂的球形装置，带有可见的蓝调电磁波。考虑到胶囊的尺寸和紧凑性，其可能的功能可能是积累某种未知的能量。但具体是为了什么？</p>"},
		"red_fragile_capsule":           {Name: "红色脉冲胶囊", Description: "<p>一个技术复杂的球形装置，带有可见的红调电磁波。考虑到胶囊的尺寸和紧凑性，其可能的功能可能是积累某种未知的能量。但具体是为了什么？</p>"},
		"ground_drone_3":                {Name: "古代无人机", Description: "<p>从技术角度来看，这是一种极其原始的自主设备。尽管其机动性和武器系统相对落后，但其防御系统无法抵抗合成者的黑客策略，这使得合成者可以完全控制它。</p>"},
		"Replic_label":                  {Name: "“Replic”派系标签", Description: "<p>雕刻的象征性标志，代表星球上的一个派系。在这里，展示的是Replics的标志——所有合成者派系中最具扩张主义和军事主义的派系。</p>"},
		"teleport_hack":                 {Name: "传送门破解", Description: "<p>远程访问和授权重写设备。允许封锁传送门的访问权限，并在派系战争期间使合成者基地容易受到破坏。</p>"},
		"siphil_contract":               {Name: "Replic伪造通讯器", Description: "<p>有人推荐你作为能解决问题的人。他就是其中一个问题。</p><p>尽量安静地解决，不要留下多余目击者。</p><p>所有助手——完成后也一并处理掉。</p><p><br>I.</p>"},
	},
}
