package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var TrashDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"terraforming_equipment":        {Name: "Terraforming equipment", Description: "<p> Terraforming equipment - advanced technologies, both mobile and stationary, which are capable of changing climatic conditions of a very different spectrum for the sake of manipulating climatic conditions. </p>"},
		"strange_box":                   {Name: "Strange box", Description: "<p> A strange box of unknown origin, constantly emits a strong signal. </p>"},
		"block_il":                      {Name: "IL block", Description: "<p> Block \"IL\" -size loading blocks of an artificial personality, which \"Synthetes\" use to store, transfer and set their own consciousness in one form or another. </p>"},
		"contribution":                  {Name: "Contribution", Description: "<p> Contribution - packaged and labeled money transferred by one side during the loss of a military conflict to the other. </p>"},
		"deactivated_reactor":           {Name: "Deactivated reactor", Description: "<p> A deactivated reactor is a sample of a reactor standardized in the \"Sintet\" environment, capable of generating enough energy to power entire bases with it. </p>"},
		"ammunition_Gonchkins":          {Name: "Ammunition \"Gonchkins\"", Description: "<p> Gonchkins ammunition is a type of projectile designed specifically for the Honchkins ballistic weapon. In the affected area, it has incredible destructive power. </p>"},
		"security_bots":                 {Name: "Security bots", Description: "<p> Security bots are bots of a purely military type that are used in patrolling the area, conducting military and peacekeeping operations. Due to the simplicity of the design idea, their AI is often prone to deviant behavior. </p>"},
		"political_message":             {Name: "Political message", Description: "<p> Political message - demands, claims, needs and ultimatums. Typically, these are the temporary data holders. </p>"},
		"data_block":                    {Name: "Data block", Description: "<p> Data block - ordinary \"civilian\" storage devices that are used to store and transmit data in various directions. The manufacturer does not ensure the security of information. </p>"},
		"scientific_materials":          {Name: "Scientific materials", Description: "<p> Research papers - documented findings, final reports, and research papers on a variety of topics. </p>"},
		"atmospheric_domes":             {Name: "Atmospheric domes", Description: "<p> Atmospheric domes - systems of stops, walls and glass coverings disassembled and secured for transportation to recreate an artificial atmosphere of the required type in the global area of ​​a particular territory. </p>"},
		"equipment_sold":                {Name: "Equipment sold", Description: "<p> Sold equipment - reinforced, unfolded, described and ready for release and sale of equipment for various purposes. </p>"},
		"datasheet":                     {Name: "Infopackage", Description: "<p> Info packet with various information. </p>"},
		"reliquary":                     {Name: "Reliquary", Description: "<p> The reliquary is a small vacuum cube weighing no more than three kilograms, whose technology allows it to “contain” many objects of physical and informational nature. </p>"},
		"corps_of_the_prisoner_synthet": {Name: "Corps of the prisoner \"Synthet\"", Description: "<p> The body of the captured \"Synthet\" - the body, chassis, guns and a myriad of systems of this disconnected from power sources and assembled \"Synthet\". </p>"},
		"armament":                      {Name: "Armament", Description: "<p> Armament - armored cargo boxes that contain the barrels of gun systems, spare parts, as well as boxes with ammunition. </p>"},
		"blueprints":                    {Name: "Blueprints", Description: "<p> Drawings - a graphic design document containing a detailed image of one or another engineering object. </p>"},
		"card":                          {Name: "Map", Description: "<p> Looks like a key to some kind of lock. </p>"},
		"products":                      {Name: "Goods", Description: "<p> Goods - as a rule, a manufactured product or a mined thing that is packed in a special membrane and is involved in trade. </p>"},
		"scientific_equipment":          {Name: "Scientific equipment", Description: "<p> Scientific equipment - small devices and whole mobile engineering objects of scientific sense. The best purchase for every budding prospector. </p>"},
		"artificially_bred_species":     {Name: "Artificially bred species", Description: "<p> Artificially bred species are selected and reared after careful genetic selection, which are transported in specialized containers with artificial atmosphere support. </p>"},
		"trade_offer":                   {Name: "Trade offer", Description: "<p> Trade offer - a transaction, agreed amounts and specific deliveries between the parties, which are indicated on this data carrier. The information is confidential. </p>"},
		"magnetic_resonator":            {Name: "Magnetic resonator", Description: "<p> Magnetic resonator is a force device by means of propagated magnetic waves, which lead to unpredictable geophysical consequences. </p>"},
		"deactivated_bots":              {Name: "Deactivated bots", Description: "<p> Deactivated bots - bots disconnected from power sources, which are prepared for repair operations, transportation or sale. </p>"},
		"dispatch":                      {Name: "Dispatch", Description: "<p> Dispatch - a diplomatic letter about a request for help, a declaration of war or banal threats, not publicized. </p>"},
		"supplies":                      {Name: "Supplies", Description: "<p> Supplies - a set of narrowly ordered or badly needed goods to maintain the health and vitality of various objects. </p>"},
		"technological_map":             {Name: "Routing", Description: "<p> Technological map is an advanced, convenient and uncomplicated way of storing and transferring large amounts of data. </p>"},
		"scientific_data":               {Name: "Scientific evidence", Description: "<p> Scientific data - archived, classified and infinitely valuable data for those who value the contribution of science to everyday life. </p>"},
		"living_flora_and_fauna":        {Name: "Living flora and fauna", Description: "<p> Living flora and fauna - sealed flasks with an artificial atmosphere, where both dangerous and safe representatives of the living flora and fauna of the planet Veliri-6 are reserved </p>"},
		"subatomic_reactor":             {Name: "Subatomic reactor", Description: "<p> A subatomic reactor is a fragile and incredibly dangerous in its own destruction engineering facility, capable of powering entire bases of \"Synthets\". </p>"},
		"ice_liquor":                    {Name: "Ice-liquor", Description: "<p>A mysterious artifact, fraught with great power. </p>"},
		"weapon_nutrients":              {Name: "Weapon nutrients", Description: "<p>Consumables are used in industrial types of tools</p>"},
		"orbital_drop_beacons":          {Name: "Orbital drop beacons", Description: "<p>Used to signal orbital systems</p>"},

		"egg":                  {Name: "Egg", Description: "<p>Яиичко11</p>"},
		"blue_fragile_capsule": {Name: "blue_fragile_capsule", Description: "<p>blue_fragile_capsule</p>"},
		"red_fragile_capsule":  {Name: "red_fragile_capsule", Description: "<p>red_fragile_capsule</p>"},
		"ground_drone_3":       {Name: "ground_drone_3", Description: "<p>ground_drone_3</p>"},
		"Replic_label":         {Name: "Replic Faction Label", Description: "<p> </p>"},
		"teleport_hack":        {Name: "Взлом телепорта", Description: "<p>Одноразовое устройство которое позволяет переписать настройки доступа в кластерные сектора.</p><p>Помимо взлома перегружает точки выхода и сеть базы точки выхода из телепорта начинают работать как глушилки, а база и все ее сооружения становятся уязвимы к уничтожению.</p>"},
	},
	_const.RU: {
		"card":                          {Name: "Карта", Description: "<p>Похоже на ключ от какого то замка.</p>"},
		"datasheet":                     {Name: "Инфопакет", Description: "<p>Инфопакет с различной информацией.</p>"},
		"reliquary":                     {Name: "Реликварий", Description: "<p>Реликварий - небольших размеров, весом не больше трёх килограммов вакуумный куб, чья технология позволяет “вмещать” внутрь него множество объектов физической, так и информационной природы.</p>"},
		"block_il":                      {Name: "Блок “ИЛ”", Description: "<p>Блок “ИЛ” -габаритные загрузочные блоки искусственной личности, которые “Синтеты” используют для хранения, переноса и установки собственного сознания в ту или иную форму.</p>"},
		"technological_map":             {Name: "Технологическая карта", Description: "<p>Технологическая карта - передовой, удобный и незамысловатый способ по хранению-передаче больших массивов данных. </p>"},
		"political_message":             {Name: "Политическое послание", Description: "<p>Политическое послание - требования, претензии, нужды и ультиматумы. Как правило, подобное содержится в этих временных держателях данных.</p>"},
		"trade_offer":                   {Name: "Торговое предложение", Description: "<p>Торговое предложение - сделка, оговоренные суммы и конкретные поставки между сторонами, что указаны на данном носителе данных. Информация конфиденциальна. </p>"},
		"data_block":                    {Name: "Блок данных", Description: "<p>Блок данных - обычные накопители “гражданского” образца, что используются для хранения и передачи данных различного направления. Производитель не обеспечивает безопасность информации.</p>"},
		"products":                      {Name: "Товары", Description: "<p>Товары - как правило произведённый продукт или добытая вещь, что упакована в специальную мембрану и участвует в торговом обороте.</p>"},
		"corps_of_the_prisoner_synthet": {Name: "Корпус пленного “Синтета”", Description: "<p>Корпус пленного “Синтета” - корпус, ходовая часть, орудия и несметное множество систем данного отключённого от источников питания и скомпонованного “Синтета”.</p>"},
		"scientific_data":               {Name: "Научные данные", Description: "<p>Научные данные - заархивированные, засекреченные и бесконечно ценные данные для тех, кто ценит вклад науки в повседневную жизнь.</p>"},
		"contribution":                  {Name: "Контрибуция", Description: "<p>Контрибуция - упакованные и помеченные денежные средства, переданные одной стороной в ходе проигрыше военного конфликта, другой.</p>"},
		"magnetic_resonator":            {Name: "Магнитные резонатор", Description: "<p>Магнитные резонатор - устройство силового воздействия посредством распространяемых магнитных волн, что приводят к непредсказуемым геофизическим последствиям.</p>"},
		"equipment_sold":                {Name: "Проданное оборудование", Description: "<p>Проданное оборудование - укреплённое, разложенное, описанное и готовое к отпуску и реализации оборудование самого разного назначения.</p>"},
		"living_flora_and_fauna":        {Name: "Живая флора и фауна", Description: "<p>Живая флора и фауна - герметичные колбы с искусственной атмосферой, где зарезервированы, как опасные, так и безопасные представители живой флоры и фауны планеты Veliri-6</p>"},
		"deactivated_reactor":           {Name: "Деактивированный реактор", Description: "<p>Деактивированный реактор - стандартизированный в среде “Синтетов” образец реактора, способный вырабатывать достаточную энергию, дабы запитывать ею целые базы. </p>"},
		"armament":                      {Name: "Вооружение", Description: "<p>Вооружение - бронированные грузовые ящики, вмещающие в себя стволы орудийных систем, запасные части, а также ящики с амуницией. </p>"},
		"blueprints":                    {Name: "Чертежи", Description: "<p>Чертежи - графический конструкторский документ, содержащий детальное изображение того или иного инженерного объекта. </p>"},
		"deactivated_bots":              {Name: "Деактивированные боты", Description: "<p>Деактивированные боты - отключённые от источников питания боты, которые подготовлены для ремонтных операций, транспортировки или продажи. </p>"},
		"ammunition_Gonchkins":          {Name: "Боеприпасы “Гонкчкинс”", Description: "<p>Боеприпасы “Гонкчкинс” - тип разгонного снаряда, который разработан специально для баллистического оружия “Гончкинс”. В зоне поражения, обладает невероятной разрушительной силой. </p>"},
		"subatomic_reactor":             {Name: "Субатомный реактор", Description: "<p>Субатомный реактор - хрупкий и невероятно опасный при собственном разрушении инженерный объект, способный запитывать целые базы “Синтетов”. </p>"},
		"scientific_materials":          {Name: "Научные материалы", Description: "<p>Научные материалы - задокументированные выводы, финальные отчёты и научные работы на самые разные темы.</p>"},
		"dispatch":                      {Name: "Депеша", Description: "<p>Депеша - дипломатическое письмо о требовании помощи, объявлении войны или банальных угрозах, лишённое огласки. </p>"},
		"scientific_equipment":          {Name: "Научное оборудование", Description: "<p>Научное оборудование - небольшие устройства и целые передвижные инженерные объекты научного толка. Лучшее приобретении для каждого начинающего изыскателя.</p>"},
		"terraforming_equipment":        {Name: "Терраформирующее оборудование", Description: "<p>Терраформирующее оборудование - передовые технологии как мобильного, так и стационарного толка, что способны изменять в угоду манипулирующего климатические условия самого разного спектра.</p>"},
		"artificially_bred_species":     {Name: "Искусственно выведенные виды", Description: "<p>Искусственно выведенные виды - отобранные и выращенные после тщательной генетической селекции виды, что перевозятся в специализированных контейнерах с поддержкой искусственной атмосферы.</p>"},
		"atmospheric_domes":             {Name: "Атмосферные купола", Description: "<p>Атмосферные купола - разобранные и закрепленные для транспортировки системы упоров, стен и стеклянных покрытий по воссозданию искусственной атмосферы нужного типа на глобальной участке той или иной территории.</p>"},
		"supplies":                      {Name: "Припасы", Description: "<p>Припасы - набор узко заказанных или крайне необходимых товаров для поддержания исправности и жизнеспособности различных объектов. </p>"},
		"security_bots":                 {Name: "Охранные боты", Description: "<p>Охранные боты - боты сугубо военного образца, что используются в патрулировании округи, проведении военных и миротворческих операций. Из-за простоты конструкторской идеи, их ИИ нередко склонен к девиантному поведению.</p>"},
		"ice_liquor":                    {Name: "Ice-liquor", Description: "<p>Загадочный артефакт, таящий в себе великую силу.</p>"},
		"weapon_nutrients":              {Name: "Питательные элементы орудий", Description: "<p>Расходные элементы использующиеся в энергетических видах орудий</p>"},
		"orbital_drop_beacons":          {Name: "Маяки орбитального сброса", Description: "<p>Используются для подачи сигнала орбитальным системам</p>"},
		"strange_box":                   {Name: "Странная коробка", Description: "<p>Странный ящик неизвестного происхождение, постоянно излучает сильный сигнал.</p>"}, // TODO

		"egg":                  {Name: "Яйцо", Description: "<p>Яиичко11</p>"},             // TODO
		"blue_fragile_capsule": {Name: "Голубая капсула", Description: "<p></p>"},          // TODO
		"red_fragile_capsule":  {Name: "Красная капсула", Description: "<p></p>"},          // TODO
		"ground_drone_3":       {Name: "Древний боевой дрон", Description: "<p></p>"},      // TODO
		"Replic_label":         {Name: "Ярлык фракции \"Replic\"", Description: "<p></p>"}, // TODO
		"teleport_hack":        {Name: "Взлом телепорта", Description: "<p>Одноразовое устройство которое позволяет переписать настройки доступа в кластерные сектора.</p><p>Помимо взлома перегружает точки выхода и сеть базы точки выхода из телепорта начинают работать как глушилки, а база и все ее сооружения становятся уязвимы к уничтожению.</p>"},
	},
}
