package descriptions

import _const "github.com/TrashPony/veliri-lib/const"

var WeaponDescription = map[string]map[string]DescriptionItem{
	_const.EN: {
		"small_missile":     {Name: "Centurion", Description: "<p> Independent development of the \"APD\" machine intelligence in order to create new weapon systems. \"Centurion\" - represented by a rocket system, assembled from samples of missile and salvo systems that once existed on the planet and trying to accommodate their best sides. In particular, it is possible to fire both \"homing\" and \"unguided\" missiles. </p>"},
		"replic_weapon_2":   {Name: "Aplex", Description: "<p> Aplex is another representative of the Replic weapon variety, which will appeal to all those who prefer to shower their enemies with an endless barrage of bullets. Aplex is a mass series of machine guns, which does not have sufficient lethality, however, the low cost of production and design features will help find their loyal followers. </p>"},
		"artillery":         {Name: "S-2500", Description: "<p> A relict development, already improved by the \"APD\" machine intelligence and representing a ballistic mortar with not the best characteristics. Regardless of the damage, it mostly suffers from low hitting accuracy without preliminary zeroing. </p>"},
		"explores_weapon_4": {Name: "O-Keot", Description: "<p> O-Keot is another development along with the \"EzE-T\" capabilities of laser weapons. This time, Explores weapons designers went in a different direction and managed to develop a massive beam splitter that works on the principle of a shotgun and literally melts the target in the affected area. </p>"},
		"reverses_weapon_4": {Name: "Pin", Description: "<p> “An annoying enemy? Tired of the battle? \" - The pin will end any dispute. </p> <p> This rocket launcher of devastating power, capable of firing both homing and unguided missiles. Sacrificing in exchange for damage with your gun traverse speed, reloading and total magazine capacity. </p> <p> Well, the price will additionally turn away from the means of mass destruction many \"amateurs\". </p>"},
		"tank_gun":          {Name: "Inhibitor", Description: "<p> Independent development of the \"APD\" machine intelligence in order to create new weapon systems. \"Inhibitor\" is the most common and effective enough gun within its framework. It is capable of hitting various targets, is not too expensive to manufacture and is competitive with analogues of \"Synthets\". </p>"},
		"replic_weapon_4":   {Name: "Crusher", Description: "<p> \"Wipe your opponents to dust!\" - so the lie of the assault shotgun - \"Crusher\". This is a formidable weapon, most effective at close range, which will be able to fully reveal its potential only for those who are not afraid to face the enemy \"face to face\". </p>"},
		"explores_weapon_1": {Name: "Ocelot", Description: "<p> The Ocelot is a standardized, off-the-shelf, medium penetration laser from Explores. If you are looking for a quality product, not the highest price, and most importantly - the ability to effectively hit most targets, Ocelot will handle it. </p>"},
		"explores_weapon_3": {Name: "EzE-T", Description: "<p> If you want a machine gun, but do not want to buy tons of ammunition - \"EzE-T\" is a specialized development by Explores regarding the development of the potential of combat lasers. This frequency emitter, if it does not hit the target, will at least demoralize anyone who tries to oppose you. </p>"},
		"big_missile":       {Name: "Agra", Description: "<p> A relict development, already improved by the \"APD\" machine intelligence and representing a large rocket launcher with colossal damage, but a small magazine and a slow gun traverse speed. Against the background with analogues of \"Synthets\", \"Agra\" loses in almost all parameters, except for tangible damage. </p>"},
		"replic_weapon_1":   {Name: "Furiosa", Description: "<p> Would you like to appreciate the power of Replic? Furiosa - will give you that last opportunity. This mortar deals so devastating damage that it will not leave a trace of your opponents. The ideal solution for those who prefer to hit targets at a long distance along a hinged trajectory, sacrificing accuracy and speed of rotation of the gun. </p>"},
		"reverses_weapon_1": {Name: "Judge", Description: "<p> Annihilate space. Don't give the enemy a chance to get away. Crush with a huge salvo of eight consecutive missiles and deliver the final judgment. The Judge is the Reverses' advanced missile armament. </p>"},
		"big_laser":         {Name: "P-0 / A", Description: "<p> A relict development, already improved by the APD machine intelligence and representing a combat beam launching unit with mediocre characteristics of the destructive properties. </p>"},
		"small_laser":       {Name: "VHF", Description: "<p> Independent development of the \"APD\" machine intelligence in order to create new weapon systems. But due to the insufficient material base, as well as the use of schemes of the previous era, the product cannot boast of something outstanding, although it is not one step lower in comparison with the analogues of \"Synthets\" regarding laser-beam armament. </p>"},
		"replic_weapon_3":   {Name: "Condor", Description: "<p> If you are looking for something in between - Condor - the recommendation from Replic. This gun has managed to establish itself as reliable, powerful enough and comfortable enough to firmly take a place in the Replic army. </p>"},
		"far_god_1":         {Name: "LBL-X", Description: "<p>Officially, previously, never mentioned anywhere, an energy weapon that is a particle projector cannon by its characteristics. Apparently, LBL-X was created under artisanal conditions by some extremely talented synth gunsmith.</p>"},
		"far_god_2":         {Name: "Leffy", Description: "<p>Volley fire rocket launcher presented by an easily manipulable slipway with many connected barrels. It is believed that Leffy is not the most successful design solution of Reversec. It is known that a batch of this weapon was destroyed, but Terreus still managed to steal one of its samples.</p>"},
		"far_god_3":         {Name: "Ultra-10", Description: "<p>An anti-aircraft machine gun that was adapted for firing at ground targets and created by Replics. Subsequently, the 'Ultra' model was artisanal upgraded by Iair. After several unsuccessful iterations, they received the most effective variation.</p>"},
		"far_god_4":         {Name: "Impulse", Description: "<p>A creation of Replics, which is a ballistic weapon of impressive destructive power, but it did not enter mass production due to its size and overwhelming force of reverse inertia.</p>"},
		"far_god_5":         {Name: "far_god_5", Description: "<p>far_god_5</p>"},
		"far_god_6":         {Name: "far_god_6", Description: "<p>far_god_6</p>"},
		"far_god_7":         {Name: "far_god_7", Description: "<p>far_god_7</p>"},
		"far_god_8":         {Name: "far_god_8", Description: "<p>far_god_8</p>"},
		"far_god_9":         {Name: "far_god_9", Description: "<p>far_god_9</p>"},
		"melee_1":           {Name: "Battering Spike", Description: "<p>A tactical ramming device.</p><p>Converts the vehicle's speed into crushing force.</p>"},
		"melee_2":           {Name: "Tesla Poker", Description: "<p>A tactical ramming device.</p><p>Upon contact, it creates a sustained plasma arc that inflicts thermal damage to enemies.</p>"},
		"rust_1":            {Name: "rust_1", Description: "<p>rust_1</p>"},
		"rust_2":            {Name: "rust_2", Description: "<p>rust_2</p>"},
		"rust_3":            {Name: "rust_3", Description: "<p>rust_3</p>"},
		"rust_4":            {Name: "rust_4", Description: "<p>rust_4</p>"},
		"rust_5":            {Name: "rust_5", Description: "<p>rust_5</p>"},

		"explores_weapon_2": {Name: "Filaz", Description: "<p>Cheap, unpretentious, and mass-produced — that is the best way to describe the \"Filaz\" line of beam projectors. The saving grace of this niche Explores product is the high accuracy of its cutting beam.</p>"},
		"explores_weapon_5": {Name: "Filaz \"Cataclysm\"", Description: "<p>A heavy embodiment of the \"Filaz\" philosophy, turning a precise cutting beam into an instrument of mass destruction.</p><p>In addition to its powerful main beam, which inherited the accuracy of its predecessor, the \"Cataclysm\" periodically fires unstable cluster projectiles that burst over an area. This makes the weapon equally effective against single targets and enemy clusters alike.</p>"},
		"explores_weapon_6": {Name: "Filaz \"Inferno\"", Description: "<p>An evolution of the \"Filaz\" line in which Explores engineers perfected the concept of thermal flux.</p><p>The \"Inferno\" retains the signature accuracy of the base model, but each beam pulse carries an accumulating thermal charge. The longer the weapon keeps a target in focus, the more the beam heats up and the higher the total damage.</p>"},

		"reverses_weapon_2": {Name: "Discharge", Description: "<p>A weapon standardized for Reverses military needs, capable of striking targets with two rapid missiles. Its moderate rate of fire and small magazine are compensated by the turret's fast traverse speed.</p>"},
		"reverses_weapon_3": {Name: "Discharge \"Storm\"", Description: "<p>A high-rate-of-fire modernization of the \"Discharge\", turning a standard weapon into a missile storm.</p><p>Reinforced reloading drives and a lightened frame let the \"Storm\" fire missiles nearly twice as fast as its predecessor, while the enlarged magazine gives the enemy no moment of respite.</p>"},
		"reverses_weapon_6": {Name: "Discharge \"Hammer\"", Description: "<p>A heavy embodiment of the \"Discharge\" philosophy, upgrading the weapon to large-caliber missiles.</p><p>A reinforced load-bearing frame and composite armor protection for the launch containers let the \"Hammer\" withstand the recoil of a heavy missile volley.</p>"},

		"replic_weapon_5": {Name: "Condor \"Squall\"", Description: "<p>A twin modification of the \"Condor\", turning a reliable cannon into an impenetrable wall of fire.</p><p>Two synchronized barrels on a single reinforced frame and accelerated ammunition-feed drives let the \"Squall\" literally bury a target in a hail of shells. The enlarged ammunition capacity gives the enemy not a moment of respite.</p>"},
		"replic_weapon_6": {Name: "Crusher \"Sledgehammer\"", Description: "<p>A deep modernization of the assault shotgun, pushing the boundaries of close and mid-range combat.</p><p>Improved ballistics and a reinforced barrel let the \"Sledgehammer\" hit targets at distances beyond the reach of the standard \"Crusher\", while a refined targeting system makes every shot more accurate.</p>"},

		"reverses_weapon_5": {Name: "Torpedo complex", Description: "<p>A rack with a small launch tube capable of firing unguided small-sized missiles. The standard weapon set of all synthetics who joined Reverses.</p>"},
	},
	_const.RU: {
		"replic_weapon_1": {Name: "Фуриоса", Description: "<p>Желаете по достоинству оценить мощь Replic? Фуриоса - даст вам такую последнюю возможность. Эта мортира наносит настолько сокрушительный урон, что не оставит от ваших соперников и следа. Идеальное решение для тех, кто предпочитает поражать цели на большом расстоянии по навесной траектории, пожертвовав взамен точностью и скоростью поворота орудия.</p>"},
		"replic_weapon_2": {Name: "Аплекс", Description: "<p>Аплекс - очередной представитель оружейного разнообразия Replic, который придётся по душе всем тем, кто предпочитает поливать своих врагов нескончаемым градом пуль. Аплекс - массовая серия пулемётов, что не обладает достаточной убойностью, однако, дешевизна производства и особенности конструкции, помогут найти своих преданных приверженцев.</p>"},
		"replic_weapon_3": {Name: "Кондор", Description: "<p>Если вы ищете нечто среднее во всём - Кондор - рекомендация от Replic. Эта пушка сумела зарекомендовать себя как безотказная, в меру мощная и достаточно удобная, чтобы прочно занять место в армии Replic.</p>"},
		"replic_weapon_4": {Name: "Сокрушитель", Description: "<p>\"Сотрите своих противников в пыль!\" - так гласить солган штурмового дробовика - \"Сокрушитель\".  Это грозное оружие, максимально эффективное на близких дистанциях, что сумеют полностью раскрыть свой потенциал только у тех, кто не боится столкнуться с врагом \"лицом к лицу\".</p>"},

		"explores_weapon_1": {Name: "Оцелот", Description: "<p>Оцелот - это стандартизированный под множество нужд и серийно выпускаемый лазер средней пробивной силы от Explores. Если вы ищете качественного изделия, не самой большой цены и главное - возможности эффективно поражать большинство целей, \"Оцелот\" справится с этим.</p>"},
		"explores_weapon_3": {Name: "EzE-T", Description: "<p>Хотите пулемёт, но не желаете закупать тонны амуниции - \"EzE-T\" специализированная разработка Explores касательно развития потенциала боевых лазеров. Данный частотный испускатель, если и не попадёт в цель, то как минимум деморализует любого, кто попытается выступить против вас.</p>"},
		"explores_weapon_4": {Name: "О-Кеот", Description: "<p>О-Кеот - ещё одно развитие наряду с \"EzE-T\" возможностей лазерного вооружения. На сей раз, оружейные конструкторы Explores пошли по иному направлению и сумели разработать массовый делитель лучей, работающий по принципу дробовика и буквально расплавляющий цель в зоне поражения.</p>"},
		"reverses_weapon_1": {Name: "Судья", Description: "<p>Аннигилируйте пространство. Не дайте шанса врагу уйти.  Сокрушите огромным залпом из восьми последовательных ракет и вынесите окончательный приговор. Судья - передовое ракетное вооружение Reverses. </p>"},
		"reverses_weapon_4": {Name: "Булавка", Description: "<p>\"Назойливый противник? Утомило сражение?\" - Булавка окончит любой спор. </p> <p>Эта ракетная установка сокрушительной силы, способная вести огонь, как самонаводящимися, так и неуправляемыми ракетами. Жертвуя в обмен на урон своей скоростью поворота орудия, перезарядкой и общей вместимостью магазина.</p> <p>Ну а цена, дополнительно отвернёт от средства массового уничтожения многих \"любителей\".</p>"},
		"artillery":         {Name: "С-2500", Description: "<p>Реликтовая разработка, улучшенная уже машинным разумом \"APD\" и представляющая из себя баллистическую мортиру с не самыми лучшими характеристиками. Не взирая на урон, в основном страдает низкой точностью попадания без предварительной пристрелки.</p>"},
		"big_laser":         {Name: "П-0/А", Description: "<p>Реликтовая разработка, улучшенная уже машинным разумом \"APD\" и представляющая из себя боевой лучепускательный агрегат с посредственными характеристиками поражающего свойства.</p>"},
		"big_missile":       {Name: "Агра", Description: "<p>Реликтовая разработка, улучшенная уже машинным разумом \"APD\" и представляющая из себя большую ракетную установку с колоссальным уроном, но малым магазином и малой скоростью поворота орудия. На фоне с аналогами \"Синтетов\", \"Агра\" проигрывает практически по всем параметрам кроме ощутимых повреждений.</p>"},
		"small_laser":       {Name: "УКВ", Description: "<p>Самостоятельная разработка машинного разума \"APD\" с целью создания новых оружейных систем.  Но из-за недостаточной материальной базы, а также задействования схем предыдущей эпохи, изделие не может похвастаться чем-то выдающимся, хотя и не стоит на ступени ниже по сравнению с аналогами \"Синтетов\" касательно лазерно-лучевого вооружения.</p>"},
		"small_missile":     {Name: "Центурион", Description: "<p>Самостоятельная разработка машинного разума \"APD\" с целью создания новых оружейных систем.  \"Центурион\" - представлен ракетной системой, собранной из образцов некогда существовавших на планете ракетно-залповых систем и, пытающийся вместить в себе лучшие их стороны.  В частности, возможно ведения огня как \"самонаводящимися\", так и \"неуправляемыми\" ракетами.</p>"},
		"tank_gun":          {Name: "Ингибитор", Description: "<p>Самостоятельная разработка машинного разума \"APD\" с целью создания новых оружейных систем.  \"Ингибитор\" - самая обыденная и достаточная эффективная в своих рамках пушка. Она способна поражать различные цели, не слишком дорога в производстве и конкурентоспособна с аналогами \"Синтетов\".</p>"},
		"far_god_1":         {Name: "LBL-X", Description: "<p>Официально, ранее, нигде не упоминаемое энергетическое оружие, что по своим характеристикам является - пушкой-проектором частиц. Судя по всему, LBL-X был создан при кустарных условиях неким крайне талантливым синтетом-оружейником.</p>"},
		"far_god_2":         {Name: "Леффи", Description: "<p>Ракетное вооружение залпового огня, представленное легко манипулируемым стапелем со множеством соединённых стволов. Принято считать, что Леффи - не самое удачное конструкторское решение Reverses. Известно, что партия данного оружия была подвергнута уничтожению, однако Терреусу, всё-таки удалось выкрасть один из его образцов.</p>"},
		"far_god_3":         {Name: "Ультра-10", Description: "<p>Зенитный пулемёт, что был адаптирован для ведения огня по наземным целям и созданный Replics. Впоследствии, модель “Ультра” была кустарно модернизирована Иаиром. Спустя несколько неудачных итераций, получив максимально эффективную вариацию.</p>"},
		"far_god_4":         {Name: "Импульс", Description: "<p>Творение Replics, представляющее из себя баллистическое орудие внушительной поражающей силы, которое не вошло в массовое производство из-за своих габаритов и непреодолимой силы обратной инерции.</p>"},
		"far_god_5":         {Name: "far_god_5", Description: "<p>far_god_5</p>"},
		"far_god_6":         {Name: "far_god_6", Description: "<p>far_god_6</p>"},
		"far_god_7":         {Name: "far_god_7", Description: "<p>far_god_7</p>"},
		"far_god_8":         {Name: "far_god_8", Description: "<p>far_god_8</p>"},
		"far_god_9":         {Name: "far_god_9", Description: "<p>far_god_9</p>"},
		"melee_1":           {Name: "Таранный шип", Description: "<p>Тактическое таранное устройство.</p> <p>Превращает скорость машины в сокрушительную силу.</p>"},
		"melee_2":           {Name: "Тесла-кочерга", Description: "<p>Тактическое таранное устройство.</p> <p>При контакте создает устойчивую плазменную дугу, наносящую термические повреждения противникам.</p>"},
		"rust_1":            {Name: "rust_1", Description: "<p>rust_1</p>"},
		"rust_2":            {Name: "rust_2", Description: "<p>rust_2</p>"},
		"rust_3":            {Name: "rust_3", Description: "<p>rust_3</p>"},
		"rust_4":            {Name: "rust_4", Description: "<p>rust_4</p>"},
		"rust_5":            {Name: "rust_5", Description: "<p>rust_5</p>"},

		"reverses_weapon_5": {Name: "Торпедный комплекс", Description: "<p>Стойка с малым пусковым тубусом, способная вести огонь неуправляемыми малогабаритными ракетами. Стандартный оружейный набор всех синтетов вступивших к Reverses.</p>"},

		"explores_weapon_2": {Name: "Филаз", Description: "<p>Дешёвый, неприхотливый и массовый - самое лучшее, что можно сказать о линейке лучепускателей - \"Филаз\".  Отдушиной в данном нишевом товаре от Explores можно считать высокую точность попадания режущего луча по цели.</p>"},
		"explores_weapon_5": {Name: "Филаз \"Катаклизм\"", Description: "<p>Тяжёлое воплощение философии \"Филаза\", превращающее точный режущий луч в инструмент массового разрушения.</p><p>Помимо мощного основного луча, унаследовавшего точность прародителя, \"Катаклизм\" с заданной периодичностью выпускает нестабильные пучковые снаряды, разрывающиеся по площади. Это делает орудие одинаково эффективным как против одиночных целей, так и против скоплений противников.</p>"},
		"explores_weapon_6": {Name: "Филаз \"Инферно\"", Description: "<p>Развитие линейки \"Филаз\", в котором инженеры Explores довели до совершенства идею нагревательных потоков.</p><p>\"Инферно\" сохраняет фирменную точность базовой модели, но каждый импульс луча несёт накопительный термический заряд. Чем дольше орудие держит цель в фокусе, тем сильнее разогревается поток и тем выше итоговый урон.</p>"},

		"reverses_weapon_2": {Name: "Разряд", Description: "<p>Стандартизированное под войсковые нужды Reverses орудие - способное путём выпуска двух стремительных ракет, поражать цели. Средний темп стрельбы и маленький объём заряжаемых зарядов, компенсируется быстротой поворота орудия.</p>"},
		"reverses_weapon_3": {Name: "Разряд \"Шторм\"", Description: "<p>Скорострельная модернизация \"Разряда\", превращающая стандартное орудие в ракетный ливень.</p><p>Усиленные приводы перезарядки и облегчённый каркас позволяют \"Шторму\" выпускать ракеты почти вдвое быстрее предшественника, а увеличенный магазин не даёт врагу ни секунды передышки.</p>"},
		"reverses_weapon_6": {Name: "Разряд \"Молот\"", Description: "<p>Тяжёлое воплощение философии \"Разряда\", переводящее орудие на крупнокалиберные ракеты.</p><p>Усиленный несущий каркас и композитная бронезащита пусковых контейнеров позволяют \"Молоту\" выдерживать отдачу от залпа больших ракет.</p>"},

		"replic_weapon_5": {Name: "Кондор \"Шквал\"", Description: "<p>Спаренная модификация \"Кондора\", превращающая надёжную пушку в неприступную стену огня.</p><p>Два синхронизированных ствола на едином усиленном каркасе и приводы ускоренной подачи боеприпасов позволяют \"Шквалу\" буквально засыпать цель градом снарядов. Увеличенный боезапас не даёт врагу ни мгновения на передышку.</p>"},
		"replic_weapon_6": {Name: "Сокрушитель \"Кувалда\"", Description: "<p>Глубокая модернизация штурмового дробовика, расширяющая границы ближнего и среднего боя.</p><p>Улучшенная баллистика и усиленный ствол позволяют \"Кувалде\" поражать цели на дистанциях, недоступных стандартному \"Сокрушителю\", а доработанная система прицеливания делает каждый залп точнее.</p>"},
	},
	_const.ZhCN: {
		"replic_weapon_1":   {Name: "狂暴", Description: "<p>想要充分体验Replic的威力？“狂暴”将给你最后的机会。这款迫击炮造成毁灭性伤害，让对手无处可逃。适合喜欢通过高抛弹道远距离打击目标的玩家，但需牺牲精度和炮塔转向速度。</p>"},
		"replic_weapon_2":   {Name: "阿普莱克斯", Description: "<p>“阿普莱克斯”是Replic武器多样化的又一代表，适合那些喜欢用无尽弹雨压制敌人的玩家。作为机枪系列，虽然单发杀伤力不足，但生产成本低廉和结构特点使其拥有忠实拥趸。</p>"},
		"replic_weapon_3":   {Name: "秃鹫", Description: "<p>若您寻求全能型武器——Replic推荐“秃鹫”。这门火炮以稳定可靠、威力适中且操作便捷著称，在Replic军队中占据重要地位。</p>"},
		"replic_weapon_4":   {Name: "粉碎者", Description: "<p>“将敌人碾作齑粉！”——突击霰弹枪“粉碎者”的格言。这把近战利器在贴身距离展现毁灭性威力，专为无畏近身搏斗的勇者打造。</p>"},
		"explores_weapon_1": {Name: "豹猫", Description: "<p>“豹猫”——Explores量产的中等穿透力标准化激光武器。如果您追求性价比高且能有效打击多数目标的装备，这款武器是理想选择。</p>"},
		"explores_weapon_3": {Name: "EzE-T", Description: "<p>想要机枪火力却不愿囤积弹药？“EzE-T”是Explores开发的激光战斗系统。即使未能命中，其高频射线也足以震慑任何敌人。</p>"},
		"explores_weapon_4": {Name: "奥基奥特", Description: "<p>“奥基奥特”——Explores在激光武器领域的又一突破。这款霰弹式光束分裂器能在打击区域产生熔毁效果，展现全新杀伤维度。</p>"},
		"reverses_weapon_1": {Name: "审判者", Description: "<p>湮灭空间，断绝退路。用八连发火箭齐射宣判最终裁决。“审判者”——Reverses尖端导弹系统的代名词。</p>"},
		"reverses_weapon_4": {Name: "毒刺", Description: "<p>“纠缠不休的敌人？厌倦鏖战？‘毒刺’终结一切争议。这款毁灭性导弹系统可发射自导/非制导火箭，以转向速度、装填时间和载弹量为代价换取极致杀伤。高昂造价更使其成为‘大规模毁灭性武器爱好者’的专属。</p>"},
		"artillery":         {Name: "S-2500", Description: "<p>经机械智能APD改造的遗迹科技，作为弹道迫击炮性能平庸。尽管伤害可观，但缺乏预瞄时精度显著下降。</p>"},
		"big_laser":         {Name: "P-0/A", Description: "<p>APD优化的遗迹科技产物，作为光束发射装置仅具备中等杀伤效能。</p>"},
		"big_missile":       {Name: "阿格拉", Description: "<p>APD强化的遗迹导弹系统，虽单发伤害惊人，但在载弹量、转向速度等参数上全面落后于合成者同类武器。</p>"},
		"small_laser":       {Name: "UKV", Description: "<p>APD自主研发的激光武器，采用旧时代设计架构。虽无突出优势，但性能不逊于合成者同类光束武器。</p>"},
		"small_missile":     {Name: "百夫长", Description: "<p>APD整合古代火箭技术打造的导弹系统，兼容自导/非制导模式发射，试图融合历史设计的精华。</p>"},
		"tank_gun":          {Name: "抑制剂", Description: "<p>APD研发的标准火炮，性价比优异，综合性能可与合成者同类产品竞争。</p>"},
		"far_god_1":         {Name: "LBL-X", Description: "<p>未在任何官方记录中出现的粒子投射武器，推测由天才合成者武器匠手工打造。</p>"},
		"far_god_2":         {Name: "莱菲", Description: "<p>多管齐射导弹系统，因设计缺陷被Reverses列入销毁名单。泰瑞乌斯成功窃取唯一存世样本。</p>"},
		"far_god_3":         {Name: "终极-10", Description: "<p>Replics原产防空机枪经雅伊尔非法改造，最终成为适配地面作战的强化版本。</p>"},
		"far_god_4":         {Name: "脉冲", Description: "<p>Replics开发的巨型弹道武器，因体积过大和后坐力问题未能量产。</p>"},
		"far_god_5":         {Name: "far_god_5", Description: "<p>far_god_5</p>"},
		"far_god_6":         {Name: "far_god_6", Description: "<p>far_god_6</p>"},
		"far_god_7":         {Name: "far_god_7", Description: "<p>far_god_7</p>"},
		"far_god_8":         {Name: "far_god_8", Description: "<p>far_god_8</p>"},
		"far_god_9":         {Name: "far_god_9", Description: "<p>far_god_9</p>"},
		"melee_1":           {Name: "冲击尖刺", Description: "<p>一种战术冲撞装置。</p><p>能将载具的速度转化为毁灭性的冲击力。</p>"},
		"melee_2":           {Name: "特斯拉刺棍", Description: "<p>一种战术冲撞装置。</p><p>接触时会产生持续等离子电弧，对敌人造成热能伤害。</p>"},
		"rust_1":            {Name: "rust_1", Description: "<p>rust_1</p>"},
		"rust_2":            {Name: "rust_2", Description: "<p>rust_2</p>"},
		"rust_3":            {Name: "rust_3", Description: "<p>rust_3</p>"},
		"rust_4":            {Name: "rust_4", Description: "<p>rust_4</p>"},
		"rust_5":            {Name: "rust_5", Description: "<p>rust_5</p>"},

		"reverses_weapon_5": {Name: "鱼雷复合系统", Description: "<p>紧凑型非制导火箭发射架，Reverses新兵标准配置。</p>"},

		"explores_weapon_2": {Name: "菲拉兹", Description: "<p>廉价、可靠、量产——这就是对「菲拉兹」系列光束发射器最好的形容。这款Explores小众产品最大的亮点，是其切割光束极高的命中精度。</p>"},
		"explores_weapon_5": {Name: "菲拉兹 \"灾变\"", Description: "<p>「菲拉兹」理念的沉重化身，将精准的切割光束化为大规模毁灭的工具。</p><p>除了继承前辈精度的强力主光束外，「灾变」还会周期性地发射不稳定的集束弹，在区域内爆炸。这使它无论对付单个目标还是敌人群组都同样有效。</p>"},
		"explores_weapon_6": {Name: "菲拉兹 \"炼狱\"", Description: "<p>「菲拉兹」系列的进化之作，Explores的工程师将热流理念臻于完美。</p><p>「炼狱」保留了基础型号的标志性精度，但每一束脉冲都携带不断累积的热能。瞄准目标的时间越长，光束温度越高，最终伤害也越大。</p>"},

		"reverses_weapon_2": {Name: "齐射", Description: "<p>一款为Reverses军事需求标准化的武器，通过发射两枚疾速导弹打击目标。中等的射速和较小的弹容量，由其炮塔的快速转向来弥补。</p>"},
		"reverses_weapon_3": {Name: "齐射 \"风暴\"", Description: "<p>「齐射」的高射速升级型号，将标准武器化为导弹风暴。</p><p>强化的装填驱动和轻量化的框架让「风暴」的发射速度几乎是前辈的两倍，而扩容的弹仓则不给敌人丝毫喘息之机。</p>"},
		"reverses_weapon_6": {Name: "齐射 \"战锤\"", Description: "<p>「齐射」理念的沉重化身，将武器升级为发射大口径导弹。</p><p>强化的承重框架和发射容器的复合装甲防护，使「战锤」能够承受重型导弹齐射的后坐力。</p>"},

		"replic_weapon_5": {Name: "神鹰 \"骤雨\"", Description: "<p>「神鹰」的双管改装型号，将可靠的火炮化为不可逾越的火墙。</p><p>两门同步的炮管安装在同一个强化框架上，配合加速供弹驱动，让「骤雨」能以弹雨倾泻目标。扩容的弹药量不给敌人片刻喘息之机。</p>"},
		"replic_weapon_6": {Name: "粉碎者 \"重锤\"", Description: "<p>突击霰弹枪的深度改装型号，拓展了近战与中距离作战的边界。</p><p>改良的弹道和强化的枪管让「重锤」能打击标准「粉碎者」无法企及的距离，而改进的瞄准系统则让每一次射击都更加精准。</p>"},
	},
}
