package handbook

import (
	"github.com/TrashPony/veliri-lib/handbook/interface_window"
)

var IndexInterface = map[string]map[string]map[string]string{
	"Main": {},
	"Auth": {},
	"Wiki": {},
}

var GameInterface = map[string]map[string]map[string]string{
	"Alerts":            interface_window.Alerts,
	"AttackDialog":      interface_window.AttackDialog,
	"AudioPlayer":       interface_window.AudioPlayer,
	"BoxPass":           interface_window.BoxPass,
	"BuildMenu":         interface_window.BuildMenu,
	"Chat":              interface_window.Chat,
	"ChoiceFraction":    interface_window.ChoiceFraction,
	"Corporation":       interface_window.Corporation,
	"Department":        interface_window.Department,
	"DetailItem":        interface_window.DetailItem,
	"EquipBar":          {},
	"FractionMarket":    interface_window.FractionMarket,
	"FriendList":        interface_window.FriendList,
	"Game":              {},
	"Gate":              interface_window.Gate,
	"GeoScan":           interface_window.GeoScan,
	"Global":            interface_window.Global,
	"GlobalMap":         interface_window.GlobalMap,
	"GroupMenu":         interface_window.GroupMenu,
	"Hangar":            interface_window.Hangar,
	"Help":              interface_window.Help,
	"HelpControl":       interface_window.HelpControl,
	"Inventory":         interface_window.Inventory,
	"Loader":            interface_window.Loader,
	"Lobby":             interface_window.Lobby,
	"Mail":              interface_window.Mail,
	"Market":            interface_window.Market,
	"MenuBar":           interface_window.MenuBar,
	"MiniGames":         interface_window.MiniGames,
	"MiniMap":           interface_window.MiniMap,
	"Missions":          interface_window.Missions,
	"ModalNotify":       interface_window.ModalNotify,
	"News":              interface_window.News,
	"NPCTrade":          interface_window.NPCTrade,
	"ObjectDialog":      interface_window.ObjectDialog,
	"PrefabricatedMenu": interface_window.PrefabricatedMenu,
	"Preloader":         {},
	"ProcessorRoot":     interface_window.ProcessorRoot,
	"SelectTarget":      interface_window.SelectTarget,
	"SendCredits":       interface_window.SendCredits,
	"ServerState":       {},
	"Settings":          interface_window.Settings,
	"StatusBar":         {},
	"TechnologyMenu":    interface_window.TechnologyMenu,
	"Training":          {},
	"Transfer":          {},
	"UserStat":          interface_window.UserStat,
	"Window":            {},
	"Workbench":         interface_window.Workbench,
	"Deviant":           interface_window.Deviant,
	"GameMenu":          interface_window.GameMenu,
}
